### ISSUE TITLE
Pokemon go bot wont work but was working earlier

### ISSUE THREAD

**Issue by icyeti** [jabbink/PokemonGoBot#1004]
My pokemon go bot won't work please help me. Thanks!

11 Aug 15:07:59 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:07:59 [default: WalkingLoop] - Walking to (45.190632, 5.729414) in 242.26504241819518 steps.
11 Aug 15:08:00 [default: WalkingLoop] - Pausing to catch pokemon...
11 Aug 15:08:00 [default: ProfileLoop] - Profile update: 401200 XP on LVL 22; 66200/100000 (66.20%) to LVL 23
11 Aug 15:08:00 [default: ProfileLoop] - XP gain: 0 XP in 0 mins; XP rate: 0/hr
Pokemon caught/transferred: 0/0; Pokemon caught from lures: 0; Items caught/dropped: 0/0;
Pokebank 250/250; Stardust 102037; Inventory 207/350
11 Aug 15:08:04 [default: BotLoop] - Getting map of (45.18947053183964, 5.729306763456525)
11 Aug 15:08:04 [default: BotLoop] - Found pokemon SPEAROW
11 Aug 15:08:04 [default: BotLoop] - Encounter failed with result: POKEMON_INVENTORY_FULL
11 Aug 15:08:04 [default: BotLoop] - Disabling catching of Pokemon
11 Aug 15:08:05 [default: BotLoop] - Dropped 1x ITEM_HYPER_POTION
11 Aug 15:08:05 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:08:09 [default: BotLoop] - Getting map of (45.18962024407203, 5.729307489196845)
11 Aug 15:08:09 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:08:14 [default: BotLoop] - Getting map of (45.18973341386979, 5.729379899511523)
11 Aug 15:08:14 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:08:19 [default: BotLoop] - Getting map of (45.18988673482002, 5.729370522546437)
11 Aug 15:08:19 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:08:24 [default: BotLoop] - Getting map of (45.189985952253934, 5.729359640600264)
11 Aug 15:08:24 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:08:29 [default: BotLoop] - Getting map of (45.19012199834076, 5.729399717471983)
11 Aug 15:08:29 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:08:34 [default: BotLoop] - Getting map of (45.19029625868019, 5.729416848180311)
11 Aug 15:08:34 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:08:35 [default: PokestopLoop] - Looting nearby pokestop 257fb6c9e3704648ba87935b28e2304f.16
11 Aug 15:08:36 [default: PokestopLoop] - Looted pokestop 257fb6c9e3704648ba87935b28e2304f.16; +100 XP: [1xITEM_POKE_BALL, 1xITEM_RAZZ_BERRY, 1xITEM_SUPER_POTION]
11 Aug 15:08:39 [default: BotLoop] - Getting map of (45.190320034966525, 5.729387559354474)
11 Aug 15:08:39 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:08:44 [default: BotLoop] - Getting map of (45.19049675143964, 5.7293626146104835)
11 Aug 15:08:44 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:08:49 [default: BotLoop] - Getting map of (45.19056264112652, 5.729412832327936)
11 Aug 15:08:49 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:08:50 [default: WalkingLoop] - Destination reached.
11 Aug 15:08:51 [default: WalkingLoop] - Walking to (45.190996, 5.729643) in 77.40039018529426 steps.
11 Aug 15:08:52 [default: PokestopLoop] - Looting nearby pokestop 4fad8362bdb84c268abe1e2110cc19ff.16
11 Aug 15:08:52 [default: PokestopLoop] - Looted pokestop 4fad8362bdb84c268abe1e2110cc19ff.16; +100 XP: [1xITEM_GREAT_BALL, 2xITEM_POKE_BALL]
11 Aug 15:08:54 [default: BotLoop] - Getting map of (45.19066510909595, 5.729442820815746)
11 Aug 15:08:54 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:08:59 [default: BotLoop] - Getting map of (45.19081214617544, 5.729509510034487)
11 Aug 15:08:59 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:09:00 [default: ProfileLoop] - Profile update: 401400 XP on LVL 22; 66400/100000 (66.40%) to LVL 23
11 Aug 15:09:00 [default: ProfileLoop] - XP gain: 200 XP in 1 mins; XP rate: 12,000/hr
Pokemon caught/transferred: 0/0; Pokemon caught from lures: 0; Items caught/dropped: 6/1;
Pokebank 250/250; Stardust 102037; Inventory 212/350
11 Aug 15:09:02 [default: PokestopLoop] - Looting nearby pokestop 744e6dee1d914c65983d45663ad7ab94.16
11 Aug 15:09:03 [default: PokestopLoop] - Looted pokestop 744e6dee1d914c65983d45663ad7ab94.16; +100 XP: [3xITEM_POKE_BALL]
11 Aug 15:09:04 [default: BotLoop] - Getting map of (45.19091219077787, 5.729557937018777)
11 Aug 15:09:04 [default: BotLoop] - Dropped 1x ITEM_SUPER_POTION
11 Aug 15:09:05 [default: BotLoop] - Dropped 3x ITEM_POKE_BALL
11 Aug 15:09:05 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:09:08 [default: WalkingLoop] - Destination reached.
11 Aug 15:09:08 [default: WalkingLoop] - Walking to (45.191578, 5.728394) in 209.15116775792038 steps.
11 Aug 15:09:09 [default: BotLoop] - Getting map of (45.191029392450375, 5.729590624430612)
11 Aug 15:09:09 [default: BotLoop] - Dropped 3x ITEM_POKE_BALL
11 Aug 15:09:09 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:09:14 [default: BotLoop] - Getting map of (45.191075243187825, 5.72953246024122)
11 Aug 15:09:14 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
11 Aug 15:09:19 [default: BotLoop] - Getting map of (45.19113097304108, 5.729338445528115)
11 Aug 15:09:19 [default: BotLoop] - Error running loop BotLoop!
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by Mixone-FinallyHere** [comment]
use Issues template please 😞 
------
This error is a new one though

**Comment by langerhans** [comment]
Does restarting the bot fix this?

**Comment by icyeti** [comment]
No it doesnt

**Comment by Peyphour** [comment]
How many object of each type do you have in your bag and your config file please

**Comment by icyeti** [comment]
Bag: 30 super potion, 50 hyper, 20 revive, 1 lucky egg, 1 incense, 43 pokeball, 33 great, 5 ultra, 3 lure, 52 razz
Config: 
# Max number of each item that the bot should keep if "drop_items" is enabled
# Use -1 in an item to never drop this specific item
# The default values add up to 350
item_revive=20
item_max_revive=10
item_potion=0
item_super_potion=30
item_hyper_potion=50
item_max_potion=50
item_poke_ball=40
item_great_ball=50
item_ultra_ball=50
item_master_ball=-10
item_razz_berry=40
item_lucky_egg=-1
item_incense=-1
item_lure_module=-1

**Comment by Mixone-FinallyHere** [comment]
AHA!

**Comment by Mixone-FinallyHere** [comment]
-10 Master ball

**Comment by Mixone-FinallyHere** [comment]
maybe not the actual issue though

**Comment by Mixone-FinallyHere** [comment]
yes it is that
![This](https://github.com/jabbink/PokemonGoBot/blob/0ce550424939c75bc8743145e44d5a4fef5fbd3e/src/main/kotlin/ink/abb/pogo/scraper/tasks/DropUselessItems.kt#L86-L92)
since it is not -1 it goes inside, then
`val count = item.count - it.value`
makes count = 10 because `item.count` is 0 and `it.value` is -10 (therefore 0 - -10 = 10 )
and you enter the if but have no master balls
