### ISSUE TITLE
 Error running loop BotLoop! 

### ISSUE THREAD

**Issue by Zaxin** [jabbink/PokemonGoBot#1009]
**Description:**
[Short description of the issue observed. If this is feature request you can modify the template as required.] Bot stops working. Error running loop BotLoop! Then some long code.

**Steps to reproduce:**

1. Crashes
2. Error code

**Expected behavior:**
Shoulde contine to work as intended?

**Actual behavior:**
Crashes then:

11 aug 23:18:49 [default: BotLoop] - Error running loop BotLoop!
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:148)
	at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
	at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:32)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:145)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:217)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
	at java.lang.Thread.run(Thread.java:745)
11 aug 23:18:49 [default: PokestopLoop] - Looting nearby pokestop 10152f15223c400995e6ad8be9e03f20.16

**Version:**
5.2

**Operating System:**
mac osx 10.11.6

**Java version:**
Latest

Sorry for posting this again, but searched and couldn't find any solution that helped me. What should i do? It sucks that i need to restart terminal every hour or so...

**Comment by Mixone-FinallyHere** [comment]
just after your error log the bot continues
it auto refreshes
the last line it is looting a pokestop if you read it properly

**Comment by Zaxin** [comment]
It actually doesn't, it said its doing it but nothing is happening. Then the error code starts again after maybe 10 seconds. And its the same thing again... and again...

**Comment by Mixone-FinallyHere** [comment]
Then it is the same as all the others please just follow the other issues, this one is repeated all over the place #817

**Comment by Zaxin** [comment]
Yeah, i know. Sadly it doesn't look like anyone have a solution to the problem :( Im a newb when it comes to computer programing and such so i don't really understand much of what is said in the threads. Thanks though!

**Comment by Mixone-FinallyHere** [comment]
Its ok its just that there are almost 800 issues opened (most of them closed now) and a huge majority are just the same thing repeated, the devs are aware don't worry, adding more issues just makes it more difficult to find actual unknown issues

**Comment by Sieberkev** [comment]
Duplicate issue of #817
