### ISSUE TITLE
Error on startup using google login

### ISSUE THREAD

**Issue by KEESSTARR** [jabbink/PokemonGoBot#1012]
**Description:**
[Short description of the issue observed. If this is feature request you can modify the template as required.]  Error on startup using google login.

**Steps to reproduce:**

1. Crashes
2. Error Code

**Expected behavior:**
Should complete login process and start running the bot

**Actual behavior:**
Loads the pokemon logo, tries to login, then crashes

**Stacktrace (If it's a crash):**
Last login: Thu Aug 11 15:25:39 on ttys000
/Users/Keeshon/Desktop/PKMNGO_BOTS/MysticACC/MysticACC.command ; exit;
Keess-Mac-mini:~ Keeshon$ /Users/Keeshon/Desktop/PKMNGO_BOTS/MysticACC/MysticACC.command ; exit;
                                  ,'\
    _.----.        ____         ,'  _\   ___    ___     ____        ;-.               ,
_,-'       `.     |    |  /`.   \,-'    |   \  /   |   |    \  |`.   \ '.           .'/
\      __    \    '-.  | /   `.  ___    |    \/    |   '-.   \ |  |   \  \ .---. .-' /
 \.    \ \   |  __  |  |/    ,','_  `.  |          | __  |    \|  |    '. '     `\_.'
   \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |      |(),()  |     ,
    \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |      (  __   /   .' \
     \    \ |   \_/  |   `-.  \    `'  /|  |    ||   \_/  | |\    |     .''.___.'--,/\_,|
      \    \ \      /       `-.`.___,-' |  |\  /| \      /  | |   |    {  /     \   }   |
       \    \ `.__,'|  |`-._    `|      |__| \/ |  `.__,'|  | |   |     '.\     /_.'    /
        \_.-'       |__|    `-._ |              '-.|     '-.| |   |      |'-.-',  `; _.'
                                `'                            '-._|      |  |  |   |`
                                                                         `""`""`"""`
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 3 more
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:80)
	... 8 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:142)
	... 19 more
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Version:**
0.5.2

**Operating System:**
OS X El Capitan Version 10.11.6

**Java version:**
Java 8?

**Comment by Mixone-FinallyHere** [comment]
#921 
Same error
Check your address bindings
