### ISSUE TITLE
help please!

### ISSUE THREAD

**Issue by addisonrudd** [jabbink/PokemonGoBot#1014]
bot was working fine all day. then this happened. 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 3 more
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:86)
	... 8 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:142)
	... 19 more
addisons-computer:poke addisonrudd$

**Comment by swtrpeter** [comment]
Have u killed java.exe in task manager ? Happened to me earlier and i had 3 instances of java.exe running

**Comment by qwertychacha2002** [comment]
Are you on mac? If so, go to your applications folder and find the utilities folder. Then find activity monitor, click the memory tab and search "java". Click on it. Then click the black stop sign in the top left corner, and choose "Force Quit". Do this to all java process you see. Then you should be all set! Or an Alternative would be starting the bot with `java -jar PokemonGoBot-(enter your bot's version here).jar --spring.main.web-environment=false`if you don't need the web gui.

**Comment by sitruc1234** [comment]
also for mac, try restarting your computer. worked for me!

**Comment by addisonrudd** [comment]
@qwertychacha2002 thanks so much it worked!

**Comment by smileytechguy** [comment]
you can also run the following:
``` bash
pkill -9 java
pkill -15 java
pgrep java # should return nothing
```

**Comment by Mixone-FinallyHere** [comment]
The address is already in use see #546  for more details
