### ISSUE TITLE
unexpected error 403 - IP ban?

### ISSUE THREAD

**Issue by MonSter0610** [jabbink/PokemonGoBot#1024]
**Description:**
Bot stopped working after 5 days of 24/7 running.

**Steps to reproduce:**

1. starting the bot either via ./run.sh or java -jar...
2. bot fails

**Expected behavior:**
bot should run normaly without any problem

**Actual behavior:**
bot has a problem (Got a unexpected http code : 403)

**Stacktrace (If it's a crash):**
login as: root
root@XYZ´s password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Aug 12 06:04:42 2016 from XYZ
root@vps:~# cd /pokemon
root@vps:/pokemon# java -jar PokemonGoBot-0.5.2.jar
                                  ,'\
    _.----.        ____         ,'  _\   ___    ___     ____        ;-.               ,
_,-'       `.     |    |  /`.   \,-'    |   \  /   |   |    \  |`.   \ '.           .'/
\      __    \    '-.  | /   `.  ___    |    \/    |   '-.   \ |  |   \  \ .---. .-' /
 \.    \ \   |  __  |  |/    ,','_  `.  |          | __  |    \|  |    '. '     `\_.'
   \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |      |(),()  |     ,
    \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |      (  __   /   .' \
     \    \ |   \_/  |   `-.  \    `'  /|  |    ||   \_/  | |\    |     .''.___.'--,/\_,|
      \    \ \      /       `-.`.___,-' |  |\  /| \      /  | |   |    {  /     \   }   |
       \    \ `.__,'|  |`-._    `|      |__| \/ |  `.__,'|  | |   |     '.\     /_.'    /
        \_.-'       |__|    `-._ |              '-.|     '-.| |   |      |'-.-',  `; _.'
                                `'                            '-._|      |  |  |   |`
                                                                         `""`""`"""`
12 Aug 06:09:28 [default] - Trying to read /pokemon/config.properties
12 Aug 06:09:28 [default] - Logging in to game server...
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred.
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
        at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:82)
        at com.pokegoapi.api.settings.Settings.<init>(Settings.java:69)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:95)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:180)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:145)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        ... 11 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:197)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
        at java.lang.Thread.run(Thread.java:745)

**Version:**
0.5.2

**Operating System:**
Debian 8

**Java version:**

root@vps:~# java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
root@vps:~#

Additional note:
Account is not banned.
Same "config.properties" is working on my laptop.
"bot-settings" is empty.

**Comment by Sieberkev** [comment]
Looks like you got a (temp) IP ban.

**Comment by staurakis** [comment]
Check `[this issue](https://github.com/jabbink/PokemonGoBot/issues/1023)`

**Comment by muschter** [comment]
It's not a good idea to be running the bot 24/7. It is best that you bot in a normal, human-like fashion, as if you were walking around playing.
