### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by vUrbsex** [jabbink/PokemonGoBot#1046]
**Description:**
I run the bot in terminal on mac. But then this error always comes up

1. I have setup a run command through terminal (cd [where my file is], java -jar [file path])
2.I runned it 
3. then the error occurred

**Expected behavior:**
I thought it would sart to initialize the bot

**Actual behavior:**
But it gives this error

**Stacktrace (If it's a crash):**

http://pastebin.com/SM3mVPV2

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Version:**
0.5.2

**Operating System:**
iMac 2013
NVIDIA GeForce GT 755M 1024 MB

**Java version:**
Java 8 Update 101

**Comment by vUrbsex** [comment]
Could this help?
13 Aug 12:50:24 [main] - Starting MainKt on mymacname.gateway with PID 96977 (/Users/name/Desktop/ThePoGoBot/PoGoBot.jar started by name in /Users/nameDesktop/ThePoGoBot)
13 Aug 12:50:24 [main] - Running with Spring Boot v1.3.6.RELEASE, Spring v4.2.7.RELEASE
13 Aug 12:50:24 [main] - No active profile set, falling back to default profiles: default
13 Aug 12:50:26 [main] - UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
13 Aug 12:50:26 [main] - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
13 Aug 12:50:27 [main] - Application startup failed
java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.Net.bind(Net.java:428)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:142)
	... 19 common frames omitted
13 Aug 12:53:01 [main] - Starting MainKt on Woo-Imac-20.gateway with PID 97170 (/Users/Barney/Desktop/ThePoGoBot/PoGoBot.jar started by Barney in /Users/Barney/Desktop/ThePoGoBot)
13 Aug 12:53:01 [main] - Running with Spring Boot v1.3.6.RELEASE, Spring v4.2.7.RELEASE
13 Aug 12:53:01 [main] - No active profile set, falling back to default profiles: default
13 Aug 12:53:02 [main] - UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
13 Aug 12:53:02 [main] - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
13 Aug 12:53:04 [main] - Application startup failed
java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.Net.bind(Net.java:428)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:142)
	... 19 common frames omitted

**Comment by yashendra2797** [comment]
Please use Pastebin for large outputs.

**Comment by vUrbsex** [comment]
ok

**Comment by vUrbsex** [comment]
Any ideas to whats going on??

**Comment by Peyphour** [comment]
Kill all java process and restart

**Comment by vUrbsex** [comment]
How do i do that??

**Comment by vUrbsex** [comment]
Thank You so much :) 👍
