### ISSUE TITLE
exception in thread 

### ISSUE THREAD

**Issue by addisonrudd** [jabbink/PokemonGoBot#1057]
```
Last login: Sat Aug 13 13:11:57 on ttys000
addisons-computer:~ addisonrudd$ cd /Users/addisonrudd/Desktop/poke 
addisons-computer:poke addisonrudd$ java -jar /Users/addisonrudd/Desktop/poke/PokemonGoBot-0.5.2.jar 
                                  ,'\
    _.----.        ____         ,'  _\   ___    ___     ____        ;-.               ,
_,-'       `.     |    |  /`.   \,-'    |   \  /   |   |    \  |`.   \ '.           .'/
\      __    \    '-.  | /   `.  ___    |    \/    |   '-.   \ |  |   \  \ .---. .-' /
 \.    \ \   |  __  |  |/    ,','_  `.  |          | __  |    \|  |    '. '     `\_.'
   \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |      |(),()  |     ,
    \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |      (  __   /   .' \
     \    \ |   \_/  |   `-.  \    `'  /|  |    ||   \_/  | |\    |     .''.___.'--,/\_,|
      \    \ \      /       `-.`.___,-' |  |\  /| \      /  | |   |    {  /     \   }   |
       \    \ `.__,'|  |`-._    `|      |__| \/ |  `.__,'|  | |   |     '.\     /_.'    /
        \_.-'       |__|    `-._ |              '-.|     '-.| |   |      |'-.-',  `; _.'
                                `'                            '-._|      |  |  |   |`
                                                                         `""`""`"""`
13 Aug 13:15:23 [default] - Trying to read /Users/addisonrudd/Desktop/poke/config.properties
13 Aug 13:15:23 [default] - Set Timer to return the first Pokestop (minutes) setting ("timer_walk_to_start_pokestop") not specified, defaulting to "-1".
13 Aug 13:15:23 [default] - Should the items that are kept be grouped by type (keep best from same type) setting ("group_items_by_type") not specified, defaulting to "false".
13 Aug 13:15:23 [default] - Camp around x lured pokestops setting ("camp_lure_pokestop") not specified, defaulting to "-1".
13 Aug 13:15:23 [default] - Display If Pokemon Was Caught From Lure setting ("display_if_pokemon_from_lure") not specified, defaulting to "true".
13 Aug 13:15:23 [default] - Max distance from starting point the bot should ever go setting ("spawn_radius") is invalid, defaulting to -1: For input string: "unlimited"
13 Aug 13:15:23 [default] - Initial map size (S2 tiles) to fetch setting ("initial_map_size") not specified, defaulting to "9".
13 Aug 13:15:23 [default] - Logging in to game server...
Exception in thread "Async HTTP Thread" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:230)
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:221)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by ansalls** [comment]
Maybe update to the latest config and try again...

**Comment by patzor** [comment]
might want to check your 

java -version

and 

compile the program on your box and run it here are the steps

apt-get install software-properties-common
add-apt-repository ppa:webupd8team/java
apt-get update
apt-get install oracle-java8-installer
git clone https://github.com/jabbink/PokemonGoBot.git && cd PokemonGoBot
./gradlew build
mv config.properties.template config.properties
nano config.properties <<-- put your credentials, configs and save
./gradlew run

**Comment by jabbink** [comment]
Please fix this issue before you can expect help. See the issue template and contribution guidelines.

**Comment by Sieberkev** [comment]
Closing due to lack of more information/inactivity
