### ISSUE TITLE
error: C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic

### ISSUE THREAD

**Issue by japstories** [jabbink/PokemonGoBot#1060]
**Description:**
[09:14:09] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.HumanNavigation.<Move>d__2.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Navigation2.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<NoTeleport>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 355
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 37

**Steps to reproduce:**

1. normal play

**Expected behavior:**
-

**Actual behavior:**
bot trying to re-login

**Stacktrace (If it's a crash):**
-

**Version:**
 PokeMobBot 8.13.2016 - v2.0.0

**Operating System:**
win10

**Java version:**
latest

**Comment by jabbink** [comment]
Shitty bot. Use the one from this repo :P
