### ISSUE TITLE
Stuck after "Pokemon" ASCII

### ISSUE THREAD

**Issue by ArThoX** [jabbink/PokemonGoBot#1084]
Hi

The bot got stuck after "Pokemon" ASCII.

```
Workstation:PokemonGoBot serveurachat$ gradle run
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:createProperties
:classes
:run
                                  ,'\
    _.----.        ____         ,'  _\   ___    ___     ____        ;-.               ,
_,-'       `.     |    |  /`.   \,-'    |   \  /   |   |    \  |`.   \ '.           .'/
\      __    \    '-.  | /   `.  ___    |    \/    |   '-.   \ |  |   \  \ .---. .-' /
 \.    \ \   |  __  |  |/    ,','_  `.  |          | __  |    \|  |    '. '     `\_.'
   \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |      |(),()  |     ,
    \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |      (  __   /   .' \
     \    \ |   \_/  |   `-.  \    `'  /|  |    ||   \_/  | |\    |     .''.___.'--,/\_,|
      \    \ \      /       `-.`.___,-' |  |\  /| \      /  | |   |    {  /     \   }   |
       \    \ `.__,'|  |`-._    `|      |__| \/ |  `.__,'|  | |   |     '.\     /_.'    /
        \_.-'       |__|    `-._ |              '-.|     '-.| |   |      |'-.-',  `; _.'
                                `'                            '-._|      |  |  |   |`
                                                                         `""`""`"""`
> Building 83% > :run
```

PS:
`Your branch is up-to-date with 'origin/develop'.`

**Comment by Sieberkev** [comment]
Please try ./gradlew run (not the default gradle, the bot is shipped with a gradle wrapper)

**Comment by ArThoX** [comment]
@Sieberkev Thanks for the help. However I am getting the same result using the wrapper.

**Comment by ArThoX** [comment]
Additional information. Yesterday it was working. This morning I did  a pull, and it's not working. Thats not sufficient to say it's the code change fault; but it coult.

```
Workstation:PokemonGoBot serveurachat$ git pull
remote: Counting objects: 24, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 24 (delta 3), reused 1 (delta 1), pack-reused 0
Unpacking objects: 100% (24/24), done.
From https://github.com/jabbink/PokemonGoBot
   db5d8e2..d3b6145  develop    -> origin/develop
Updating db5d8e2..d3b6145
Fast-forward
 src/main/kotlin/ink/abb/pogo/scraper/Settings.kt                     | 2 +-
 src/main/kotlin/ink/abb/pogo/scraper/tasks/Walk.kt                   | 2 +-
 src/main/kotlin/ink/abb/pogo/scraper/util/directions/RouteRequest.kt | 3 +++
 3 files changed, 5 insertions(+), 2 deletions(-)

```

**Comment by AlexBoulyga** [comment]
How long did you wait? What Java Version? No error message? What operaring system?

**Comment by ArThoX** [comment]
I waited about 15mins.

```
java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

No error message.

OSX 10.11.5 (15F34)

**Comment by AlexBoulyga** [comment]
No idea about OSX, are you using the .proeprties or the .json? Try a new pull please

**Comment by ArThoX** [comment]
Oh wait, log folder:

```
15 août 10:25:53 [main] - Running with Spring Boot v1.3.6.RELEASE, Spring v4.2.7.RELEASE
15 août 10:25:53 [main] - No active profile set, falling back to default profiles: default
15 août 10:25:54 [main] - UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
15 août 10:25:54 [main] - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
15 août 10:25:56 [main] - Application startup failed
java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:89)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:142)
	... 11 common frames omitted
```

**Comment by ArThoX** [comment]
Shit... simple issue... Let me check ghost running instances...

**Comment by ArThoX** [comment]
That's it, for some reason I had a hidden dead instance still using the address...

Issue: Unable to run the bot

Reason: bot already started and using the address, error visible in /log logs

Fix: kill -9 the old proces

However in this scenario I would have expected the error to be visible through the console :)


Closed

**Comment by AlexBoulyga** [comment]
Yes it usually is, thats why i was confused top :)

**Comment by chongivan** [comment]
try in terminal
killall -9 java
