### ISSUE TITLE
Evolve errors

### ISSUE THREAD

**Issue by zhoushifeng8** [jabbink/PokemonGoBot#1093]
15 八月 22:50:51 [default: ProfileLoop] - Error running loop ProfileLoop!
java.lang.ArithmeticException: / by zero
	at ink.abb.pogo.scraper.tasks.EvolvePokemon.run(EvolvePokemon.kt:32)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:254)
	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:142)
	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:202)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by patzor** [comment]
have u try re-running it? and check the process if the java still running in background before u re-run it

**Comment by zhoushifeng8** [comment]
@patzor yes, java still running

**Comment by patzor** [comment]
kill the process first before re-run

**Comment by zhoushifeng8** [comment]
@patzor ok i try

**Comment by AlexBoulyga** [comment]
Get the latest Version of this bot please. Some evolve errors Werke fixed there

**Comment by zhoushifeng8** [comment]
@AlexBoulyga thank you, i'm using Pokemon Go Bot v0.6.0

**Comment by AlexBoulyga** [comment]
Ah already 0.6.0, did Killing the process help?

**Comment by zhoushifeng8** [comment]
@AlexBoulyga after transfer all the ready to evolve pokemon, now seems ok

**Comment by jabbink** [comment]
Hi @zhoushifeng8,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two weeks (until 2016-08-17 17:41) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by ansalls** [comment]
The profile loop fails 99.999% of the time for me, which causes this error. In ~20 hours the profile loop has correctly executed twice.

**Comment by AlexBoulyga** [comment]
@ansalls try reinstalling the lässt Version of the bot (delete everything including configs and do it again Form scratch). Without any more info i cant help you

**Comment by patzor** [comment]
@ansalls Give it some time.. I receive the same error one of my other bot I try restarting the vps and it worked perfectly after a couple of minutes running..

**Comment by ansalls** [comment]
#1088 ?

**Comment by Sieberkev** [comment]
Original issue fixed with #1157
