### ISSUE TITLE
first run and I get this error (MAC)

### ISSUE THREAD

**Issue by irishguy007** [jabbink/PokemonGoBot#1097]
first run and I get this error (MAC)

5 Aug 17:34:02 [default] - Trying to read /Users/other/Desktop/pokemongobot/config.properties
15 Aug 17:34:02 [default] - config.properties file not found
15 Aug 17:34:02 [default] - Trying to read /Users/other/Desktop/pokemongobot/config.properties.txt
15 Aug 17:34:02 [default] - Logging in to game server...
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:82)
	at com.pokegoapi.api.settings.Settings.<init>(Settings.java:69)
	at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:93)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:212)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:148)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:58)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:47)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:223)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)

help would be greatly appreciated :)

**Comment by AlexBoulyga** [comment]
config.properties file not found
Read the readme -.-

**Comment by jabbink** [comment]
Hi @irishguy007,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-17 18:50) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
Can you log in in the official client?

**Comment by muschter** [comment]
> Caused by: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.

Your issue could be this line that was in your stacktrace.

**Comment by AlexBoulyga** [comment]
15 Aug 17:34:02 [default] - config.properties file not found

Rather that

**Comment by muschter** [comment]
@AlexBoulyga It looks like it read a file called config.properties.txt, though.

**Comment by irishguy007** [comment]
it does look like it started to login and read it

**Comment by irishguy007** [comment]
i haven't filled out this section of the config file: 

base64_password=

# Proxy server and port to be used by the bot. Only HTTP proxy are supported at the moment
proxy_server=
proxy_port=-1
# Proxy type, among SOCKS/HTTP/DIRECT. DIRECT means a direct connection i.e : no proxy
proxy_type=SOCKS
# Proxy authentication
proxy_username=
proxy_password

# Token to login directly
token=

**Comment by muschter** [comment]
If you could post an image of the directory you are trying to run the bot from, that could give us some insight. Also, if regards to the new account statement: If you were IP banned, I would imagine that all accounts associated with that IP address will follow suit, regardless if they are new or not.

**Comment by AlexBoulyga** [comment]
There is a readme here just look for it in the repo, usage.md and readme.md @muschter i got this error a few times with wrong configs

**Comment by AlexBoulyga** [comment]
Java Version? Bot Version? Operating system?

**Comment by irishguy007** [comment]
lets hope I'm not ip banned........  seem to still be able to play on other acc's.     
 os 10.11.5 latest bot java8

**Comment by addisonrudd** [comment]
im having the same problem

**Comment by AlexBoulyga** [comment]
Hmm have you already tried logging in with the official client?

**Comment by irishguy007** [comment]
don't really wanna  try on my device now  just  incase :(

**Comment by irishguy007** [comment]
have a non batted acc id like to keep

**Comment by addisonrudd** [comment]
maybe we should wait 24 hours. It could be the new 24 hour banned. Im not sure how i got banned but whatever.

**Comment by AlexBoulyga** [comment]
Maybe maybe permanent

**Comment by irishguy007** [comment]
not good if its kicking in the second you connect the account

**Comment by irishguy007** [comment]
someone have a new acc to test on theres to see if they get  the same?

**Comment by addisonrudd** [comment]
I do. one sec ill try

**Comment by addisonrudd** [comment]
i got the same error on a new account that was banned. So maybe its a silly problem that we can fix. Or its an ip ban

**Comment by addisonrudd** [comment]
wasnt banned*

**Comment by irishguy007** [comment]
I'm betting must be something  simple

**Comment by addisonrudd** [comment]
thats what im thinking too. lets focus on the other part then just "you account may be banned". it says alot of other stuff to.

**Comment by addisonrudd** [comment]
okay so its not letting me on the normal game on my phone either.

**Comment by irishguy007** [comment]
are you trying with the same acc??

**Comment by addisonrudd** [comment]
yes im trying with my main. It wont even load up. im not sure what it could be..

**Comment by irishguy007** [comment]
the account i was trying to bot was a brand new account , not gonna try it on my device but my iPhone will load up my main acc no issue at the moment

**Comment by addisonrudd** [comment]
okay i got it figured out. short answer is were probably fucked. it looks like a ban. not sure if its permanant or not though but it may be. we will see i guess.

**Comment by irishguy007** [comment]
dam it,,,, looks like its an account ban though.. you have any other accounts that you can login with to confirm?

**Comment by swtrpeter** [comment]
I have this same issue and my account is not banned.. Double checked just to be sure. It is only having with this version. I can run the same account on the latest pre-built version with a few errors but it runs so I know its not an account ban.

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
