### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by daraujofs** [jabbink/PokemonGoBot#1132]
`Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:82)
	at com.pokegoapi.api.settings.Settings.<init>(Settings.java:69)
	at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:93)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:212)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:148)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:58)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:47)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:223)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by AlexBoulyga** [comment]
Read the log, "your account may be banned", test if your account really is banned through the normal APP, and if yes search already opened Tickets With the same probpem

**Comment by jabbink** [comment]
Hi @daraujofs,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-19 07:05) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by dutchsociety** [comment]
My account and from my colleages are also banned from the Pokemon services with the latest Pogo version. Made a new account and it works fine again, had almost all pokemons and was over lvl 34 :(

**Comment by jabbink** [comment]
@dutchsociety see release notes; they started banning based on inhuman behavior.

**Comment by AlexBoulyga** [comment]
Even if you havent botted anymore, they look back on your "behaviour"

**Comment by dutchsociety** [comment]
Yep i know, nothing we can do about it (helaas).

**Comment by daraujofs** [comment]
Hi!
I went into my device and completed the "tutorial". Thereafter, all worked fine.

**Comment by Sieberkev** [comment]
Thanks, I'll add that to the FAQ file :)
