### ISSUE TITLE
Something is not working with my bot

### ISSUE THREAD

**Issue by icyeti** [jabbink/PokemonGoBot#1140]
When I use the pokemon go bot the Profile Loop wont work.

It should run the profile loop but

This happens

17 Aug 08:48:24 [default: ProfileLoop] - Profile update: 541196 XP on LVL 23; 106196/125000 (84.96%) to LVL 24
17 Aug 08:48:24 [default: ProfileLoop] - XP gain: 2,210 XP in 1 mins; XP rate: 132,600/hr; Next level in: 0.14 hr
17 Aug 08:48:24 [default: ProfileLoop] - Pokemon caught/transferred: 11/6; Pokemon caught from lures: 5; Items caught/dropped: 12/5;
17 Aug 08:48:24 [default: ProfileLoop] - Pokebank 167/250; Stardust 76911; Inventory 247/350
17 Aug 08:48:25 [default: ProfileLoop] - Error running loop ProfileLoop!
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:66)
	at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:23)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:254)
	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:138)
	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:202)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
	at java.lang.Thread.run(Thread.java:745)

Bot version PokemonGoBot-0.6.0.jar

I'm on mac 10.11.5

For java I am on 1.8.0_45

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by AlexBoulyga** [comment]
Just restart it, I dont know where this error comes from, however restarting helps (if there is this sentence: Contents of buffer are null)

**Comment by FrancYescO** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/issues/331

Seems just some request are made too fast

**Comment by icyeti** [comment]
I think I restarted it and it's still not working. Maybe I restarted it wrong. Can you tell me how to restart it on a Mac.

**Comment by ansalls** [comment]
It's not you, i've got the same problem. I've restarted, uninstalled and reinstalled, updated java... It still works fine on 5.2 though, so if I need to transfer pkmn I just run that. On a side note, if the calls happen to go through and you have a stack and a bunch of lucky eggs it may burn all your eggs and only evolve a handful of pokemon. Reason is after it's started the stack evolve process, if a loop error occurs and it's below the stack limit it thinks it hasn't hit it yet, then will pop another egg as soon as it hits it, rinse and repeat. So, if you're having this issue shut off the lucky egg!

**Comment by ansalls** [comment]
#1093 
#1120

**Comment by Sieberkev** [comment]
As @FrancYescO said, it's a known issue with the underlaying API to niantic which sends too much data in one time to the servers, and they reply back with a null response.

Jabbink is working on a brand new API to get this mess fixed (see also #1136 which is a bit related).

**Comment by yumao5** [comment]
@icyeti , I am using Mac too. Basic I type run twice. First time login-in always failed. Just ctrl-c to stop it and run again. Should be fine.

**Comment by Sieberkev** [comment]
Please read the [FAQ](https://github.com/jabbink/PokemonGoBot/blob/develop/FAQ.md#i-get-an-invalidprotocolbufferexception-contents-of-buffer-are-null)
