### ISSUE TITLE
Bug - [default: PokestopLoop] - Error running loop PokestopLoop!

### ISSUE THREAD

**Issue by DiogoRNeves** [jabbink/PokemonGoBot#1162]
**Description:**
After the error the bot seems to stop walking.

**Steps to reproduce:**

1. Run the bot

**Expected behavior:**
N/A

**Actual behavior:**
N/A

**Stacktrace (If it's a crash):**
18 Aug 08:09:29 [default: PokestopLoop] - Error running loop PokestopLoop!
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at ink.abb.pogo.scraper.util.directions.RouteRequestKt.getRouteCoordinates(RouteRequest.kt:46)
	at ink.abb.pogo.scraper.util.directions.RouteRequestKt.getRouteCoordinates(RouteRequest.kt:84)
	at ink.abb.pogo.scraper.tasks.Walk.walkRoute(Walk.kt:81)
	at ink.abb.pogo.scraper.tasks.Walk.walk(Walk.kt:70)
	at ink.abb.pogo.scraper.tasks.Walk.run(Walk.kt:63)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:262)
	at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:74)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:262)
	at ink.abb.pogo.scraper.Bot$start$5.invoke(Bot.kt:166)
	at ink.abb.pogo.scraper.Bot$start$5.invoke(Bot.kt:36)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:204)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:36)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Version:**
f9c163e1a481952616b9ef9bb77f694cd2ad15d5

**Operating System:**
Mac OS X

**Java version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
Should be fixed with #1167
