### ISSUE TITLE
Get Awarded Badge Levels

### ISSUE THREAD

**Issue by gise88** [jabbink/PokemonGoBot#1170]
**Description:**
On new level many red lines! :smile: A fix can be put this line: https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/tasks/UpdateProfile.kt#L63 in a try-catch statement

**Stacktrace:**
19 ago 03:02:01 [default: BotLoop] - Missed, waiting for 1.8867693486616957 seconds
19 ago 03:02:01 [default: ProfileLoop] - Error running loop ProfileLoop!
java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Unknown Source)
        at POGOProtos.Networking.Responses.CheckAwardedBadgesResponseOuterClass$CheckAwardedBadgesResponse.getAwardedBadgeLevels(CheckAwardedBadgesResponseOuterClass.java:249)
        at com.pokegoapi.api.player.PlayerProfile.checkAndEquipBadges(PlayerProfile.java:191)
        at ink.abb.pogo.scraper.tasks.UpdateProfile.run(UpdateProfile.kt:63)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:262)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:36)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:204)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:36)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Version:**
https://github.com/jabbink/PokemonGoBot/commit/5dfa2973f9975e9ac0188151ed9ea4903fbd5276

**Operating System:**
Debian 8

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
Should be fixed with #1173
