### ISSUE TITLE
Bot crashing while lauching.

### ISSUE THREAD

**Issue by Pepejson** [jabbink/PokemonGoBot#1186]
**Description:**
Just updated my source via git pull and compiled it. Launched and following error appears.
Note that I'm using old .config file from https://github.com/jabbink/PokemonGoBot/commit/b24584b35971f0fae2afe4fd753d5cde4ab2258f but I'm always doing it that way and the bot warns me that variable in config file is not found and setting that var to default. This time bot is crashing. I don't know if it's config related but I think it could be so that's why I point this.

**Steps to reproduce:**

1. Compile latest develop branch.
2. Run the bot

**Expected behavior:**
Bot should launch normally.

**Actual behavior:**
Bot crashing.

**Stacktrace (If it's a crash):**
```
MacBook-Air-Pepejson:PokemonGoBot Pepejson$ java -jar PokemonGoBot-0.6.0.jar 
                                  ,'\
    _.----.        ____         ,'  _\   ___    ___     ____        ;-.               ,
_,-'       `.     |    |  /`.   \,-'    |   \  /   |   |    \  |`.   \ '.           .'/
\      __    \    '-.  | /   `.  ___    |    \/    |   '-.   \ |  |   \  \ .---. .-' /
 \.    \ \   |  __  |  |/    ,','_  `.  |          | __  |    \|  |    '. '     `\_.'
   \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |      |(),()  |     ,
    \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |      (  __   /   .' \
     \    \ |   \_/  |   `-.  \    `'  /|  |    ||   \_/  | |\    |     .''.___.'--,/\_,|
      \    \ \      /       `-.`.___,-' |  |\  /| \      /  | |   |    {  /     \   }   |
       \    \ `.__,'|  |`-._    `|      |__| \/ |  `.__,'|  | |   |     '.\     /_.'    /
        \_.-'       |__|    `-._ |              '-.|     '-.| |   |      |'-.-',  `; _.'
                                `'                            '-._|      |  |  |   |`
                                                                         `""`""`"""`
Exception in thread "default" com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_FALSE token
 at [Source: /Users/Pepejson/Desktop/Development/PokemonGoBot/./bot-settings/default.json; line: 18, column: 21] (through reference chain: ink.abb.pogo.scraper.Settings["followStreets"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1233)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1121)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1074)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:328)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2731)
	at ink.abb.pogo.scraper.services.BotService.load(BotService.kt:69)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:85)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:67)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Version:**
https://github.com/jabbink/PokemonGoBot/commit/9b98471942f87883be95a1458c09f5cef2961661

**Operating System:**
OS X 10.11

**Java version:**
```
MacBook-Air-Pepejson:PokemonGoBot Pepejson$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

```
Leave this sentence in your issue as proof that you have read and used this template.

**Comment by mineme45** [comment]
Can you remove the "followStreets" line on your "default.json" file?

**Comment by Pepejson** [comment]
Yes, removed it and works.

**Comment by Sieberkev** [comment]
We added it to the FAQ :)
