### ISSUE TITLE
Static login error with suggestion 

### ISSUE THREAD

**Issue by DiogoRNeves** [jabbink/PokemonGoBot#120]
Im using v0.3.0 on a PTC Login.

After a large amount of time (I've had this after an hour or after 2 and a half hours) it starts looping over this:

```
Getting map of (COORDS, COORDS)
D/RequestHandler: Authenticated with static token
Exception in thread "Thread-2114" com.pokegoapi.exceptions.LoginFailedException
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:133)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:238)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:173)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:163)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:96)
	at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:20)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:64)
	at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Bot.kt:54)
	at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Bot.kt:18)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

When I stop and restart the bot it gets on perfectly again, as long as I'm not authenticating with token. So I was thinking if you could get a count of the amount of times this error comes up and then force it to use user/pw login after, idk, 5?

**Comment by jabbink** [comment]
Issue in the Java API, post it here if you want.

github.com/Grover-c13/PokeGOAPI-Java
