### ISSUE TITLE
Error Message upon Launch: IllegalArgumentException: No enum constant POGOProtos.Enums.PokemonIdOuterClass.PokemonId.false

### ISSUE THREAD

**Issue by jacksonash** [jabbink/PokemonGoBot#1205]
**Description:**
[Short description of the issue observed. If this is feature request you can modify the template as required.]

**Steps to reproduce:**
1. Launch Bot
2. Error Pops up

**Expected behavior:**
Bot should run normally

**Actual behavior:**
Error Pops up

**Stacktrace (If it's a crash):**
Exception in thread "default" java.lang.IllegalArgumentException: No enum constant POGOProtos.Enums.PokemonIdOuterClass.PokemonId.false
	at java.lang.Enum.valueOf(Enum.java:238)
	at POGOProtos.Enums.PokemonIdOuterClass$PokemonId.valueOf(PokemonIdOuterClass.java:14)
	at ink.abb.pogo.scraper.SettingsParser.createSettingsFromProperties(Settings.kt:116)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:147)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:58)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:47)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
**Version:**
PokemonGoBot-0.6.0.

**Operating System:**
Mac

**Java version:**
Java 8 Update 101

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment]
Update your follow_street configuration with the improved version (boolean -> array of providers)

**Comment by FrancYescO** [comment]
Wrong Pokémon name in config?

**Comment by jacksonash** [comment]
How does one do that @Sieberkev

**Comment by Sieberkev** [comment]
Did you solve your mysterious pokemon problem?

**Comment by Sieberkev** [comment]
Closed due to inactivity, if you ever come back to this, make sure the pokemon names in your configuration are correct (and don't set `false` as a pokemon name)
