### ISSUE TITLE
Error on startup 

### ISSUE THREAD

**Issue by KEESSTARR** [jabbink/PokemonGoBot#1247]
### Prerequisites (Remove this section if you want)
Make sure you...

* Have checked the FAQ if your question has not been answered there.
* Have searched the existing issues if your question has not been asked here.
* Post a FULL stacktrace and not only a part of it.
* Fill in all the fields correctly, it helps us immensly if we get a complete image of your situation.

**Description:**
I try to launch but then gets an error

**Steps to reproduce:**

1. Launch
2. Error

**Expected behavior:**
Launch, bot runs normally

**Actual behavior:**
Launch, error pops up

**Stacktrace (If it's a crash):**
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 3 more
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:89)
	... 8 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:142)
	... 19 more
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Version:**
0.6.0

**Operating System:**
OSX El Capitan v10.11.6

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by digihax** [comment]
This is covered in the FAQ: Java is running and listening already: kill the java process and try again.

"Address already in use at io.undertow.Undertow.start(Undertow.java:186)"
"Caused by: java.net.BindException: Address already in use"

**Comment by KEESSTARR** [comment]
I thought I had that problem but I have no other bots or, just to be safe no Java programs at all running.

**Comment by Sieberkev** [comment]
Do you have any other programs running on port 8080 or 8001? You can check with netstat in your command line `netstat -plnt | grep ':8080'`
