### ISSUE TITLE
Error received at profile update

### ISSUE THREAD

**Issue by OrionLethe13** [jabbink/PokemonGoBot#1274]
### Prerequisites (Remove this section if you want)
Make sure you...

* Have checked the FAQ if your question has not been answered there.
* Have searched the existing issues if your question has not been asked here.
* Post a FULL stacktrace and not only a part of it.
* Fill in all the fields correctly, it helps us immensly if we get a complete image of your situation.

**Description:**
Error received at profile update

**Steps to reproduce:**

error occurs every time profile update timer is hit

**Expected behavior:**
Profile details should be provided

**Actual behavior:**
Error above, profile is not provided

**Stacktrace (If it's a crash):**
02 Sep 14:00:34 [default: ProfileLoop] - Error running loop ProfileLoop!
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.player.PlayerProfile.checkAndEquipBadges(PlayerProfile.java:166)
	at ink.abb.pogo.scraper.tasks.UpdateProfile.run(UpdateProfile.kt:63)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:254)
	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:137)
	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:202)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
	at java.lang.Thread.run(Thread.java:745)

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]

**Operating System:**
Mac OS X

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by EpicAwesomeWolf** [comment]
Do you not know how to use a search bar? #1107 search before posting. @Sieberkev @jabbink requesting close.
