### ISSUE TITLE
Error running loop BotLoop!

### ISSUE THREAD

**Issue by muzicvn** [jabbink/PokemonGoBot#1285]
### Prerequisites (Remove this section if you want)

Make sure you...
- Have checked the FAQ if your question has not been answered there.
- Have searched the existing issues if your question has not been asked here.
- Post a FULL stacktrace and not only a part of it.
- Fill in all the fields correctly, it helps us immensly if we get a complete image of your situation.

**Description:**
10 Sep 19:20:38 [default: BotLoop] - No Pokeballs in your inventory; blacklisting Pokemon
10 Sep 19:20:38 [default: BotLoop] - Error running loop BotLoop!
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at ink.abb.pogo.scraper.tasks.ReleasePokemon.run(ReleasePokemon.kt:78)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:285)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:178)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:40)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:224)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:40)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Steps to reproduce:**
1. [Step 1]
2. [Step 2]

**Version:**
0.6.0

**Operating System:**
Mac OS 10.11.6

**Java version:**
1.8

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by EpicAwesomeWolf** [comment]
@muzicvn Check before posting. #1009. @jabbink @Sieberkev requesting close.

**Comment by Sieberkev** [comment]
Please update to the most recent version, it uses a brand new underlaying API which should resolve this type of error.
