### ISSUE TITLE
Error on startup 

### ISSUE THREAD

**Issue by KEESSTARR** [jabbink/PokemonGoBot#1290]
### Prerequisites (Remove this section if you want)

Make sure you...
- Have checked the FAQ if your question has not been answered there.
- Have searched the existing issues if your question has not been asked here.
- Post a FULL stack trace and not only a part of it.
- Fill in all the fields correctly, it helps us immensely if we get a complete image of your situation.

**Description:**
Error upon startup

**Steps to reproduce:**
1. Run Bot
2. Error appears 

**Expected behavior:**
I start running it and then it should run normally 

**Actual behavior:**
I start it and then the error appears

**Stacktrace (If it's a crash):**
Last login: Tue Sep 13 18:54:02 on ttys000
/Users/*****_/Desktop/PKMNGO_BOTS/MysticACC/MysticACC.command ; exit;
Keess-Mac-mini:~ Keeshon$ /Users/**_***/Desktop/PKMNGO_BOTS/MysticACC/MysticACC.command ; exit;
                                  ,'\
    _.----.        ____         ,'  _\   ___    ___     ____        ;-.               ,
_,-'       `.     |    |  /`.   \,-'    |   \  /   |   |    \  |`.   \ '.           .'/
\      __    \    '-.  | /   `.  ___    |    \/    |   '-.   \ |  |   \  \ .---. .-' /
 \.    \ \   |  __  |  |/    ,','_`.  |          | __  |    |  |    '. '     `\_.'
   \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |      |(),()  |     ,
    \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |      (  __   /   .' \
     \    \ |   _/  |   `-.  \`'  /|  |    ||   _/  | |\    |     .''.**_.'--,/\_,|
      \    \ \      /       `-.`._**,-' |  |\  /| \      /  | |   |    {  /     \   }   |
       \    \ `.__,'|  |`-._    `|      |__| \/ |`.**,'|  | |   |     '.\     /_.'    /
        \_.-'       |**|    `-._ |              '-.|     '-.| |   |      |'-.-',`; _.'
                                `'                            '-._|      |  |  |   |`
`""`""`"""`
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
    ... 3 more
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
    at io.undertow.Undertow.start(Undertow.java:186)
    at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
    at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
    at ink.abb.pogo.scraper.MainKt.main(Main.kt:89)
    ... 8 more
Caused by: java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:433)
    at sun.nio.ch.Net.bind(Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
    at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
    at io.undertow.Undertow.start(Undertow.java:142)
    ... 19 more
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Version:**
0.6.0

**Operating System:**
OSX El Capitan 10.11.6

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by borraz** [comment]
Check if you have any process running on port 8080.
I have that problem and was tomcat running on that port.

**Comment by MacDogg** [comment]
BindException: Address already in use
FAQ has some fixes for this.  But like borraz says, it's a port in use issue.  Change you port to something else or disable whatever is on 8080.

**Comment by EpicAwesomeWolf** [comment]
@KEESSTARR look's like you have posted before about the same topic. Please, don't post if it's not important. #1247

**Comment by digihax** [comment]
Either a) You picked an unused/available port, or kept the default port, have launched the bot, closed it, and are trying to open it again.  Java is still running, and bound to that port you previously specified or used, and that's causing the error.  FIX: Kill java.  I gave you terminal commands to do so in prior post you created on this.

b) OR you have a different process that's using that selected port, and when you launch the bot, it conflicts with the pre-existing app/service that's already chosen that port.  FIX: Select a different port, and keep trying until you find one that's open.  Try starting at 17000 and incrementing by one.  Or, google how to find open ports on your mac, and use one of those.  Also, google to find out what processes have which ports open on your mac.  That can help you also.  Change the config file/json file as appropriate, and use your new skills from googling to confirm the ports being used are what's expected.

Either way, this is not a CODE issue, this is an issue with YOUR SYSTEM.
