### ISSUE TITLE
I am getting this error. Tried looking for similar posts but failed. Complete noob with this stuff. Please help

### ISSUE THREAD

**Issue by jpvgm5** [jabbink/PokemonGoBot#1294]
17 Sep 17:09:50 [main] - Starting MainKt on Llamadro-PC with PID 1712 (C:\Users\Llamadro\Desktop\PoGo\bot.jar started by Llamadro in C:\Users\Llamadro\Desktop\PoGo)
17 Sep 17:09:51 [main] - Running with Spring Boot v1.3.6.RELEASE, Spring v4.2.7.RELEASE
17 Sep 17:09:51 [main] - No active profile set, falling back to default profiles: default
17 Sep 17:10:15 [main] - UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
17 Sep 17:10:15 [main] - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
17 Sep 17:10:22 [main] - Application startup failed
java.lang.RuntimeException: java.net.BindException: Address already in use: bind
    at io.undertow.Undertow.start(Undertow.java:186)
    at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
    at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
    at ink.abb.pogo.scraper.MainKt.main(Main.kt:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.net.BindException: Address already in use: bind
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
    at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
    at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
    at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
    at io.undertow.Undertow.start(Undertow.java:142)
    ... 19 common frames omitted

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Creepster** [comment]
I'm noob at stuff like that too, but there are a couple of lines near the beginning

`17 Sep 17:10:22 [main] - Application startup failed
java.lang.RuntimeException: java.net.BindException: Address already in use`

and it literally says that startup failed because address is already in use.

**Comment by jpvgm5** [comment]
How do i fix it, Creepster? :(

**Comment by Creepster** [comment]
Go to ["FaQ"](https://github.com/jabbink/PokemonGoBot/blob/develop/FAQ.md) and search for "Address already in use" (second from the end).

I hope you'll get your answer there.

**Comment by digihax** [comment]
Look in your config file.  What port is it using?  8001?  8080?  is something else using that port?  Kill it/change ports.  That's what has to happen.  Set it to a different port, like 7999 and see if it starts up ok.  See if java is already running in processes, and kill it, and restart it.  few approaches you can take to fix.
