### ISSUE TITLE
What's wrong with login?

### ISSUE THREAD

**Issue by zhoushifeng8** [jabbink/PokemonGoBot#1307]
[PTC] Logging back in!
Exception in thread "bot" ink.abb.pogo.api.exceptions.LoginFailedException: Failed to fetch token, body: error=invalid_request
	at ink.abb.pogo.api.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:244)
	at ink.abb.pogo.api.PoGoApiImpl.start(PoGoApiImpl.kt:83)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:165)
	at ink.abb.pogo.scraper.services.BotService.submitBot(BotService.kt:42)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:85)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:67)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by jabbink** [comment]
Hi @zhoushifeng8,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-11-14 10:15) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by jaacks** [comment]
PTC or Google?

**Comment by zhoushifeng8** [comment]
@jaacks google, how to set to google account? I replace PTC with google following errors come out

                                                                         `""`""`"""`
Exception in thread "bot" com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 start byte 0x80
 at [Source: /Users/zhoushifeng/Desktop/pokemon go/./bot-settings/bot.json; line: 8, column: 16]
 at [Source: /Users/zhoushifeng/Desktop/pokemon go/./bot-settings/bot.json; line: 8, column: 5] (through reference chain: ink.abb.pogo.scraper.Settings["credentials"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:379)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:339)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:513)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2731)
	at ink.abb.pogo.scraper.services.BotService.load(BotService.kt:69)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:85)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:67)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 start byte 0x80
 at [Source: /Users/zhoushifeng/Desktop/pokemon go/./bot-settings/bot.json; line: 8, column: 16]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidInitial(UTF8StreamJsonParser.java:3542)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeCharForError(UTF8StreamJsonParser.java:3288)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3520)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2683)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:832)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:79)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:488)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	... 10 more

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
