### ISSUE TITLE
Google account login setup

### ISSUE THREAD

**Issue by zhoushifeng8** [jabbink/PokemonGoBot#1316]
**Description:**
How google account set bot.json file? If i replace ptc with Google, google-auto both cannot work, errors popup

**Steps to reproduce:**

**Expected behavior:**
[What should happen?]

**Actual behavior:**
Exception in thread "bot" com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 start byte 0x80
 at [Source: /Users/zhoushifeng/Desktop/pokemon go/./bot-settings/bot.json; line: 8, column: 16]
 at [Source: /Users/zhoushifeng/Desktop/pokemon go/./bot-settings/bot.json; line: 8, column: 5] (through reference chain: ink.abb.pogo.scraper.Settings["credentials"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:379)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:339)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1589)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:513)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2731)
	at ink.abb.pogo.scraper.services.BotService.load(BotService.kt:69)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:85)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:67)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 start byte 0x80
 at [Source: /Users/zhoushifeng/Desktop/pokemon go/./bot-settings/bot.json; line: 8, column: 16]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidInitial(UTF8StreamJsonParser.java:3542)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._decodeCharForError(UTF8StreamJsonParser.java:3288)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3520)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2683)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:832)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:79)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:488)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
	... 10 more

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
0.7.4
**Operating System:**
MAC

**Java version:**
8

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by jaacks** [comment]
Try latest version.

**Comment by zhoushifeng8** [comment]
@jaacks thank you for your reply, ilatest version still same, if I change ptc to google, the error popup

**Comment by jabbink** [comment]
The error is pretty descriptive:

> Invalid UTF-8 start byte 0x80

Can you paste line 7-9 of your config?

**Comment by zhoushifeng8** [comment]
@jabbink 

all default config, just change ptc to google. 

{
  "latitude" : 0,
  "longitude" : 0,
  "saveLocationOnShutdown" : true,
  "savedLatitude" : 0,
  "savedLongitude" : 0,
  "credentials" : {
    "type" : “google”,
    "username" : "",
    "password" : ""
  },
  "proxyServer" : "",
  "proxyPort" : "-1",
  "proxyType" : "SOCKS",
  "proxyUsername" : "",
  "proxyPassword" : "",
  "restApiPassword" : "",
  "speed" : 2.8,
  "randomSpeedRange" : 0.0,
  "followStreets" : [],
  "mapzenApiKey" : "",
  "googleApiKey" : "",
  "groupItemsByType" : false,
  "dropItems" : true,
  "itemDropDelay" : -1,
  "uselessItems" : {
    "ITEM_REVIVE" : 20,
    "ITEM_MAX_REVIVE" : 10,
    "ITEM_POTION" : 0,
    "ITEM_SUPER_POTION" : 30,
    "ITEM_HYPER_POTION" : 50,
    "ITEM_MAX_POTION" : 50,
    "ITEM_POKE_BALL" : 40,
    "ITEM_GREAT_BALL" : 50,
    "ITEM_ULTRA_BALL" : 50,
    "ITEM_MASTER_BALL" : 10,
    "ITEM_RAZZ_BERRY" : 40,
    "ITEM_LUCKY_EGG" : -1,
    "ITEM_INCENSE_ORDINARY" : -1,
    "ITEM_TROY_DISK" : -1
  },
  "profileUpdateTimer" : 60,
  "timerWalkToStartPokestop" : -1,
  "randomNextPokestopSelection" : 5,
  "campLurePokestop" : -1,
  "desiredCatchProbability" : 0.4,
  "desiredCatchProbabilityUnwanted" : 0.0,
  "autotransfer" : true,
  "autotransferTimeDelay" : -1,
  "randomBallThrows" : false,
  "waitBetweenThrows" : false,
  "keepPokemonAmount" : 1,
  "maxPokemonAmount" : -1,
  "displayKeepalive" : true,
  "displayPokestopName" : false,
  "displayPokestopRewards" : true,
  "displayPokemonCatchRewards" : true,
  "displayIfPokemonFromLure" : true,
  "lootPokestop" : true,
  "catchPokemon" : true,
  "autoFillIncubator" : true,
  "sortByIv" : false,
  "desiredCurveRate" : 0.0,
  "neverUseBerries" : true,
  "allowLeaveStartArea" : false,
  "spawnRadius" : -1,
  "banSpinCount" : 0,
  "transferCpThreshold" : 400,
  "transferCpMinThreshold" : -1,
  "transferIvThreshold" : 80,
  "ignoredPokemon" : [ "EEVEE", "MEWTWO", "CHARMANDER" ],
  "obligatoryTransfer" : [ "DODUO", "RATTATA", "CATERPIE", "PIDGEY" ],
  "evolveBeforeTransfer" : [ "CATERPIE", "RATTATA", "WEEDLE", "PIDGEY" ],
  "neverCatchPokemon" : [],
  "evolveStackLimit" : 100,
  "useLuckyEgg" : 1,
  "evolveTimeDelay" : 300,
  "export" : "",
  "guiPortSocket" : 8001,
  "initialMapSize" : 9,
  "waitChance" : 0.0,
  "waitTimeMin" : 0,
  "waitTimeMax" : 0,
  "botTimeoutAfterMinutes" : -1,
  "botTimeoutAfterCatchingPokemon" : -1,
  "botTimeoutAfterVisitingPokestops" : -1,
  "buddyPokemon" : ""
}

**Comment by Cypherke** [comment]
"proxyPort" : -1, not "proxyPort" : "-1",

**Comment by zhoushifeng8** [comment]
@Cypherke Thank you, I changed, same error pop out...

**Comment by Cypherke** [comment]
copy and paste your json file to jsonlint.com and try to validate... What program are you using to edit the json file?

**Comment by zhoushifeng8** [comment]
@Cypherke i using mac system text to edit

**Comment by zhoushifeng8** [comment]
@Cypherke 

Error: Parse error on line 8:
...tials": {		"type": “google”,		"usernam
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

**Comment by zhoushifeng8** [comment]
@Cypherke @jabbink Thank you I know what happen already, becase " ” this 2 differnet.

**Comment by jabbink** [comment]
line 8. your " is not an actual `"`. looks like os x text mate or sth. remove those cursive " characters and insert normal "'s

**Comment by zhoushifeng8** [comment]
@jabbink thank you
