### ISSUE TITLE
IN_COOLDOWN_PERIOD after spesific error

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#132]
`Profile update : 642240 XP on LVL 24; 207240/275000 (75.36%) to LVL 25
Getting map of (40.78136304646817, -73.97165380274542)
Exception in thread "Thread-51" com.pokegoapi.exceptions.RemoteServerException: java.net.SocketTimeoutException: timeout
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:156)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:238)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:173)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:163)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:96)
	at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:20)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:64)
	at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Bot.kt:54)
	at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Bot.kt:18)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:210)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:111)
	... 10 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
	... 31 more
Getting map of (40.781376545256485, -73.97168540279743)
Looting nearby pokestop b0841dcb5877411384510a81934c670e.16
IN_COOLDOWN_PERIOD
Walking to (40.781391, -73.97167900000001) in 0.8945861721750432 steps.
Destination reached.
Profile update : 642240 XP on LVL 24; 207240/275000 (75.36%) to LVL 25
Getting map of (40.78142735508258, -73.97165072150952)
Getting map of (40.78142833903779, -73.97169505444025)
Looting nearby pokestop b0841dcb5877411384510a81934c670e.16
IN_COOLDOWN_PERIOD
Walking to (40.781391, -73.97167900000001) in 0.105413828802525 steps.
Destination reached.
Profile update : 642240 XP on LVL 24; 207240/275000 (75.36%) to LVL 25
Getting map of (40.78137530593603, -73.97164461444001)
Looting nearby pokestop b0841dcb5877411384510a81934c670e.16
IN_COOLDOWN_PERIOD
Getting map of (40.78138206549581, -73.97165421347829)
Walking to (40.781391, -73.97167900000001) in 0.8945861663140218 steps.
Destination reached.
Profile update : 642240 XP on LVL 24; 207240/275000 (75.36%) to LVL 25
Looting nearby pokestop b0841dcb5877411384510a81934c670e.16
IN_COOLDOWN_PERIOD
Getting map of (40.78140477950877, -73.97171360481988)
Walking to (40.781391, -73.97167900000001) in 0.10541383622633364 steps.
Destination reached.
Profile update : 642240 XP on LVL 24; 207240/275000 (75.36%) to LVL 25
Getting map of (40.78138820581506, -73.9716499897288)
Looting nearby pokestop b0841dcb5877411384510a81934c670e.16
IN_COOLDOWN_PERIOD
Walking to (40.781391, -73.97167900000001) in 0.8945861575340981 steps.
Destination reached.
Profile update : 642240 XP on LVL 24; 207240/275000 (75.36%) to LVL 25
Getting map of (40.781402433080316, -73.97172926372701)
Looting nearby pokestop b0841dcb5877411384510a81934c670e.16
IN_COOLDOWN_PERIOD
Looting nearby pokestop b0841dcb5877411384510a81934c670e.16`

**Comment by jabbink** [comment]
Fix incoming
