### ISSUE TITLE
run a few hours then get this error message then after that not catch any pokemon

### ISSUE THREAD

**Issue by zhoushifeng8** [jabbink/PokemonGoBot#1324]
run a few hours then get this error message then after that not catch any pokemon
**Description:**
Exception in thread "RxComputationScheduler-4" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: Invalid Auth status code received, token not refreshed?
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
	at rx.internal.operators.OnSubscribeTimerOnce$1.call(OnSubscribeTimerOnce.java:49)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:186)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: ink.abb.pogo.api.exceptions.LoginFailedException: Invalid Auth status code received, token not refreshed?
	at ink.abb.pogo.api.network.ActionQueue.sendRequests(ActionQueue.kt:161)
	at ink.abb.pogo.api.network.ActionQueue.access$sendRequests(ActionQueue.kt:26)
	at ink.abb.pogo.api.network.ActionQueue$1$1.invoke(ActionQueue.kt:75)
	at ink.abb.pogo.api.network.ActionQueue$1$1.call(ActionQueue.kt:26)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	... 10 more

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
1.0.1
**Operating System:**
MAC

**Java version:**
latest
Leave this sentence in your issue as proof that you have read and used this template.

**Comment by jabbink** [comment]
yeah happens after exactly 150 minutes
