### ISSUE TITLE
bot not starting "Exception in Thread default"

### ISSUE THREAD

**Issue by mSmithe** [jabbink/PokemonGoBot#1329]
Description:
bot doesn't surpasses the logging in stage

Steps to reproduce:
Exception in thread "default" ink.abb.pogo.api.exceptions.LoginFailedException: Failed to fetch token, body: error=invalid_request
        at ink.abb.pogo.api.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:246)
        at ink.abb.pogo.api.PoGoApiImpl.start(PoGoApiImpl.kt:82)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:174)
        at ink.abb.pogo.scraper.services.BotService.submitBot(BotService.kt:37)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:84)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:66)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

Expected behavior:
accually starts without problems

Actual behavior:
nothing.

Stacktrace (If it's a crash):
[Please use pastebin if it's too long]

Version:
1.0.1

Operating System:
Windows 10

Java version:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by nikhilgoswami** [comment]
If you are using Google or Facebook account in place of username use your email id it might work!
