### ISSUE TITLE
Bot doing fine, getting this error everytime

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#1333]
**Description:**
Fine with bottin but this error keeps comming.

**Steps to reproduce:**

1. Open bot, login
2. after 1-2 entries, starts to give this error

**Expected behavior:**
Shouldn't be giving error

**Actual behavior:**
Gives error

**Stacktrace (If it's a crash):**

```
30 Ara 18:35:12 [default: BotLoop] - Error running loop BotLoop!
java.lang.NullPointerException
	at ink.abb.pogo.scraper.tasks.ReleasePokemon.run(ReleasePokemon.kt:47)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:265)
	at ink.abb.pogo.scraper.Bot$start$7.invoke(Bot.kt:159)
	at ink.abb.pogo.scraper.Bot$start$7.invoke(Bot.kt:37)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:205)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:37)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Version:**
v1.0.1

**Operating System:**
macOS Sierra 10.12.2

**Java version:**
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by jabbink** [comment]
Hi @CptJackieSparrow,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2017-01-01 17:45) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by avelis** [comment]
@CptJackieSparrow I am actually seeing this error as well. Same OS version, same compiled jar version, & Java `1.8.0_31`. I also compiled the latest from the cloned source (`8e1aea16c8e32238ade9e27d1e228d89a6e4d42a`) and still got the same stacktrace error.

It would appear that there is a logic check to determine if the bot should release Pokemon from your Pokemon bank. Somewhere in the source it's getting a NullPointerException referencing something that does not exist to determine Pokemon release status. Therefore, the bot will continue to catch Pokemon fine but never release any to curate your Pokemon bank according to your preferences.

@jabbink Not sure what else the ticket needs to complete the issue's information but I can do my best to happily provide it. I have read the issue template but do you requre better behavioral expectations written out?

**Comment by jabbink** [comment]
![image](https://cloud.githubusercontent.com/assets/2461972/23261026/db22bdce-f9d4-11e6-9685-18e755c80d0c.png)

The missing info was already added.

**Comment by avelis** [comment]
@jabbink My bad. I need put on my reading glasses apparently.

Also, I wanted to say thanks for creating this project and hosting it on Github. I know it's a bot in all but still.
