### ISSUE TITLE
Exception in thread "default"

### ISSUE THREAD

**Issue by unskilledsniper438** [jabbink/PokemonGoBot#1334]
**Description:**
cant login

**Stacktrace (If it's a crash):**
Exception in thread "default" ink.abb.pogo.api.exceptions.RemoteServerException: Failed to receive contents from server
        at ink.abb.pogo.api.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:148)
        at ink.abb.pogo.api.PoGoApiImpl.start(PoGoApiImpl.kt:82)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:174)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:116)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:79)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:66)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.net.ConnectException: Failed to connect to /116.231.165.246:8080
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189)
        at okhttp3.internal.connection.RealConnection.buildTunneledConnection(RealConnection.java:154)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:111)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at ink.abb.pogo.api.auth.PtcCredentialProvider$2.intercept(PtcCredentialProvider.java:106)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
        at okhttp3.RealCall.execute(RealCall.java:60)
        at ink.abb.pogo.api.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:146)
        ... 6 more

**Version:**
1.0.1

**Operating System:**
windows 10

**Java version:**
[Full output of `java -version`]

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by ralequi** [comment]
Is this bot still alive? @jabbink

**Comment by jabbink** [comment]
Currently not. Also yesterday there was once again a forced update and currently no bot works

**Comment by mSmithe** [comment]
any chance this bot will work ever again ? @jabbink
