### ISSUE TITLE
when getting profile data from pogo server

### ISSUE THREAD

**Issue by nikhilgoswami** [jabbink/PokemonGoBot#1345]
**Description:** 
Even after stacktrace it trys to get profile data doesn't stop completely.
**Stacktrace (it's a crash not sure):**
Logged in with token TGT-2726766-EXDU7g6EpTWW3lAbXXssxuJ7engkMlWSEEWlll7hueYZG3lCKG-sso.pokemon.com and expiry 1561406517635
24 Jun 22:31:58 [default] - Logged in successfully
Getting profile data from pogo server.................Exception in thread "RxComputationScheduler-1" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: rx.exceptions.OnErrorNotImplementedException: Got a unexpected http code: 404
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
	at rx.internal.operators.OnSubscribeTimerOnce$1.call(OnSubscribeTimerOnce.java:49)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:186)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: ink.abb.pogo.api.exceptions.RemoteServerException: Got a unexpected http code: 404

**Version** 
built from source
**Operating System**  
Ubuntu
**Java version:**
openjdk version "1.8.0_212"

**Comment by jabbink** [comment]
Hi @nikhilgoswami,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2019-06-26 19:10) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.

**Comment by nikhilgoswami** [comment]
07 Jul 15:34:41 [default] - Trying to read /media/nick/Storage/pokemonBot/config.properties
07 Jul 15:34:41 [default] - Saved start Latitude setting ("saved_latitude") is invalid, defaulting to 0.0: empty String
07 Jul 15:34:41 [default] - Saved start Longitude setting ("saved_longitude") is invalid, defaulting to 0.0: empty String
07 Jul 15:34:41 [default] - Logging in to game server...
[PTC] Logging back in!
5Logged in with token TGT-6026900-iAXWduIbRgmJMCgfxVvLroxILIVk59mEVlNK0kCqxRNcojBTh5-sso.pokemon.com and expiry 1562504686472
07 Jul 15:34:46 [default] - Logged in successfully
Getting profile data from pogo server..Exception in thread "RxComputationScheduler-1" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: rx.exceptions.OnErrorNotImplementedException: Got a unexpected http code : 404
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
	at rx.internal.operators.OnSubscribeTimerOnce$1.call(OnSubscribeTimerOnce.java:49)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:186)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: ink.abb.pogo.api.exceptions.RemoteServerException: Got a unexpected http code : 404
	at ink.abb.pogo.api.network.ActionQueue.sendRequests(ActionQueue.kt:141)
	at ink.abb.pogo.api.network.ActionQueue.access$sendRequests(ActionQueue.kt:26)
	at ink.abb.pogo.api.network.ActionQueue$1$1.invoke(ActionQueue.kt:75)
	at ink.abb.pogo.api.network.ActionQueue$1$1.call(ActionQueue.kt:26)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	... 10 more
..........................................................................

**Comment by jabbink** [comment]
This bot hasn't been updated in years and is defunct.
