### ISSUE TITLE
com.pokegoapi.exceptions.LoginFailedException in v0.3.0

### ISSUE THREAD

**Issue by Tjessx** [jabbink/PokemonGoBot#143]
Using version 0.3.0
`Exception in thread "Thread-859" com.pokegoapi.exceptions.LoginFailedException
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:133)
        at com.pokegoapi.api.map.pokemon.CatchablePokemon.encounterPokemon(CatchablePokemon.java:111)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:48)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:64)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Bot.kt:54)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Bot.kt:18)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)`

And after this error, the map also failed to load with this error: 
`Getting map of (50.93257637020533, 5.340960568078479)
Exception in thread "Thread-860" com.pokegoapi.exceptions.LoginFailedException
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:133)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:238)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:173)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:163)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:96)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:20)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:64)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Bot.kt:54)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Bot.kt:18)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)`

**Comment by ToMeRhh** [comment]
Did this happen after a while, or right on the start?
if it took it a while to happen, then this is an API related problem, not a problem with this bot.
If you'd like, you should check out the API repo for more info.
if the bot started that way, you should check your login details.

**Comment by Tjessx** [comment]
After a while, I'll post this issue there

**Comment by jabbink** [comment]
1. Google login, most likely.
2. Known problem.
3. Has been reported dozens of times already

**Comment by jabbink** [comment]
When this is merged it should be fixed https://github.com/Grover-c13/PokeGOAPI-Java/pull/165

**Comment by jabbink** [comment]
Still broken, see #165
