### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by jst94** [jabbink/PokemonGoBot#16]
Exception in thread "main" java.lang.NullPointerException
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:93)

When using java -jar

**Comment by jabbink** [comment]
Did you do the thing with the config file as instructed?

**Comment by CptJackieSparrow** [comment]
I have the exactly same problem which i write down under reddit post.
It works fine for 15-16 threads, then this thing starts to occure.

**Comment by jabbink** [comment]
Is it literally the same error (error contains "readJavaFormatString") or is more like the error of #13?

**Comment by CptJackieSparrow** [comment]
I'll have a look.

**Comment by jst94** [comment]
Yeah my config file is good as it seems

**Comment by jabbink** [comment]
Is your config file located next to the `.jar` and can you paste the contents of your `config.properties`?

**Comment by CptJackieSparrow** [comment]
Yeah they are next to each other
# PTC Login credentials
username=[My Username]
password=[My Password]
latitude=40.763704
longitude=-73.973522
prefered_ball=ITEM_POKE_BALL

**Comment by jst94** [comment]
Works now.
Used another text editor to make the properties.
Now getting this:
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException
	at com.pokegoapi.auth.PTCLogin.login(PTCLogin.java:169)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:89)

**Comment by jabbink** [comment]
@CptJackieSparrow seems like it should work for you and you did not get the same error as @jst94; just keep on botting :+1:

@jst94 your username/password are not correct for pokemon.com

**Comment by jst94** [comment]
@jabbink  Yeah they work :( just checked on the website

**Comment by CptJackieSparrow** [comment]
Thank you for your cooperation mate!
Well i can't continue botting as I'm having another error eachtime i open the bot :D
Now it turned Main.kt:189, Main.kt:118 errors.

**Comment by tomtobac** [comment]
Exception in thread "Thread-192" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:104)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:170)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:147)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:93)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt:124)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

I will let this here. It crashed but keep working.
Awesome bot, the best I found, really! :+1:

**Comment by jabbink** [comment]
That's a bug related to the Java API not being compatible in a multithreaded setting. Shouldn't make the app crash and it should just continue working afterwards. Also the original issue is related to having an incorrect config.properties file, so I'll close this.
