### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by jst94** [jabbink/PokemonGoBot#25]
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException
	at com.pokegoapi.auth.PTCLogin.login(PTCLogin.java:169)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:115)

I checked at the website it works.. even changed my password to something simple and it still gives that error message.

Mac osx

**Comment by jabbink** [comment]
Immediately, or after a few minutes?

**Comment by jst94** [comment]
Immediately

**Comment by jst94** [comment]
Works fine on Windows.
