### ISSUE TITLE
Not Working On Mac OSX, getting this error

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#27]
Exception in thread "main" java.lang.UnsupportedClassVersionError: POGOProtos/Inventory/ItemIdOuterClass$ItemId : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at ink.abb.pogo.scraper.MainKt.<clinit>(Main.kt:43)

**Comment by jabbink** [comment]
What is the output of `java -version`?

**Comment by julienkessels** [comment]
working here, osx

**Comment by CptJackieSparrow** [comment]
just downloaded the latest let me check

**Comment by CptJackieSparrow** [comment]
it's 1.6.0_65

**Comment by CptJackieSparrow** [comment]
can you tell me your java version @julienkessels ?
and here's what i'm doing:
1-)Placed pogo.scarper-all-0.2.0.jar on Desktop
2-)config file ready
3-)terminal "java -jar pogo.scarper-all-0.2.0.jar"
4-)boom, error

**Comment by jabbink** [comment]
>output of java -version 1.6.0_65

That means Java 6 Update 65

Not Java 8 Update 101.

Minimum dependency is Java 7

**Comment by CptJackieSparrow** [comment]
TY <3
