### ISSUE TITLE
[bug]Pokemon hatch log

### ISSUE THREAD

**Issue by Emuuung** [jabbink/PokemonGoBot#276]
Every time a pokemon hatches from egg I get this log:
```log
Exception in thread "Thread-66" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.getExperienceAwarded(GetHatchedEggsResponseOuterClass.java:292)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:77)
        at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:38)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:97)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:91)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:28)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```
There doesn't seem to be a problem cause the bot puts another egg in uncubator afterwards:

`(time and date): Put egg -xxxxxxxxxxxxxxxxxxx in unused incubator`

So I think it's just the log that needs to be fixed.

Edit: I just noticed the TODO in the [HatchEggs.kt](PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/tasks/HatchEggs.kt) file.

**Comment by jabbink** [comment]
Compiled from source or jar?

If from source, this is invalid, as it should be fixed upstream very soon. In the pre compiled jar this should be fixed already.

**Comment by Emuuung** [comment]
I compiled it from source. Now I'm getting:
`(date and time): Failed to put egg in incubator; error: ERROR_POKEMON_ID_NOT_EGG`
^Over and over again, maybe I don't have an egg to put in incubator? not sure, can't confirm.

**Comment by jabbink** [comment]
Yeah, known issue in the Java API.

edit `lib/PokeGOAPI-Java/src/resources/protobuf/src/POGOProtos/Networking/Responses/GetHatchedEggsResponse.proto`: change `uint64` to `fixed64` and run a `clean build`.

Or use the pre-built version.
