### ISSUE TITLE
Failed to drop 1x ITEM_REVIVE: UNSET 

### ISSUE THREAD

**Issue by cleftfairy** [jabbink/PokemonGoBot#279]
**Description:**
Strange, non-fatal error. Using latest build v0.4.1-11-g941bcab

**Steps to reproduce:**
Don't know, hasn't recurred. Later picked up ITEM_REVIVEs x1 and x2 and had no problem dropping them.

**Stacktrace (If it's a crash):**
25 Jul 00:37:31: Looted pokestop 4ebfc05f65a24a4aa0aa95831e5502fa.16; +50 XP: [2xITEM_POKE_BALL, 1xITEM_REVIVE] 
25 Jul 00:37:37: Destination reached.
25 Jul 00:37:46: Failed to drop 1x ITEM_REVIVE: UNSET 
25 Jul 00:37:46: Walking to pokestop "Kompan Playground " (32.70984, -117.151039) in 70.50472431894391 steps.
25 Jul 00:37:49: Dropped 1x ITEM_REVIVE 
25 Jul 00:37:49: Failed to drop 1x ITEM_REVIVE: ERROR_NOT_ENOUGH_COPIES 
Exception in thread "Thread-10" 
                                java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at com.pokegoapi.api.map.MapObjects.update(MapObjects.java:198)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:312)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:250)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:185)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:175)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:101)
        at ink.abb.pogo.scraper.tasks.WalkToUnusedPokestop.run(WalkToUnusedPokestop.kt:24)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:97)
        at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:44)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:97)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:90)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:28)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
25 Jul 00:37:51: Looting nearby pokestop 91cb1b03daef4ce9b3bf925906e1ebc5.16

**Version:**
v0.4.1-11-g941bcab

**Comment by jabbink** [comment]
Shouldn't break anything and the bot just continues, right?

Probably caused by some server issue so it didn't update the user profile. Or you used a revive in just the wrong second from the official client.

**Comment by cleftfairy** [comment]
yep it continues. thx
