### ISSUE TITLE
Egg Hatching Doesn't Work

### ISSUE THREAD

**Issue by nc1992** [jabbink/PokemonGoBot#299]
**Description:**
Egg hatching doesn't work. Neither queuing up of incubators(no errors in logs or exceptions or anything for this one) nor receiving the hatched eggs after .
**Steps to reproduce:**
Run the program with eggs that are due to be hatched, eg 5.0/5.0 Km

**Expected behavior:**
[What should happen?]
Bot responds to these calls from the api correctly
**Actual behavior:**
[What actually happens]
it doesn't
**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]
Exception in thread "Thread-4" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:72)
        at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:34)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:97)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:91)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:25)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
        at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:82)
        at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:1062)
        at com.google.protobuf.CodedInputStream.readRawByte(CodedInputStream.java:1129)
        at com.google.protobuf.CodedInputStream.readRawVarint64SlowPath(CodedInputStream.java:780)
        at com.google.protobuf.CodedInputStream.readRawVarint64(CodedInputStream.java:772)
        at com.google.protobuf.CodedInputStream.readUInt64(CodedInputStream.java:328)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.<init>(GetHatchedEggsResponseOuterClass.java:137)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.<init>(GetHatchedEggsResponseOuterClass.java:75)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse$1.parsePartialFrom(GetHatchedEggsResponseOuterClass.java:1030)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse$1.parsePartialFrom(GetHatchedEggsResponseOuterClass.java:1025)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:105)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:125)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:130)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.parseFrom(GetHatchedEggsResponseOuterClass.java:461)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:70)
        ... 5 more
Getting map of (40
**Version:**

[The version of the lib you used]
built after this commit:
https://github.com/jabbink/PokemonGoBot/commit/e42e0e6a6c7ac2df23f08f0595ab60d0f2bda033

**Comment by philippjess** [comment]
Works perfectly fine in the (updated) released jar and in currentHead branch at the time of writing. Didnt test develop branch.

**Comment by iamthasasquatch** [comment]
I thought this was announced to be an API issue atm Ill check and edit back

**Comment by philippjess** [comment]
This seems to be just cosmetic, the hatching itself works. At least i get
"25 Jul 13:48:32: Put egg *REDACTED* in unused incubator" in the log from time to time.

**Comment by jabbink** [comment]
Is an API issue which is manually patched in the bundled jar.

Also this seems more like some unexpected data in the servers response which might be temporary.
