### ISSUE TITLE
Fails to find config.properties file

### ISSUE THREAD

**Issue by LordBigbus** [jabbink/PokemonGoBot#30]
running through cmd. 

C:\Users\Johnathon Carter\Desktop\New folder (7)>java -jar pogo.scraper-all-0.2.1.jar
Exception in thread "main" java.io.FileNotFoundException: config.properties (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:90)

C:\Users\Johnathon Carter\Desktop\New folder (7)>

Config file is named exactly, even tried copy and pasting the name. I am probably missing something obvious.

**Comment by leadboots5** [comment]
You most likely still have it as a .txt file. Since you're on windows when you have notepad open and do 'save as' select 'all files'(not a windows but it something to that affect). then it will save as a .properties file instead of a .txt file.

**Comment by jabbink** [comment]
while being in `cmd` you can type `notepad config.properties`, if it opens the properties as you saved them, the file exists and you shouldn't get the above error. If it doesn't exist, you get: "This file does not exist".

Then just copy your config to the new notepad window.
