### ISSUE TITLE
Suddenly, constantly getting "Error  in API Url" after no changes

### ISSUE THREAD

**Issue by oSwifty** [jabbink/PokemonGoBot#315]
**Description:**
Was working 100% up until about an hour ago, when I started getting the following trace upon starting the bot. The config was not changed, nor was the version. Have verified the account isn't soft-banned. Any ideas?

**Steps to reproduce:**

1. Start

**Expected behavior:**
Correctly working bot

**Actual behavior:**
Login Failed

**Stacktrace (If it's a crash):**

Logging in to game server...
Logged in as [username] with token [token]
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:149)
	at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
	at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
	at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:107)

**Version:**
0.4.2 release

**Comment by oSwifty** [comment]
Apologies - just saw a recent commit regarding token, and found the token written to the bottom of the config file. Removed that and all good again.
