### ISSUE TITLE
 pogo.scraper-all-0.4.2.jar

### ISSUE THREAD

**Issue by miracho** [jabbink/PokemonGoBot#317]
New version problem.

Logging in to game server...
Exception in thread "main" java.lang.IllegalStateException: if (token.contains("poke?eshToken(token)
        } must not be null
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:90)

:(

**Comment by ColeB27** [comment]
Same problem, I have to clear token= every time now.

**Comment by dan-bowerman** [comment]
I get this using the develop branch, 0.4.2 release build, and 0.4.2 release src...

**Comment by dan-bowerman** [comment]
```
C:\PokemonGoBot>gradlew run
:PokeGOAPI-Java:extractIncludeProto UP-TO-DATE
:PokeGOAPI-Java:extractProto UP-TO-DATE
:PokeGOAPI-Java:generateProto UP-TO-DATE
:PokeGOAPI-Java:compileJava UP-TO-DATE
:PokeGOAPI-Java:processResources UP-TO-DATE
:PokeGOAPI-Java:classes UP-TO-DATE
:PokeGOAPI-Java:jar UP-TO-DATE
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
Logging in to game server...
D/GoogleLogin: Get user to go to:https://www.google.com/device and enter code:XXXX-XXXX
D/GoogleLogin: Got token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Logged in as xxxxxxxxxxxx@gmail.com with token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Setting this token in your config
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:173)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:71)
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
        at sun.security.ssl.InputRecord.read(InputRecord.java:527)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
        at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
        at okhttp3.RealCall.execute(RealCall.java:60)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:115)
        ... 4 more
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_101\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 22.251 secs
```

This happens each time I launch, the initial build is successful but I can't actually run it. I've tried several times to clear the token in the config and it repopulates everytime I submit the new code, but I always end up with the above output. Stuff is X'd out where appropriate.

**Comment by jabbink** [comment]
>Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

Different error. Server is broken

**Comment by jabbink** [comment]
Also this is a duplicate.

https://github.com/jabbink/PokemonGoBot/issues?utf8=%E2%9C%93&q=%20if%20(token.contains(%22poke%3FeshToken(to%20is%3Aissue

**Comment by miracho** [comment]
ty so much.
