### ISSUE TITLE
Does not hatch eggs

### ISSUE THREAD

**Issue by siimveskilt** [jabbink/PokemonGoBot#323]
**Description:**
Under features it lists that egg hatching works, but it's not working. Maybe it's because I assigned all incubators manually before and it won't open the eggs to free incubators?

**Steps to reproduce:**

1. Get eggs.
2. Manually assign incubators.
3. Profit. Oh wait.

**Expected behavior:**
Eggs should hatch.

**Actual behavior:**
Eggs do not hatch.

**Version:**
0.4.2

**Comment by TaylorZaneKirk** [comment]
I literally just hatched an Electabuzz from the 10K egg I manually assigned to an incubator last night. I know that doesn't help you much, but it at least shows that the feature isn't fundamentally broken.

**Comment by siimveskilt** [comment]
My config looks like this (with personal info and token omitted):

should_hatch_eggs=true

# desired chance to catch Pokemon with 1 throw
desired_catch_probability=0.82

## Walking
# Meters per second
speed=2.778

## Items drop
# should the bot EVER drop items (true/false)
drop_items=true

# max number of each item that the bot should keep if "drop_items" is enabled
# use -1 in a item to never drop this specific item
item_revive=20
item_max_revive=10
item_potion=0
item_super_potion=0
item_hyper_potion=70
item_max_potion=70
item_poke_ball=25
item_great_ball=25
item_ultra_ball=100
item_master_ball=50
item_razz_berry=50

## Extra Info
# should the bot display rewards pokestop (true/false)
display_pokestop_rewards=true

# should the bot display rewards when catching pokemon (true/false)
display_pokemon_catch_rewards=true

# should the bot display information of where it's walking to (true/false)
# this will show the name of the pokestop that it's walking to and
# replace on the loot log the pokestop id for its name
# WARNING:  this will increase the https requests without any need. if
#           the servers are slow it's recommended to turn off this setting
display_pokestop_name=false

## Pokemon Transfer
# should the bot auto transfer duplicate pokemon
autotransfer=true

# minimum amount of pokemon type to keep
keep_pokemon_amount=2

# Sort by IV first instead of CP
sort_by_iv=true

# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=90

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=600

# Only walk (hatch eggs, don't collect pokemon or pokestops)
walk_only=false

# list of pokemon you don't want to transfer regardless of CP
# the names must be divided by a ","
# if you want all pokemons to be transferred just leave it blank
ignored_pokemon=MEWTWO,CHARMANDER

# list of pokemon you always want to trancsfer regardless of CP
obligatory_transfer=DODUO,RATTATA,CATERPIE,PIDGEY,JYNX

**Comment by sakindia123** [comment]
Just hatched a 636 Machop,and another egg was automatically put in incubator,don't think it is an issue

**Comment by siimveskilt** [comment]
Could one of you post your config here so I could try it?

**Comment by TaylorZaneKirk** [comment]
Sure, I don't think I really changed from the defaults, though.

```
# desired chance to catch Pokemon with 1 throw
desired_catch_probability=0.8

## Walking
# Meters per second
speed=2.778

## Items drop
# should the bot EVER drop items (true/false)
drop_items=true

# max number of each item that the bot should keep if "drop_items" is enabled
# use -1 in a item to never drop this specific item
item_revive=20
item_max_revive=10
item_potion=0
item_super_potion=30
item_hyper_potion=50
item_max_potion=50
item_poke_ball=50
item_great_ball=50
item_ultra_ball=50
item_master_ball=50
item_razz_berry=50

## Extra Info
# should the bot display rewards pokestop (true/false)
display_pokestop_rewards=true

# should the bot display rewards when catching pokemon (true/false)
display_pokemon_catch_rewards=true

# should the bot display information of where it's walking to (true/false)
# this will show the name of the pokestop that it's walking to and
# replace on the loot log the pokestop id for its name
# WARNING:  this will increase the https requests without any need. if
#           the servers are slow it's recommended to turn off this setting
display_pokestop_name=false

## Pokemon Transfer
# should the bot auto transfer duplicate pokemon
autotransfer=false

# minimum amount of pokemon type to keep
keep_pokemon_amount=1

# Sort by IV first instead of CP
sort_by_iv=false

# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=80

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=400

# Only walk (hatch eggs, don't collect pokemon or pokestops)
walk_only=false

# list of pokemon you don't want to transfer regardless of CP
# the names must be divided by a ","
# if you want all pokemons to be transferred just leave it blank
ignored_pokemon=EEVEE,MEWTWO,CHARMANDER

# list of pokemon you always want to trancsfer regardless of CP
obligatory_transfer=DODUO,RATTATA,CATERPIE,PIDGEY
```

**Comment by siimveskilt** [comment]
Finally found a clue!

`Exception in thread "Thread-63" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:72)
        at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:34)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:101)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:95)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:25)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
        at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:82)
        at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:1062)
        at com.google.protobuf.CodedInputStream.readRawByte(CodedInputStream.java:1129)
        at com.google.protobuf.CodedInputStream.readRawVarint64SlowPath(CodedInputStream.java:780)
        at com.google.protobuf.CodedInputStream.readRawVarint64(CodedInputStream.java:772)
        at com.google.protobuf.CodedInputStream.readUInt64(CodedInputStream.java:328)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.<init>(GetHatchedEggsResponseOuterClass.java:137)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.<init>(GetHatchedEggsResponseOuterClass.java:75)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse$1.parsePartialFrom(GetHatchedEggsResponseOuterClass.java:1030)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse$1.parsePartialFrom(GetHatchedEggsResponseOuterClass.java:1025)
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:105)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:125)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:130)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.parseFrom(GetHatchedEggsResponseOuterClass.java:461)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:70)
        ... 5 more`

**Comment by EyesReye** [comment]
The hatching is alot slower than it was back in 0.3.0

**Comment by jabbink** [comment]
>The hatching is alot slower than it was back in 0.3.0

it's not, unless you increased your walking speed from the default value

>Finally found a clue!
>Exception in thread "Thread-63" com.pokegoapi.exceptions.RemoteServerException: 

Server error, invalid
