### ISSUE TITLE
[Bug] Failed to run after login (develop)

### ISSUE THREAD

**Issue by Emuuung** [jabbink/PokemonGoBot#325]
I get this error message when trying to run after login with PTC account, building from source from branch "develop":
```
:run
Logging in to game server...
Logged in as XXXXXX with token TGT-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-sso.pokemon.com
Setting this token in your config
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:83)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:71)
Exception in thread "main" java.lang.NullPointerException
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:88)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:71)
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by CosmoRing** [comment]
Servers down

**Comment by Emuuung** [comment]
Ah thank you, after the line
`com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null`
it seemed a little weird seeing the "google" name when I was trying to log from a PTC account.
