### ISSUE TITLE
Problem w logging in PTC Account! :(

### ISSUE THREAD

**Issue by Zeift** [jabbink/PokemonGoBot#329]
Setting this token in your config
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:149)
	at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
	at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
	at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:107)

Another problem when I removed token is.
Setting this token in your config
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
	at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:83)
	at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
	at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:107)
Exception in thread "main" java.lang.NullPointerException
	at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:88)
	at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
	at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:107)

**Comment by ColeB27** [comment]
PTC Servers are down, check www.ispokemongodownornot.com and try again later.

**Comment by Zeift** [comment]
Thanks!
