### ISSUE TITLE
Exception in thread "Thread-376"

### ISSUE THREAD

**Issue by Dr4mEdo** [jabbink/PokemonGoBot#33]
Hello, great work ! Very easy to use ;)

I got a little error after 20 min of use

```
Exception in thread "Thread-376" com.pokegoapi.exceptions.LoginFailedException
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:94)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:170)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:147)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:93)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt:166)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

If that can help ;)

Use on Mac 10.11.5 
Java 8 update 91

**Comment by Dr4mEdo** [comment]
Just got this one : 

```
Dropped 3x ITEM_POKE_BALL
Exception in thread "Thread-30" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:104)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:170)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:147)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:93)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:83)
	at com.pokegoapi.api.map.Map.getRetainedMapObject(Map.java:51)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:64)
	at ink.abb.pogo.scraper.MainKt.processMapObjects(Main.kt:216)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt:167)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

```

Still working ;)

**Comment by leadboots5** [comment]
I also get LoginFailedException on Mac. I haven't looked at the code to see if Thread is a count but its triggered in the high 300s low 400s every time now and then just keeps getting it. If its had an issue with login then it should probably just terminate instead of continually attempting to get the map.

> Exception in thread "Thread-406" com.pokegoapi.exceptions.LoginFailedException
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:94)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:170)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:147)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:93)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt:166)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by D3C1V3R** [comment]
I'm assuming this error is related to a timeout issue with googles login(Unless you're using PTC?) and however that's handled. I've experienced it too after running the bot for 20-30 minuets, @leadboots5 I'm almost assuming the thread count is just an error log count, nothing significant.
@Dr4mEdo Your error isnt related to LoginFailedException

**Comment by leadboots5** [comment]
Got my errors using PTC

**Comment by Dr4mEdo** [comment]
I'm using PTC also.

**Comment by apottere** [comment]
I'm getting a logout exception on Mac with Google login.

**Comment by vdianl** [comment]
As well on ptc as google.
The bot needs to reconnect with pokemon go cause it wants unauthorized get the map with pokestops and pokemons. Thats the failure.
Im not familiar with this java dialect so its hard for me to fix it.

**Comment by XeNz** [comment]
I'm not that into OAuth2 but I think the refresh token needs to be saved and needs to be used to exchange it for an access token instead of just using the access token and letting this access token time out.

**Comment by jabbink** [comment]
Yeah, the login thing is an upstream issue with the Java API that this thing uses.

The `java.lang.IndexOutOfBoundsException: Index: 0, Size: 0` was also an upstream issue which has been resolved already.
