### ISSUE TITLE
Stuck on Pokemon when out of PokeBalls

### ISSUE THREAD

**Issue by xenxes** [jabbink/PokemonGoBot#332]
When out of Pokeballs, the bot loops on the same target, easy fix might be to set a minimum # of balls threshold before catching?

25 Jul 09:55:32: Found pokemon RATTATA
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:97)
25 Jul 09:55:32: Encountered pokemon RATTATA with CP 10
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.
invoke(Bot.kt:83)
25 Jul 09:55:32: No balls available
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.
invoke(Bot.kt:28)
25 Jul 09:55:36: Getting map of (38.57683176218426, -121.49541664465436)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
25 Jul 09:55:37: Found pokemon RATTATA
Exception in thread "Thread-9576" kotlin.KotlinNullPointerException
25 Jul 09:55:37: Encountered pokemon RATTATA with CP 10
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPo
kemon.kt:32)
25 Jul 09:55:37: No balls available
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:97)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.
invoke(Bot.kt:83)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.
invoke(Bot.kt:28)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by jabbink** [comment]
Already fixed when you compile from source
