### ISSUE TITLE
Pct login error

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#336]
This happens when I try to login with my pct account. The weird thing is that my other pct account is running perfect right now. with the same settings ( I think). What's the issue here?

D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.ja
va:83)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:107)
Exception in thread "main" java.lang.NullPointerException
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.ja
va:88)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:107)

**Comment by TechnoDaft** [comment]
http://ispokemongodownornot.com/

**Comment by Leodenact** [comment]
It's been all day, and one of my pct is working perfectly. It's something with the settings I guess.. Can I delete the settings completely to get a fresh start without the need to reinstall the whole program?

**Comment by Leodenact** [comment]
Update:

Interesting, I changed the starting location and it magicly worked out.

**Comment by jabbink** [comment]
Great
