### ISSUE TITLE
[Bug in 0.4.2] Error after enter code for google device

### ISSUE THREAD

**Issue by gl-lamhnguyen** [jabbink/PokemonGoBot#337]
**Description:**
Using google login, got error after I entered the code on google.com/device

**Steps to reproduce:**

1. Use google login in config.json with no password
2. Grab the code outputs by bot program and enter it on google.com/device
3. Program continues and crashes

**Expected behavior:**
Bot should be running

**Actual behavior:**
Error:
```
25 Jul 18:11:25: Display Keepalive Coordinates setting ("display_keepalive") not specified, defaulting to "true".
Logging in to game server...
D/GoogleLogin: Get user to go to:https://www.google.com/device and enter code:EMTG-LUWU
D/GoogleLogin: Got token: <REDACTED>
Logged in as <REDACTED> with token <REDACTED>
Setting this token in your config
Exception in thread "main" java.lang.NoSuchMethodError: java.io.BufferedReader.lines()Ljava/util/stream/Stream;
        at ink.abb.pogo.scraper.Settings.writeToken(Settings.kt:139)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:105)
```

**Version:**
0.4.2

**Comment by pr0ves** [comment]
What java version do you have?

**Comment by siimveskilt** [comment]
He has 7. Get java 8 and problem solved.

**Comment by dan-bowerman** [comment]
I get something similar, but related to SSL, any ideas how to resolve?

```
C:\PokemonGoBot>gradlew run
:PokeGOAPI-Java:extractIncludeProto UP-TO-DATE
:PokeGOAPI-Java:extractProto UP-TO-DATE
:PokeGOAPI-Java:generateProto UP-TO-DATE
:PokeGOAPI-Java:compileJava UP-TO-DATE
:PokeGOAPI-Java:processResources UP-TO-DATE
:PokeGOAPI-Java:classes UP-TO-DATE
:PokeGOAPI-Java:jar UP-TO-DATE
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
Logging in to game server...
D/GoogleLogin: Get user to go to:https://www.google.com/device and enter code:XXXX-XXXX
D/GoogleLogin: Got token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Logged in as xxxxxxxxxxxx@gmail.com with token xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Setting this token in your config
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:173)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:71)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by gl-lamhnguyen** [comment]
great, thank you
