### ISSUE TITLE
Still not working on Mac

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#35]
Exception in thread "main" java.io.FileNotFoundException: config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:90)

I have config.properties file ready, in the same folder with jar file.
still getting this error.
Updated Java Enviroment, and JDK too

**Comment by falko100** [comment]
Are you sure you don't have a typo ? Works perfectly here.

**Comment by leadboots5** [comment]
You most likely have it as a txt file. Right click the file. Go to 'Get Info'. Under 'Name & Extension' you'll likely see 'config.properties.txt' Delete the '.txt' and then save/keep your change.

**Comment by CptJackieSparrow** [comment]
nope i did it already.. I dunno i'm certainly doing something wrong, PC is not catching pokemon either.. You guys locate jar file on desktop?

**Comment by Dr4mEdo** [comment]
Did you locat your folder in the terminal 
`cd "your folder"`

**Comment by CptJackieSparrow** [comment]
THIS HELPED THANK YOU @Dr4mEdo

**Comment by CptJackieSparrow** [comment]
:dancer:  @Dr4mEdo

**Comment by CptJackieSparrow** [comment]
Guys I have one last request.
I'd like to have a bash script for this one, features will be:
1st) End process after 8 minutes of farming/botting
2nd) Start process
3rd) exectue "cd [location of my pokebot folder]"
4th)execute "java -jar [jar folder name]
5th) loop, i have no coding skills, so i'll be glad if someone can create it for me if it's not time consuming

**Comment by WithoutWout** [comment]
I've put together this script which seems to do somewhat what I think you're looking for, although not in the order you asked. It makes the process timeout after 480 seconds, which is 8 minutes and then restarts again. CTRL + C should always stop it. To make this work more easily, you could put it in a .command file. This file need it's permissions changed by running `chmod a+x [.command file location here]`

```
function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
cd [location of my pokebot folder]
while true
do
timeout 480 java -jar pogo.scraper-all-0.2.1.jar
done
```

I've tested it with 15 seconds timeout and it seemed to do the trick just fine. Hope it works for you as well.

**Comment by apexjnr** [comment]
@CptJackieSparrow  what did you have to do to get it working?

**Comment by CptJackieSparrow** [comment]
open terminal
write "cd" hit space the drag and drop the folder your jar app in (not jar app, te folder), hit enter
then write "java -jar" hit space them drag and drop jar app, hit enter.

**Comment by CptJackieSparrow** [comment]
@withoutwout thanks brother. I'll have a look at it when i go home, lets see if a code dumb like me can make it work

**Comment by CptJackieSparrow** [comment]
@WithoutWout 

`Exception in thread "Thread-16" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:175)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:147)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:93)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt:166)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:31)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:173)
	... 5 more
Exception in thread "Thread-15" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:104)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:170)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:147)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:93)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:83)
	at com.pokegoapi.api.map.Map.getRetainedMapObject(Map.java:51)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:64)
	at ink.abb.pogo.scraper.MainKt.processMapObjects(Main.kt:216)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt:167)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)`

here's the error i'm getting now

**Comment by jabbink** [comment]
That error means, as the first line indicates in an unreadable way, that the remote server broke down, aka Niantics servers are broken.

**Comment by CptJackieSparrow** [comment]
thank you guys for your awesome support!
