### ISSUE TITLE
Login not working anymore

### ISSUE THREAD

**Issue by d-moos** [jabbink/PokemonGoBot#350]
**Description:**
Login is not working anymore (at least PTC)

**Steps to reproduce:**
Log in with any PTC account

**Expected behavior:**
Being logged in 

**Actual behavior:**
Exception thrown

**Stacktrace (If it's a crash):**
Logging in to game server...
Logged in as xxxxx with token xxxxxxxx
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:149)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:107)

**Version:**
v0.4.2

**Comment by d-moos** [comment]
Removing token and log-in again fixed the issue somehow.

**Comment by Agronis** [comment]
Be sure to close this issue please.
