### ISSUE TITLE
PTC login not working

### ISSUE THREAD

**Issue by unnieverse** [jabbink/PokemonGoBot#354]
**Description:**

I can't log in with a specific ptc account. I can log in with three other ptc accounts.

**Steps to reproduce:**

Running pogo.scraper-all-0.3.0.jar would output:

Logging in to game server...
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException
	at com.pokegoapi.auth.PtcLogin.login(PtcLogin.java:197)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:82)

Running pogo.scraper-all-0.4.2.jar would output:

Logging in to game server...
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException
	at com.pokegoapi.auth.PtcLogin.login(PtcLogin.java:196)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:87)

**Comment by Agronis** [comment]
Go into your config file and verify your credentials are correct.

Remove token and retry.

If still failing, double check in official app that this account isn't banned.

**Comment by unnieverse** [comment]
idk why you closed this. I searched before posting and none of the other people had solutions that worked for me.

**Comment by Enochen** [comment]
You have the same error, so comment on their issue instead.

**Comment by unnieverse** [comment]
Figured it might be better than hijacking a thread. Btw the solution for my problem hasn't been posted yet. So good luck with that.
