### ISSUE TITLE
com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null

### ISSUE THREAD

**Issue by TerrorFactor** [jabbink/PokemonGoBot#358]
Hi,

I ran into issues trying to set up the latest version of the bot on another pc. 
```
C:\Users\user\Downloads\PokemonGoBot>gradlew run
:PokeGOAPI-Java:extractIncludeProto UP-TO-DATE
:PokeGOAPI-Java:extractProto UP-TO-DATE
:PokeGOAPI-Java:generateProto UP-TO-DATE
:PokeGOAPI-Java:compileJava UP-TO-DATE
:PokeGOAPI-Java:processResources UP-TO-DATE
:PokeGOAPI-Java:classes UP-TO-DATE
:PokeGOAPI-Java:jar UP-TO-DATE
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
26 Jul 00:24:49: Display Keepalive Coordinates setting ("display_keepalive") not
 specified, defaulting to "true".
Logging in to game server...
Logged in as censored with token TGT-censored-censored
censored-sso.pokemon.com
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.ja
va:83)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:71)
Exception in thread "main" java.lang.NullPointerException
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.ja
va:88)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:71)
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe'' finished w
ith non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 8.701 secs
```
The account works well on an older build from yesterday, on a different pc. I tested it multiple times with a few hours between them, as there seemed to have been issues with the login servers.
Downloaded and installed the latest jdk today, installed github tools, used the git console as mentioned in the instructions on the first page.
Filled in the config template (withe notepad++), removed template in the filename and tried to run it.
Tried with 2 PTC accounts. Both accounts work well on my other system with the older build of the bot.

EDIT:
To help diagnose this, I copied my old bot folder completely to the new machine. The old one also works on that machine.

```
C:\Users\user\Downloads\PokemonGoBot - 2>gradlew run
Download https://jitpack.io/com/github/Grover-c13/PokeGOAPI-Java/master-SNAPSHOT
/PokeGOAPI-Java-master-f21ab72705-1.pom
Download https://repo1.maven.org/maven2/org/isuper/s2-geometry-library-java/0.0.
1/s2-geometry-library-java-0.0.1.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.p
om
Download https://repo1.maven.org/maven2/com/google/guava/guava-parent/18.0/guava
-parent-18.0.pom
Download https://jitpack.io/com/github/Grover-c13/PokeGOAPI-Java/master-SNAPSHOT
/PokeGOAPI-Java-master-f21ab72705-1.jar
Download https://repo1.maven.org/maven2/org/isuper/s2-geometry-library-java/0.0.
1/s2-geometry-library-java-0.0.1.jar
Download https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.j
ar
:compileKotlin
w: C:\Users\user\Downloads\PokemonGoBot - 2\src\main\kotlin\ink\abb\pogo\scr
aper\Main.kt: (52, 13): 'sslSocketFactory(SSLSocketFactory!): OkHttpClient.Build
er!' is deprecated. Deprecated in Java
w: C:\Users\user\Downloads\PokemonGoBot - 2\src\main\kotlin\ink\abb\pogo\scr
aper\tasks\ReleasePokemon.kt: (42, 42): Variable 'reason' initializer is redunda
nt
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
Display Keepalive Coordinates setting ("display_keepalive") not specified, defau
lting to "true".
26 Jul 00:49:12: Logging in to game server...
26 Jul 00:49:13: Logged in as censored with token TGT-censored-censored
censored-sso.pokemon.com
26 Jul 00:49:13: Set this token in your config to log in directly
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Getting profile data from pogo server.

Name: censored
Team: TEAM_NONE
```

**Comment by pilotchute** [comment]
clear the token in config.properties

from:
token=<lots of random characters>
to:
token=

Then re-login. The issue is that your static token expired.
