### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Qasimmodo** [jabbink/PokemonGoBot#368]
Exception in thread "main" java.lang.NoSuchMethodError: java.util.Comparator.thenComparing(Ljava/util/Comparator;)Ljava/util/Comparator;
        at ink.abb.pogo.scraper.Bot.run(Bot.kt:55)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:116)

**Comment by li24yang75** [comment]
I think you should update your jdk.

**Comment by jabbink** [comment]
Use Java 8, not 7!
