### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by askep3** [jabbink/PokemonGoBot#370]
When I launch the program it logs in fine, but crashes right away, here is the log:

Logging in to game server...
Logged in as XXXX with token XXXX
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:149)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:107)

Both of my bots are doing this, every time I try to launch them, but I don't know if this is happening to other people too.

Version 0.4.2

**Comment by askep3** [comment]
Tested with version 0.3.0 and its running fine, and POGO servers are up, so its a local issue.

**Comment by PeterXQChen** [comment]
Remove the string on "token" to fix this.

**Comment by askep3** [comment]
@PeterXQChen That fixed it, thanks! I just made a new config file before I saw your comment, next time I'll just do that.
