### ISSUE TITLE
index out of bound exception after putting an egg

### ISSUE THREAD

**Issue by okynk** [jabbink/PokemonGoBot#380]
**Description:**
index out of bound exception after putting an egg

**Steps to reproduce:**
1. put egg

**Stacktrace (If it's a crash):**
```
26 Jul 13:19:27: Put egg 8356779197444194577 in unused incubator 
Getting map of (-6.174691154052173, 106.82710170912323)
Exception in thread "Thread-7" java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
        at java.util.ArrayList.rangeCheck(ArrayList.java:638)
        at java.util.ArrayList.get(ArrayList.java:414)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1369)
        at POGOProtos.Networking.Responses.GetHatchedEggsResponseOuterClass$GetHatchedEggsResponse.getExperienceAwarded(GetHatchedEggsResponseOuterClass.java:292)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:78)
        at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:34)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:97)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:91)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:25)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Version:**
`0.4.2`

**Comment by jabbink** [comment]
Use the precompiled version or patch the protobufs yourself to incorporate the fix.
