### ISSUE TITLE
Bot is walking in circles

### ISSUE THREAD

**Issue by MyUncleSam** [jabbink/PokemonGoBot#500]
**Description:**
My bot stopped to walk from pokestop to pokestop and is just walking in circles. A friend using this bot has the same troubles.

**Steps to reproduce:**
Start the bot :-(
Also tried to set no coordinates but then it is walking in circles there.

**Expected behavior:**
Do not know if it is depending on this error:

```
27 Jul 17:50:30: Error running loop BotLoop! 
java.lang.NoClassDefFoundError: ink/abb/pogo/scraper/tasks/LootOneNearbyPokestop$WhenMappings                                                                                                                      
        at ink.abb.pogo.scraper.tasks.LootOneNearbyPokestop.run(LootOneNearbyPokestop.kt:45)                                                                                                                       
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)                                                                                                                                                               
        at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:40)                                                                                                                                 
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)                                                                                                                                                               
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:115)                                                                                                                                                     
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:30)                                                                                                                                                      
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:128)                                                                                                                                                   
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:30)                                                                                                                                                    
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)    
```      

**Actual behavior:**
Walk in circles around a point

**Stacktrace (If it's a crash):**
No crash

**Version:**
v0.4.3

**Operating System:**
Ubuntu 16.04 LTS

**Java version:**
Oracle 1.8

**Comment by MyUncleSam** [comment]
Ok now it seems like it is running again ...  is this a server problem?

**Comment by pr0ves** [comment]
If you're using a ptc account, yes. The ptc servers have been down for a couple hours, check [here](http://ispokemongodownornot.com/) to check if they're down.
Closing.
