### ISSUE TITLE
Error running botloop

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#517]
This has been happening for a few builds now, starts doing that a while after running. No specific time before it does it. I left it overnight, worked perfectly, an hour after waking up it came up with this error.

commit ba305eb5fc740abdfeede7535eb684d47d2dbb82

```
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.j
ava:129)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:302)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPo
kemon.kt:27)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:112)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:32)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
27 Jul 20:37:33: Getting map of (40.7797646435112, -73.96477599477195)
27 Jul 20:37:33: Error running loop BotLoop!
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.j
ava:129)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:302)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPo
kemon.kt:27)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:112)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:32)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
27 Jul 20:37:38: Getting map of (40.779808633794644, -73.96482742296624)
27 Jul 20:37:38: Error running loop BotLoop!
```

**Comment by alone23** [comment]
version? branch?

**Comment by omar972** [comment]
Develop branch, and I did post the latest commit. commit ba305eb

**Comment by alone23** [comment]
Remove token and try again

**Comment by jabbink** [comment]
Ptc or Google?

**Comment by omar972** [comment]
Google, ill try alone's suggestion.

**Comment by omar972** [comment]
Nope, still the same problem.

**Comment by tzakil** [comment]
I have the same problem. Im also getting walkingloop error and sometimes profileloop error on top of botloop error. But its still catching some pokemon. 

http://pastebin.com/qVK0fsML

And the localhost:8000 is just showing a log

![screen shot 2016-07-27 at 5 42 38 pm](https://cloud.githubusercontent.com/assets/20675151/17193536/8f5ab4c2-5421-11e6-8acb-93b23d0d1512.jpg)

**Comment by omar972** [comment]
@jabbink Is the problem from our side or is there a fix coming?

**Comment by jabbink** [comment]
>com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null


Servers were offline

**Comment by omar972** [comment]
Oh I see. Anyway to make it continue automatically when they are back online? Or should I just make a task in task scheduler that automatically kills the script and reruns it every couple of hours?

**Comment by jabbink** [comment]
Not sure if it will resume automatically, never tested it.

**Comment by omar972** [comment]
It's not for me.

**Comment by rclai** [comment]
I got some random errors, but it started walking now: 
```
27 Jul 18:52:49: Error running loop BotLoop! 
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:27)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:109)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:30)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:128)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:30)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
        ... 11 more
27 Jul 18:52:49: Error running loop ProfileLoop! 
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:73)
        at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:22)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:103)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:30)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:128)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:30)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:71)
        ... 7 more
27 Jul 18:52:54: Getting map of (26.157511394606782, -80.13321879507005)
27 Jul 18:52:54: Walking to (26.156819, -80.132244) in 220.75108114832483 steps.
27 Jul 18:52:59: Getting map of (26.15742497705146, -80.13313253749332)
```

**Comment by rclai** [comment]
There's also a random ProfileLoop error:

```
27 Jul 18:53:49: Profile update: 440090 XP on LVL 23; 5090/125000 (4.07%) to LVL 24 
27 Jul 18:53:49: XP gain: 100 XP; Pokemon caught/transferred: 0/0; Items caught/dropped: 4/0;
Pokebank 99/250; Stardust 52278; Inventory 262/350 
27 Jul 18:53:49: Error running loop ProfileLoop! 
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:73)
        at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:22)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:103)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:30)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:128)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:30)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:71)
        ... 7 more
```

**Comment by jabbink** [comment]
All related to broken servers.

**Comment by rclai** [comment]
Should this be taken as a warning sign or should I just let it run?

**Comment by Cy4n1d3** [comment]
Is this related to this issue?
```
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
	at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:21)
	at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:82)
	at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:332)
	at com.pokegoapi.api.map.MapObjects.update(MapObjects.java:198)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
java.util.ConcurrentModificationException
[31;1m28 Jul 08:06:28: Error running loop WalkingLoop! [0m
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
	at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:21)
	at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:82)
	at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:332)
	at com.pokegoapi.api.map.MapObjects.update(MapObjects.java:198)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
java.util.ConcurrentModificationException
[31;1m28 Jul 08:06:28: Error running loop WalkingLoop! [0m
28 Jul 08:06:23: Resuming walk.
 Stamina: 0 | Attack: 9 | Defense: 15 | IV: 24 (53%): [200x XP, 3x Candy, 100x Stardust] [0m
[36;1m28 Jul 08:06:23: Caught a EKANS with CP 53 and IV 53%
[...]
28 Jul 08:06:23: Pausing to catch pokemon...
[32;1m28 Jul 08:06:23: Found pokemon EKANS [0m
28 Jul 08:06:22: Resuming walk.
28 Jul 08:06:20: Pausing to catch pokemon..
```
This is more likely to be a threading issue it seems.

**Comment by PancakeZik** [comment]
I'm also having similar errors, but doesn't seem to be anything related to the servers:

> 28 Jul 09:40:36: Resuming walk.
28 Jul 09:40:40: Error running loop BotLoop!
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at com.pokegoapi.api.map.MapObjects.update(MapObjects.java:198)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:332)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:28)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:112)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:32)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
28 Jul 09:40:46: Looting nearby pokestop "Westminster Baptist Church  "

>

**Comment by jabbink** [comment]
Concurrent modification error might come from #523

**Comment by pvase666** [comment]
Just got same error.
