### ISSUE TITLE
How to access the localhost?

### ISSUE THREAD

**Issue by Leodenact** [jabbink/PokemonGoBot#538]
I have no programs installed on my computer, how can see the stats on the bot from localhost? when I try typing it in the web it says access denied.

**Comment by vamirineni87** [comment]
http://localhost:8000

**Comment by Emuuung** [comment]
@Leodenact Change the port in the configuration file, the default port is 8000 but it could be blocked in your system network.

**Comment by Scoboose** [comment]
try going to 127.0.0.1:8000 in your web browser

**Comment by Jstillerman** [comment]
Make sure you downloaded the new release

**Comment by Emuuung** [comment]
@Leodenact If any of the answers worked for you, please close your issue, if not, reply with more information; like logs.

**Comment by Lenovotro** [comment]
I have the same issue. No console logs, just doesn't have an application to open localhost on 8000. 5000 worked on a previous build, so I assume its a port issue.

**Comment by Lenovotro** [comment]
I'm getting this error:

`java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at com.pokegoapi.api.map.MapObjects.update(MapObjects.java:198)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:332)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:82)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:21)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)`

**Comment by Leodenact** [comment]
I go to my broswer aand type in localhost and I'm not getting anywhere. Do i need to install a program first? I have the latest release btw.
I don't have any programs on this computer, maybe I need a another program installed to access localhost?
Should I type something i cmd?

**Comment by Spyderdreams** [comment]
This runs fine after you start the jar file the web services are started. I have 7 bot all running and I  added these two lines to the config file and gave each bot a different port.

gui_port=8000
gui_port_socket=8001
![image](https://cloud.githubusercontent.com/assets/20584970/17199290/6fbca010-5441-11e6-85ec-904bab2cb75e.png)

**Comment by Lenovotro** [comment]
@Leodenact Don't use Microsoft Edge, use internet explorer.

**Comment by langerhans** [comment]
>I go to my broswer aand type in localhost

Please read the replies you got. You have to enter the port too, here I'll make a clickable link for your convenience: [http://localhost:8000](http://localhost:8000)

**Comment by BartWillems** [comment]
@Lenovotro Don't use internet explorer nor edge, they are both equally evil and bad

**Comment by sakindia123** [comment]
How do u get the map and the Pokebank?I only get a log with notifications

![pogo](https://cloud.githubusercontent.com/assets/1249661/17210980/1e2fc288-54e4-11e6-9181-0d8f0fec2af6.PNG)

**Comment by pr0ves** [comment]
Resize the log window and move it on the side, the map should be underneath.

**Comment by langerhans** [comment]
Assuming this issue is resolved.
