### ISSUE TITLE
[non fatal bug] timeout error with new build 0.5.0 alpha

### ISSUE THREAD

**Issue by Emuuung** [jabbink/PokemonGoBot#541]
I encounterd this in log:
```
27 jul 19:17:33: Error running loop WalkingLoop!
com.pokegoapi.exceptions.RemoteServerException: java.net.SocketTimeoutException: timeout
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:153)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:302)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:86)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:21)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.net.SocketTimeoutException: timeout
        at okio.Okio$3.newTimeoutException(Okio.java:210)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
        at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
        at okhttp3.RealCall.execute(RealCall.java:60)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:107)
        ... 11 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at okio.Okio$2.read(Okio.java:138)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
        ... 32 more
27 jul 19:17:37: Destination reached.
```
But the bot was able to continue. Maybe the sever was slow?

**Comment by langerhans** [comment]
Yes, this is a response timeout, so the request was sent successfully but the server failed to reply in time. Either your network was flaky at that time or the pogo servers had a hiccup. Closing as the bot recovered gracefully.
