### ISSUE TITLE
Web UI Port Issue

### ISSUE THREAD

**Issue by KyleBoyer** [jabbink/PokemonGoBot#546]
After closing and reopening a compiled Jar, port 8000 is not closed properly.

Stack Trace:

Exception in thread "main" java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:484)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1080)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:430)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:415)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:197)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:350)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

**Comment by langerhans** [comment]
What version is that on? #526 is in 0.5.0 which should have fixed that for the socket server.

**Comment by Agronis** [comment]
>closing and reopening a compiled Jar

Yes, but are you sure you killed the background service itself?

Typically when I see 'address already in use' I think of any web app I'm testing that I forgot to properly shut down and there is still a ***Java*** process running in the background.

**Comment by KyleBoyer** [comment]
I was on the latest dev version at the time of writing this issue. I believe the person above is correct, as when I ran a command to see what was using that port, I had to kill a Java process in order for my new bot's socket to work.

**Comment by langerhans** [comment]
Assuming this is fixed.
