### ISSUE TITLE
[bug] ConcurrentModificationException

### ISSUE THREAD

**Issue by rraumberger** [jabbink/PokemonGoBot#577]
**Description:**
ConcurrentModificationException occurred after upgrading to v0.5.0-Alpha.
... and yes i know that it's a alpha.. just wanted to let you guys know.

**Steps to reproduce:**
Haven't been able to reproduce it, so far.
It just randomly occurred after ~5 min since starting the bot.

**Expected behavior:**
Well.. no exception?

**Actual behavior:**
See below.

**Stacktrace (If it's a crash):**
28 Jul 17:19:07: Error running loop BotLoop!
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at com.pokegoapi.api.map.MapObjects.update(MapObjects.java:188)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:332)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:28)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:112)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:32)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Version:**
v0.5.0-Alpha

**Operating System:**
Linux 3.10.0-042stab113.21

**Java version:**
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b13)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by pashorizer** [comment]
That's not a big deal for now the bot will just work fine. I'll put a fix later in for that. It's API related.

**Comment by kasagon** [comment]
I just got something similair.
Also this BotLoop error, but at the same time I get ProfileLoop and WalkingLoop errors:
http://pastebin.com/zUN2USfh

Also, for me the bot stopped doing everything else with those errors, it stayed in place for about 25-30 minutes with only those errors.

**Comment by pashorizer** [comment]
Going to be fixed soon

https://github.com/Grover-c13/PokeGOAPI-Java/pull/324

**Comment by langerhans** [comment]
This specific one is fixed on alpha3. There are some others tho, but that is not as bot issue, therefore closing here.
