### ISSUE TITLE
0.5.0alpha2: RemoteServerException

### ISSUE THREAD

**Issue by HoneyWheat** [jabbink/PokemonGoBot#596]
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
        at com.pokegoapi.api.pokemon.Pokemon.transferPokemon(Pokemon.java:106)
        at ink.abb.pogo.scraper.tasks.ReleasePokemon.run(ReleasePokemon.kt:46)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:116)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:32)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:112)
        ... 9 more

**Comment by langerhans** [comment]
Servers are overloaded, not a bot issue.

**Comment by HoneyWheat** [comment]
See #608

**Comment by aTadTasty** [comment]
but it's not just server being overloaded.  i think they reduced the rate you are able to request and send packets.
