### ISSUE TITLE
Logs error

### ISSUE THREAD

**Issue by pikachukaki** [jabbink/PokemonGoBot#604]
What is Error running loop WalkingLoop! and Error running loop BotLoop! are they problems???

**Comment by pikachukaki** [comment]
29 Ιουλ 01:08:00: Error running loop ProfileLoop!
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:75)
        at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:22)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:106)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:32)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:112)
        ... 9 more

**Comment by langerhans** [comment]
#596 #597 #598 #601 

Try searching next time ;)
