### ISSUE TITLE
Started receiving error in 0.4.3

### ISSUE THREAD

**Issue by insufficient-funds** [jabbink/PokemonGoBot#612]
**Description:**
Below error began to pop up when running 0.4.3 earlier this afternoon

**Steps to reproduce:**

1. launch 0.4.3 bot
2. retreives list of pokemon in inventory
2. gets map, then initial pokestops, then error

**Expected behavior:**
launch  bot, works.

**Actual behavior:**
launch bot, receive error.

**Stacktrace (If it's a crash):**
28 Jul 19:28:16: Have ZUBAT () with 283 CP and IV 91%
 Stamina: 15 | Attack: 12 | Defense: 14 | IV: 41 (91%)
28 Jul 19:28:16: Getting map of (37.26929003896382, -79.94060936099667)
28 Jul 19:28:16: Getting initial pokestops...
28 Jul 19:28:16: Got 117 pokestops
28 Jul 19:28:16: Getting map of (37.26926389004664, -79.9405887774163)
[31;1m28 Jul 19:28:16: Error running loop ProfileLoop! [0m
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:73)
        at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:22)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:103)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:30)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:128)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:30)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:71)
        ... 7 more
[31;1m28 Jul 19:28:16: Error running loop BotLoop! [0m
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:27)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:109)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:30)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:128)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:30)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
        ... 11 more
28 Jul 19:28:21: Getting map of (37.269297087225006, -79.9405914094104)

**Version:**
bot version 0.4.3

**Operating System:**
win 10 x64

**Java version:**
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)

**Comment by insufficient-funds** [comment]
Sorry if this has already been posted/discussed/solved; i glanced through other open issues but didn't see anything similar.

**Comment by Agronis** [comment]
Now that you've seen it's already been posted, please close this issue.

**Comment by jjordantb** [comment]
@Agronis He stated it has not been posted. I too am receiving this error

**Comment by insufficient-funds** [comment]
sorry, i actually said that i didn't see this one listed elsewhere.  If it is somewhere, I'll gladly close this.

**Comment by unnieverse** [comment]
Don't worry about it :). The servers are overloaded right now.

#596 #597 #598 #601 #604

**Comment by insufficient-funds** [comment]
I assumed that would be partly the issue, however this started for me about 7 hours ago, and has happened pretty regularly since.

**Comment by unnieverse** [comment]
Servers have been flaky for me since last night on the actual app. I would just wait it out tbh :)

**Comment by SSminowjohnson** [comment]
Don't think it's the servers, plenty other bots working fine.

**Comment by insufficient-funds** [comment]
seems to be a 'global' issue with stuff using the pogo api's needing their requests throttled down to once every 3sec.
