### ISSUE TITLE
error msg keeps popping up, how to resolve:)

### ISSUE THREAD

**Issue by creepercon0826** [jabbink/PokemonGoBot#643]
**Description:**
[Short description of the issue observed. If this is feature request you can modify the template as required.]

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
walk around the map

**Actual behavior:**
_## **30 Jul 15:36:37: Error running loop WalkingLoop!
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:82)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:21)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
        ... 10 more**_

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
0.5.0

**Operating System:**
[Your operating system]

**Java version:**
[Full output of `java -version`]
30 Jul 15:36:37: Error running loop WalkingLoop!
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:82)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:21)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
        ... 10 more

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]

**Operating System:**
[Your operating system]

**Java version:**
[Full output of `java -version`]

**Comment by PancakeZik** [comment]
See #627

**Comment by creepercon0826** [comment]
thanks

**Comment by langerhans** [comment]
Duplicate, try latest version and next time use the search please...
