### ISSUE TITLE
install help

### ISSUE THREAD

**Issue by sitruc1234** [jabbink/PokemonGoBot#645]
**Description:**
I keep getting "access denied" when doing the java .jar part, maybe im doing something wrong.
can someone walk me through installing?

**Comment by Sieberkev** [comment]
When you want to start the JAR file from the command line, you first have to make sure you are working in the same folder as it `cd c:\PokemonGoBot\`

**Comment by sitruc1234** [comment]
ok, now it is saying "Error: Could not find or load main class .jar"

**Comment by sitruc1234** [comment]
I got it working but where do i get the login token?

**Comment by yashendra2797** [comment]
'token=' should be left as is (blank), Without it the app won't work. You need to fill in the password for your PTC or Google Account. If you're using 2FA, create an app password. You need to fill in either your password in plaintext (hunter2), or in base64. Plaintext is better from an ease of use point of view.

**Comment by sitruc1234** [comment]
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
	at ink.abb.pogo.scraper.Bot.start(Bot.kt:89)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:128)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
	... 5 more
any way to fix this?

**Comment by Sieberkev** [comment]
Not at this moment, that is a known issue #627
