### ISSUE TITLE
Help error

### ISSUE THREAD

**Issue by vinc05** [jabbink/PokemonGoBot#646]
**Description:**
       ... 10 more
30 Jul 11:15:06: Error running loop WalkingLoop!
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
        at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:92)
        at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:22)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.map.Map.getMa

**Operating System:**
Derbian 8

**Java version:**
8

all go only this mex every time why?

**Comment by Sieberkev** [comment]
This is a known issue #627

**Comment by vinc05** [comment]
yes ok i form italy , can you make low guide to fix please?

**Comment by alone23** [comment]
Read #627

**Comment by vinc05** [comment]
how i read on english? ._.

**Comment by vinc05** [comment]
i know only the bot have problem fixed by other update?

**Comment by langerhans** [comment]
Use the latest version.
