### ISSUE TITLE
No matter what here is the error I get

### ISSUE THREAD

**Issue by iamjonbradley** [jabbink/PokemonGoBot#647]
30 Jul 05:12:49: Error running loop WalkingLoop! 
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
	at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
	at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:82)
	at ink.abb.pogo.scraper.tasks.Walk$walk$1.invoke(Walk.kt:21)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
	... 10 more

**Comment by iamjonbradley** [comment]
I am using the latest release FYI

**Comment by Sieberkev** [comment]
This is a known issue #627

**Comment by iamjonbradley** [comment]
is this regarding the release jar? if ur talking about doing a git clone, i have a ton of issues I haven't posted. I have a server I use for both I can provide any developer access to if they can help

**Comment by Sieberkev** [comment]
It is an API throttling system Niantic has implemented on their servers to improve stability on their side. 

The developers of the JAVA API and this bot are working on getting it fixed, but it's a bunch harder than putting some Sleeps in here and there, so please be patient while they're on it.

**Comment by Jeraimee** [comment]
I use the Network Link Conditioner set to 3G and it resolves the issue for me.

**Comment by langerhans** [comment]
Fixed in alpha3, also duplicate issue galore ._.
