### ISSUE TITLE
Starting Problem (Contents of buffer are null) on Ubuntu 16.04

### ISSUE THREAD

**Issue by Shazgul** [jabbink/PokemonGoBot#653]
**Description:**
Everytime i start the Bot i become this Error: Contents of buffer are null

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
The Bot should normally Starts

**Actual behavior:**
The bot brings the Error

**Stacktrace (If it's a crash):**
30 Juli 19:21:39: Getting map of (censored, censored)
30 Juli 19:21:39: Getting initial pokestops...
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
	at ink.abb.pogo.scraper.Bot.start(Bot.kt:92)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:134)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
	... 5 more

**Version:**
Pokemon Go Bot v0.5.0 alpha 2

**Operating System:**
Ubuntu 16.04

**Java version:**
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195526.buildd.src)
OpenJDK Client VM (build 9-internal+0-2016-04-14-195526.buildd.src, mixed mode)

**Comment by langerhans** [comment]
Known, please check other issues before posting...
