### ISSUE TITLE
0.5.0a3: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by HoneyWheat** [jabbink/PokemonGoBot#663]
30 Jul 23:17:41: Looted pokestop "*removed*"; +50 XP: [1xITEM_GREAT_BALL, 1xITEM_SUPER_POTION, 1xITEM_POTION]
30 Jul 23:18:09: Error running loop BotLoop!
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at ink.abb.pogo.scraper.tasks.ReleasePokemon.run(ReleasePokemon.kt:63)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:183)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:122)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:32)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:145)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
30 Jul 23:18:10: Profile update: 852045 XP on LVL *removed*

**Comment by pashorizer** [comment]
This is going to be fixed with the next jar or you build from the latest PokemonGoBot `dev` and PokeGOAPI `Development`
