### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant POGOProtos.Enums.PokemonIdOuterClass.PokemonId.GYRADOS

### ISSUE THREAD

**Issue by alkalisdad** [jabbink/PokemonGoBot#676]
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant POGOProtos.Enums.PokemonIdOuterClass.PokemonId.GYRADOS
	at java.lang.Enum.valueOf(Enum.java:238)
	at POGOProtos.Enums.PokemonIdOuterClass$PokemonId.valueOf(PokemonIdOuterClass.java:14)
	at ink.abb.pogo.scraper.SettingsParser.createSettingsFromProperties(Settings.kt:92)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:85)

**Expected behavior:**
Log-In

**Actual behavior:**
Displays error

**Version:**
5.0.3

**Comment by olath888** [comment]
You misspelled Gyarados. Try correcting it - I suspect your issue will go away.
