### ISSUE TITLE
Error running loop WalkingLoop! 

### ISSUE THREAD

**Issue by panascy** [jabbink/PokemonGoBot#678]
after some time (10-20mins) of working.. then this happens:

31 Jul 09:13:04: Pausing to catch pokemon...
31 Jul 09:13:06: Getting map of (40.69678087197261, -73.32691041427412)
31 Jul 09:13:08: Pausing to catch pokemon...
31 Jul 09:13:11: Getting map of (40.69668862912372, -73.32693649236246)
31 Jul 09:13:12: Pausing to catch pokemon...
31 Jul 09:13:15: Error running loop WalkingLoop!
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
31 Jul 09:13:16: Error running loop WalkingLoop!
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
31 Jul 09:13:16: Getting map of (40.69669017238398, -73.32688458547919)
31 Jul 09:13:16: Error running loop BotLoop!
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
31 Jul 09:13:16: Error running loop WalkingLoop!
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
31 Jul 09:13:17: Error running loop WalkingLoop!
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
31 Jul 09:13:17: Failed to update profile and inventories
D/RequestHandler: Authenticated with static token
31 Jul 09:13:19: Pausing to catch pokemon...
31 Jul 09:13:21: Getting map of

Can you help me on this one?

**Comment by sphinxid** [comment]
Same with this => https://github.com/jabbink/PokemonGoBot/issues/680

**Comment by langerhans** [comment]
Clsoing in favor of #680
