### ISSUE TITLE
LoginFailedException Errors

### ISSUE THREAD

**Issue by Flat** [jabbink/PokemonGoBot#7]
After leaving the bot running for a while a LoginFailedException error occurs, and repeats itself with incrementing threads. The bot doesn't work after this error occurs. A restart of the application allows it to continue running for a while longer.

```
Exception in thread "Thread-377" com.pokegoapi.exceptions.LoginFailedException
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:88)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:166)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:143)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:89)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt:105)
	at ink.abb.pogo.scraper.MainKt$main$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Main.kt)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

```

**Comment by SwipeX** [comment]
This is from the API library 
> com.pokegoapi.api

**Comment by casper-gh** [comment]
Got same error with Google account, I can restart the app programmatically but how to bypass the google auth on google.com/device?
