### ISSUE TITLE
Amazon Ec2 - Seeing "Got a unexpected http code : 403"

### ISSUE THREAD

**Issue by vamirineni87** [jabbink/PokemonGoBot#712]
**Description:**
Seeing the following error when executing bot from Ec2. 
`[ec2-user@IP]$ java -jar pogo.scraper-all-0.5.0-alpha4.jar
01 Aug 02:35:08: Logging in to game server...
01 Aug 02:35:09: Logged in successfully
Getting profile data from pogo server.
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:196)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.lang.Thread.run(Thread.java:745)
`

**Steps to reproduce:**

1. [Running the bot on amazon linux on EC2 free tier]

**Stacktrace (If it's a crash):**
`D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:196)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.lang.Thread.run(Thread.java:745)
`

**Version:**
5.0 aplha 4

**Operating System:**
amazon linux

**Java version:**
`openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b13)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)
`

**Comment by Agronis** [comment]
Interesting.. 403.

Have you tried from any other VPS ?

Small but possible chance they're blocking EC2 instances.. Amazon only has so many [IP ranges](https://ip-ranges.amazonaws.com/ip-ranges.json).

**Comment by vamirineni87** [comment]
I havent tested on other VPS. Its working fine locally.

**Comment by aTadTasty** [comment]
supposedly niantic has started banning and blocking vps (ip address) from accessing their api

**Comment by langerhans** [comment]
Yes, tons of reports that AWS IP ranges got blocked by them. 403 most certainly means that. Nothing we can do. You need to switch your hoster. Other reports show that also DO got partly blocked.

**Comment by jabbink** [comment]
Can confirm. try an unknown datacenter. Or directly use Google Cloud.
