### ISSUE TITLE
Error running loop BotLoop!

### ISSUE THREAD

**Issue by Almdelui** [jabbink/PokemonGoBot#717]
**Description:**
I have found this error on my bot all time, from the start and it's very annoying because it's spamming the message all time. Plus I noticed that the efficiency of the bot came down with this, less Pokemon caught and fewer poke stops looted.

**Stacktrace (If it's a crash):**
01 ago 09:55:28: Error running loop BotLoop! 
java.lang.IllegalArgumentException: You cannont remove more quantity than you have
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:75)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:201)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:125)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:34)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)

**Version:**
0.5.0 Alpha 4

**Operating System:**
Mac Os X El Capitan 10.11.5

**Java version:**
Java 8

**Comment by thegimliboy** [comment]
Same here.

**Comment by Cypherke** [comment]
what are your item_ settings in your config?

**Comment by Almdelui** [comment]
Fixed, changing the item_settings, thanks Cypherke ;)

**Comment by ColeB27** [comment]
still have this problem, what did you change @Almdelui

**Comment by jabbink** [comment]
Possibly values other than `-1` or integers of `0` and higher.
