### ISSUE TITLE
"Error running loop BotLoop!" - "Error  in API Url"

### ISSUE THREAD

**Issue by thegimliboy** [jabbink/PokemonGoBot#720]
If I start the bot it works very well for like an hour. But the I get this message and it won't stop.

```
01 Aug 11:27:56: Getting map of (52.52863104056791, 13.467353387957665)
D/RequestHandler: Authenticated with static token
01 Aug 11:28:01: Failed to update profile and inventories
D/RequestHandler: Authenticated with static token
01 Aug 11:28:01: Error running loop ProfileLoop!
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.lang.Thread.run(Thread.java:745)
01 Aug 11:28:01: Getting map of (52.52854901638909, 13.467414334137823)
D/RequestHandler: Authenticated with static token
01 Aug 11:28:02: Error running loop BotLoop!
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.lang.Thread.run(Thread.java:745)
01 Aug 11:28:06: Getting map of (52.5284412503666, 13.46743982192904)
D/RequestHandler: Authenticated with static token
01 Aug 11:28:07: Error running loop BotLoop!
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.lang.Thread.run(Thread.java:745)
01 Aug 11:28:11: Getting map of (52.52834102963154, 13.46740194994802)
D/RequestHandler: Authenticated with static token
01 Aug 11:28:12: Error running loop BotLoop!
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.lang.Thread.run(Thread.java:745)
```

Please, help me. (Btw. this bot is awesome, my respect for the developer)

**Comment by Sieberkev** [comment]
This is an issue in the external Java API: https://github.com/Grover-c13/PokeGOAPI-Java/issues/417

**Comment by ursalame** [comment]
Here's a little bash script that can help you:

```
#!/bin/bash
EXPR="java -jar pogo.scraper-all-0.5.0-alpha4.jar &"; 
WAIT_BEFORE_KILLING=50m;
WAIT_AFTER_KILL_TO_FORCE_KILL=30s;
WAIT_BEFORE_LOOPING=1m;

while true
do
	eval $EXPR;
	PID=$!;
	
	sleep $WAIT_BEFORE_KILLING;
	kill $PID;

	sleep $WAIT_AFTER_KILL_TO_FORCE_KILL;
	kill -9 $PID;
	
	sleep $WAIT_BEFORE_LOOPING;		
done
```

**Comment by Creuqe** [comment]
May i know how can i use that script(or a similar) on windows? @ursalame

**Comment by thegimliboy** [comment]
@Creuqe https://github.com/jabbink/PokemonGoBot/issues/716#issuecomment-236863730

**Comment by thegimliboy** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/pull/442 I'll close this for now ^^

**Comment by thegimliboy** [comment]
Even with the new changes in API and Bot it doesn't work (for me).

**Comment by jabbink** [comment]
Logging in and keeping the token alive is the responsibility of the API. I was told this was fixed now so I'm closing this.
