### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by tuccy** [jabbink/PokemonGoBot#733]
**Description:**
Runtime Exception 
I think that reasson try to realease pokemon over self  PokemontsCounts Iteration, after Running loop BotLoop

Little temporaly fix on ReleasePokemon.kt awaiting the project brains to take the best way to solve

Red addeded code, yellow moved.

![runtimeexception](https://cloud.githubusercontent.com/assets/6490876/17300311/0b9c1a6e-5812-11e6-9c3d-6ffc828cf2c0.png)

maybe must add break statment inside catch to avoid full iteration, at the moment i can't reproduce it again.

Sorry for my English is really low

In addition someone can document a little guide with the correct way to participate on dev project?
thanks.

**Comment by sureshg** [comment]
I am getting this for `transferPokemon`

```kotlin
01 Aug 17:49:24: Going to transfer EKANS with CP 50 and IV 37%; reason: CP < 400 and IV < 80%
01 Aug 17:49:25: Error running loop BotLoop!
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at com.annimon.stream.LazyIterator.next(LazyIterator.java:30)
        at com.annimon.stream.Stream$10.nextIteration(Stream.java:519)
        at com.annimon.stream.Stream$10.hasNext(Stream.java:499)
        at com.annimon.stream.Stream.collect(Stream.java:1232)
        at com.pokegoapi.api.inventory.PokeBank.addPokemon(PokeBank.java:56)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:128)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
        at com.pokegoapi.api.pokemon.Pokemon.transferPokemon(Pokemon.java:106)
        at ink.abb.pogo.scraper.tasks.ReleasePokemon.run(ReleasePokemon.kt:46)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:201)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:127)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:34)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)```

**Comment by devinsba** [comment]
its an API bug:

```
at com.pokegoapi.api.inventory.PokeBank.addPokemon(PokeBank.java:56)
```

**Comment by jabbink** [comment]
^
