### ISSUE TITLE
Thread-4 Adress already used?

### ISSUE THREAD

**Issue by Shazgul** [jabbink/PokemonGoBot#749]
**Description:**
The Bot seems to run totally normally but i became this Error at starting the Bot again:

Exception in thread "Thread-4" java.net.BindException: Die Adresse wird bereits verwendet
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:100)
	at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
	at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
	at ink.abb.pogo.scraper.gui.WebServer$start$1.run(WebServer.kt:27)
	at java.lang.Thread.run(Thread.java:745)

Also when i try to stop the bot with CTRL + C i have to forceclose the Terminal, it doenst stop it in the terminal anymore. 

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
Bot should close.

**Actual behavior:**
Bot stucks at Socket Server stopped.

**Version:**
Alpha 4

**Operating System:**
Ubuntu 16.04.

**Java version:**
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK Server VM (build 25.91-b14, mixed mode)

**Comment by citruz** [comment]
I can confirm the "Address already in use" error. When I stop the bot using ctrl-c it logs "Stopped socketserver" and the program stops correctly, but as soon as I start it again I get "Address already in use". Have to wait 30-60sec until it works again.

**Comment by fabioneves** [comment]
Yup, I can confirm that too.

**Comment by yumao5** [comment]
Clean your ps and follow suggestion above. You will be fine.

**Comment by qifbox** [comment]
To stop the bot and run it again, on windows, i just open the Task Manager and close de 2 java running. the console will stay open and u can run the bot again.

**Comment by jabbink** [comment]
Fix is to indeed wait for it to fully close and make sure java really isn't running. Then start the bot again.

Also the current `develop` branch allows starting and stopping bots directly via a HTTP call.

**Comment by conradsze** [comment]
How do I make sure java really isn't running in the background, do i have to restart my Macbook everytime. And what is the correct way to stop the bot? (ctrl-C ? )

**Comment by jabbink** [comment]
Ctrl+c and wait for a few seconds. It will tell you when it's done (max 5 secs)
