### ISSUE TITLE
Still getting "LoginFailedException"

### ISSUE THREAD

**Issue by EpicAwesomeWolf** [jabbink/PokemonGoBot#76]
D/RequestHandler: Authenticated with static token
Exception in thread "Thread-1242" com.pokegoapi.exceptions.LoginFailedException
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:133)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:238)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:173)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:163)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:96)
	at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:20)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:64)
	at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Bot.kt:54)
	at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$1.invoke(Bot.kt:18)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

Fix??

**Comment by aTadTasty** [comment]
maybe your token expired. have you tried the the `token= `as empty and nothing.

i had an error when it was set on mine as `token==` which i then fixed by using `token=`

**Comment by EpicAwesomeWolf** [comment]
oh. thanks 👍

**Comment by Mewks** [comment]
I'm also still getting this error regardless of what I do. It sucks because I would like to leave it running for hours and hours, right now it can only run for about 30mins.

**Comment by jabbink** [comment]
Only PTC accounts work without getting kicked out atm, the Google login issue has to do with the Java API and won't be fixed in this repo
