### ISSUE TITLE
[Help] NullPointerException after login

### ISSUE THREAD

**Issue by Doomki** [jabbink/PokemonGoBot#778]
When running with `./gradlew run`, everything works initially, but then the following occurs:

> 03 Aug 13:55:20 (default): Logging in to game server...
03 Aug 13:55:21 (default): Logged in successfully
Getting profile data from pogo server.
Exception in thread "default" java.lang.NullPointerException
        at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

and the build is stuck at 83%. I built the project from source.

**Comment by jabbink** [comment]
Weird line number.

Also please don't remove the issue template. You removed the most essential information.........

**Comment by Doomki** [comment]
Ok sorry, this is extremely embarassing.
I hadn't actually used this Google account to play P GO yet, so there was no existing account.
