### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by InletWindow** [jabbink/PokemonGoBot#794]
Hi -- just recently found your bot.  Thanks so much for making!  i am having issues getting it up and running though.  I followed instructions from THIS youtube video -- https://www.youtube.com/watch?v=E5rsLlhpZL8

I did all the steps, as far as I know.  I think I installed the java thing I needed.  But I get this error message:
03 Aug 15:19:06: Set Timer to return the first Pokestop (minutes) setting ("timerWalkToStartPokeStop") not specified, defaulting to "-1". 
03 Aug 15:19:06: Port where the webserver should listen setting ("gui_port") not specified, defaulting to "8000". 
03 Aug 15:19:06: Logging in to game server...
03 Aug 15:19:07: Logged in successfully
Getting profile data from pogo server.
D/RequestHandler: Authenticated with static token
Exception in thread "main" java.lang.NullPointerException
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:42)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:145)

I have very little to no coding/java experience.  I had thought I did everything right.  Anything you could suggest that I try?

If you look at the comments for that youtube video, a whole bunch of people are having the exact same issue.

I searched around this site and around the internet for a long while and could find no solution before posting this.

**Comment by InletWindow** [comment]
I'm on a mac and I updated to the latest operating system to see if that might help... it didn't

**Comment by pashorizer** [comment]
Follow the read me on this github.

**Comment by Silver331** [comment]
Hey, i had the same Error, u need to login to your account first on phone or pc and choose a pokemon and a name, then u can use the Bot

**Comment by InletWindow** [comment]
Silver331 -- thanks so much!  It very briefly worked after I first logged into the account and picked a name and starter.  It caught an Ekans.  I thought wow this is cool!  Then it kept saying 0 pokestops found.  I waited a little tried again.

Now I get new error messages.


03 Aug 16:11:28: Logging in to game server...
03 Aug 16:11:41: Logged in successfully
Getting profile data from pogo server.
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
	at java.lang.Thread.run(Thread.java:745)

did I get temp banned or something or what happened?  My coordinates were for less than a mile away.

**Comment by jabbink** [comment]
Do you have `token=some-characters-here` in your config?

**Comment by InletWindow** [comment]
there are no characters next to token=

Here is how it appears, with the coordinates I put in:
# Token to login directly
token=
latitude=33.781944
longitude=-84.372870

**Comment by edwincheung555** [comment]
for me, it logs in but i get 0 pokestops even though Pier 39 in San Francisco has 35+ pokestops and all it says is retrying in 10 seconds

**Comment by jabbink** [comment]
Servers are broken right now. Just wait.
