### ISSUE TITLE
Contents of buffer are null

### ISSUE THREAD

**Issue by Peyphour** [jabbink/PokemonGoBot#795]
**Description:**
When launching the bot I get this

**Steps to reproduce:**

1. Launch the bot

**Expected behavior:**
Bot should connect to PoGO server
**Actual behavior:**
PoGO return an invalid response (I guess)

**Stacktrace (If it's a crash):**
Getting profile data from pogo server.
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
        at com.pokegoapi.api.inventory.Inventories.<init>(Inventories.java:74)
        at com.pokegoapi.api.PokemonGo.getInventories(PokemonGo.java:130)
        at com.pokegoapi.api.player.PlayerProfile.getStats(PlayerProfile.java:304)
        at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 12 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        ... 14 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:292)
        at java.lang.Thread.run(Thread.java:745)

**Version:**
Last version (pulled and builded the repo before re-testing)
**Operating System:**
Debian 7
**Java version:**
`java version "1.8.0_101"`

**Comment by prestonvanloon** [comment]
+1

**Comment by BartWillems** [comment]
+1 same error
Running Ubuntu 16.04.1
`java version "1.8.0_101"`

**Comment by Shuntor** [comment]
Same here

**Comment by pashorizer** [comment]
......
http://ispokemongodownornot.com/

**Comment by Peyphour** [comment]
^ Tells us that it is not down

**Comment by husbeard** [comment]
Lol, no wonder. it's down..

**Comment by Shazgul** [comment]
Okay now i'm becoming:

Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
	at java.lang.Thread.run(Thread.java:745)

**Comment by edwincheung555** [comment]
same here
if any of yours start working, update us

**Comment by Peyphour** [comment]
![image](https://cloud.githubusercontent.com/assets/12598033/17380349/1044a2dc-59c7-11e6-9fe1-a36f9c2fbb41.png)

**Comment by pashorizer** [comment]
@Peyphour Yeah, only that there is a huge big red flagged "CRIT" on login.

**Comment by Peyphour** [comment]
I can connect with the Android app

**Comment by etkstim** [comment]
Some issue for me

**Comment by Peyphour** [comment]
Oh and I use Google and not PTC

**Comment by mojin7** [comment]
Same here. App is fine. Exception in thread "Main" when running the bot. Windows 7. Java 1.8 101. Alpha 4

**Comment by dwfz** [comment]
+1

**Comment by Peyphour** [comment]
Google login seems down as well

**Comment by ke11** [comment]
+1

**Comment by KEESSTARR** [comment]
Mine is not working for PTC or Google login

**Comment by Peyphour** [comment]
So it seems to be an issue with PoGO servers only, we just have to wait (and I used a lucky egg :cry:)

**Comment by Peyphour** [comment]
I can now login, but the bot cannot retrieve pokestops

**Comment by jabbink** [comment]
@Peyphour stop lying. The site says it's down

![image](https://cloud.githubusercontent.com/assets/2461972/17380676/986abdda-59c8-11e6-9d5e-9a001bee5d52.png)
