### ISSUE TITLE
Contents of buffer are null - started 15 minutes ago

### ISSUE THREAD

**Issue by husbeard** [jabbink/PokemonGoBot#796]
**Description:**
When logging into the game file we get the following error;
03 Aug 13:01:36: Logging in to game server...
03 Aug 13:01:37: Logged in successfully
Getting profile data from pogo server.
D/RequestHandler: Authenticated with static token
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: Contents of buffer are null
        at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:119)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:154)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
        at com.pokegoapi.api.inventory.Inventories.<init>(Inventories.java:74)
        at com.pokegoapi.api.PokemonGo.getInventories(PokemonGo.java:135)
        at com.pokegoapi.api.player.PlayerProfile.getStats(PlayerProfile.java:304)
        at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:42)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:145)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:292)
        at java.lang.Thread.run(Unknown Source)

**Steps to reproduce:**

1. [Step 1] Open the command prompt
2. [Step 2] Run the java command

**Expected behavior:**
Contents of buffer are null

**Actual behavior:**
Contents of buffer are null

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
alpha 4

**Operating System:**
Windows 10 64

**Java version:**
(build 1.8.0_101-b13)

**Comment by Sieberkev** [comment]
Loginservers down atm

**Comment by husbeard** [comment]
Yes, Just saw that. Thanks. How do I close this?
