### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException: empty String

### ISSUE THREAD

**Issue by ElGecko76** [jabbink/PokemonGoBot#80]
Hello,

I downloaded the jar file and saved the config.properties file next to the jar file, and I have this error : 

$ java -jar pogo.scraper-all-0.3.0.jar
Exception in thread "main" java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at ink.abb.pogo.scraper.Settings$startingLatitude$1.invoke(Settings.kt:37)
	at ink.abb.pogo.scraper.Settings$startingLatitude$1.invoke(Settings.kt:16)
	at ink.abb.pogo.scraper.Settings.getPropertyOrDie(Settings.kt:69)
	at ink.abb.pogo.scraper.Settings.<init>(Settings.kt:37)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:68)

Can you help me please ?
Thanks in advance

**Comment by ElGecko76** [comment]
![capture d ecran_2016-07-22_19-44-49](https://cloud.githubusercontent.com/assets/19478137/17065928/c528c91c-5044-11e6-9a08-938667217057.png)

**Comment by CameronBanga** [comment]
Check lines 8 and 9 of your config.properties. You probably didn't set a latt/long. Those values are null, so it crashes. Try adding a latt/long, and it should work. In a format like this:

```
latitude=41.467305
longitude=-87.061951
```

**Comment by ElGecko76** [comment]
Thanks ! :D
