### ISSUE TITLE
Application failed to start with classpath

### ISSUE THREAD

**Issue by zhoushifeng8** [jabbink/PokemonGoBot#806]
Cannot run the bot....

**Comment by zhoushifeng8** [comment]
2016-08-07 23:36:08.617  INFO 5444 --- [           main] .b.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: [jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/PokeGOAPI-Java-ef1f52f1f0621f94b97125975c961a8ad8129e92.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/kotlin-stdlib-1.0.3.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/netty-socketio-1.7.7.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-boot-starter-1.3.6.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-boot-starter-web-1.3.6.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-boot-starter-undertow-1.3.6.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/jackson-databind-2.8.0.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/jackson-core-2.8.0.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/jackson-annotations-2.8.0.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/jackson-module-kotlin-2.8.0.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/gpsoauth-0.3.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/okio-1.9.0.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/moshi-1.2.0.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/stream-1.1.1.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/okhttp-3.4.1.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/protobuf-java-3.0.0-beta-3.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/rxjava-1.1.8.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/lz4-1.3.0.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/kotlin-runtime-1.0.3.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/netty-buffer-4.0.25.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/netty-common-4.0.25.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/netty-transport-4.0.25.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/netty-handler-4.0.25.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/netty-codec-http-4.0.25.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/netty-codec-4.0.25.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/netty-transport-native-epoll-4.0.25.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/slf4j-api-1.7.21.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-boot-1.3.6.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-boot-autoconfigure-1.3.6.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-boot-starter-logging-1.3.6.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-core-4.2.7.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/snakeyaml-1.16.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-boot-starter-validation-1.3.6.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-web-4.2.7.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-webmvc-4.2.7.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/undertow-core-1.3.23.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/undertow-servlet-1.3.23.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/undertow-websockets-jsr-1.3.23.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/javax.servlet-api-3.1.0.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/javax.el-3.0.0.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/kotlin-reflect-1.0.3.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/base64-2.3.9.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-context-4.2.7.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/logback-classic-1.1.7.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/jcl-over-slf4j-1.7.21.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/jul-to-slf4j-1.7.21.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/log4j-over-slf4j-1.7.21.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/tomcat-embed-el-8.0.36.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/hibernate-validator-5.2.4.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-aop-4.2.7.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-beans-4.2.7.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/spring-expression-4.2.7.RELEASE.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/jboss-logging-3.3.0.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/xnio-api-3.3.6.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/xnio-nio-3.3.6.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/jboss-annotations-api_1.2_spec-1.0.0.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/jboss-websocket-api_1.1_spec-1.1.0.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/logback-core-1.1.7.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/validation-api-1.1.0.Final.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/classmate-1.1.0.jar!/, jar:file:/Users/zhoushifeng/Desktop/pokemon%20go/PokemonGoBot-0.5.0.jar!/lib/aopalliance-1.0.jar!/]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 3 more
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:71)
	... 8 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:142)
	... 19 more

**Comment by zhoushifeng8** [comment]
2016-08-07 23:36:06.464  INFO 5444 --- [           main] ink.abb.pogo.scraper.MainKt              : Starting MainKt on zhoudeiMac.local with PID 5444 (/Users/zhoushifeng/Desktop/pokemon go/PokemonGoBot-0.5.0.jar started by zhoushifeng in /Users/zhoushifeng/Desktop/pokemon go)
2016-08-07 23:36:06.469  INFO 5444 --- [           main] ink.abb.pogo.scraper.MainKt              : No active profile set, falling back to default profiles: default
2016-08-07 23:36:06.521  INFO 5444 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@6e5e91e4: startup date [Sun Aug 07 23:36:06 SGT 2016]; root of context hierarchy
2016-08-07 23:36:07.451  INFO 5444 --- [           main] org.xnio                                 : XNIO version 3.3.6.Final
2016-08-07 23:36:07.478  INFO 5444 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.6.Final
2016-08-07 23:36:07.628  WARN 5444 --- [           main] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2016-08-07 23:36:07.628  WARN 5444 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2016-08-07 23:36:07.643  INFO 5444 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2016-08-07 23:36:07.644  INFO 5444 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1125 ms
2016-08-07 23:36:07.839  INFO 5444 --- [           main] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2016-08-07 23:36:07.843  INFO 5444 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2016-08-07 23:36:07.843  INFO 5444 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2016-08-07 23:36:07.844  INFO 5444 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2016-08-07 23:36:07.844  INFO 5444 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
2016-08-07 23:36:08.229  INFO 5444 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@6e5e91e4: startup date [Sun Aug 07 23:36:06 SGT 2016]; root of context hierarchy
2016-08-07 23:36:08.335  INFO 5444 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/start]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.startBot(java.lang.String)
2016-08-07 23:36:08.336  INFO 5444 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bots]}" onto public final java.util.List<ink.abb.pogo.scraper.Settings> ink.abb.pogo.scraper.controllers.BotController.bots()
2016-08-07 23:36:08.336  INFO 5444 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/load]}" onto public final void ink.abb.pogo.scraper.controllers.BotController.loadBot(java.lang.String)
2016-08-07 23:36:08.336  INFO 5444 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/unload]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.unloadBot(java.lang.String)
2016-08-07 23:36:08.338  INFO 5444 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/reload]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.reloadBot(java.lang.String)
2016-08-07 23:36:08.338  INFO 5444 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/stop]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.stopBot(java.lang.String)
2016-08-07 23:36:08.341  INFO 5444 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2016-08-07 23:36:08.341  INFO 5444 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2016-08-07 23:36:08.398  INFO 5444 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-07 23:36:08.398  INFO 5444 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-07 23:36:08.429  INFO 5444 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-07 23:36:08.536  INFO 5444 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-08-07 23:36:08.605 ERROR 5444 --- [           main] o.s.boot.SpringApplication               : Application startup failed

**Comment by husbeard** [comment]
I've got a similar issue:



java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
        ... 3 more
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
        at io.undertow.Undertow.start(Undertow.java:186)
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:71)
        ... 8 more
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
        at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
        at io.undertow.Undertow.start(Undertow.java:142)
        ... 19 more

**Comment by jabbink** [comment]
Ah, address already in use:

You apparently use port 8080 already on your computer.

Start the bot like this: `java -jar PokemonGoBot-0.5.0.jar --server.port=8090`

**Comment by zhoushifeng8** [comment]
wah, thank you Jabbink, it works, thank you

**Comment by smileytechguy** [comment]
@jabbink why is this needed?  Wouldn't the 2 ports in config.properties overide?

**Comment by Casual-User** [comment]
Thank you, was also surprised, the config.properties ports wouldn't suffice anymore.
