### ISSUE TITLE
HTTP Code 403

### ISSUE THREAD

**Issue by Venome** [jabbink/PokemonGoBot#807]
**Description:**
not working

**Steps to reproduce:**

1. java -jar PokemonGoBot-0.5.0.jar

**Stacktrace (If it's a crash):**
```
07 Aug 22:50:00 (config-properties-conversion): Logged in successfully
Getting profile data from pogo server.
D/RequestHandler: Authenticated with static token
Exception in thread "config-properties-conversion" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred.
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
	at com.pokegoapi.api.inventory.Inventories.<init>(Inventories.java:74)
	at com.pokegoapi.api.PokemonGo.getInventories(PokemonGo.java:138)
	at com.pokegoapi.api.player.PlayerProfile.getStats(PlayerProfile.java:304)
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
	at ink.abb.pogo.scraper.MainKt.startBot$default(Main.kt:89)
	at ink.abb.pogo.scraper.services.BotService.submitBot(BotService.kt:39)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:62)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 13 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 15 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:197)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
	at java.lang.Thread.run(Thread.java:745)
```

**Version:**
0.5.0

**Operating System:**
OSX

**Java version:**
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by staurakis** [comment]
Maybe something wrong with your config file? The log file shows the program starts correctly and then it shows this: Exception in thread "config-properties-conversion" .
I think there is something wrong (an wrong value in a variable) in the config file.
Can you find the original one that you had to rename and start from that?

**Comment by staurakis** [comment]
[Here](https://github.com/jabbink/PokemonGoBot/blob/develop/config.properties.template) you can find the original config file. Rename it to config.properties, put the correct credentials and starting positions plus anything else you would like to change and try again.
