### ISSUE TITLE
Errors with Google Login

### ISSUE THREAD

**Issue by CLGitDev** [jabbink/PokemonGoBot#830]
Hi team,

First of all, thanks for your effort in updating the bot with the latest API. It is working perfectly for me except I'm getting erros with Google login after awhile.

I notice from the wiki page that there is a known issue with the Java API that handles Google login, and it is expected to see errors after 1.5 hours. I think I'm facing the exact issue at the moment. This had never happened to me when I was using v0.4.3 though.

May I know if there is any change regarding to this area? Or I was just lucky before? Is it possible to make a quick fix around this, say auto re-login on error, or maybe hardcode an one hour timer?

Thanks in advance for your help!

**Comment by pashorizer** [comment]
There are some scripts floating around which essentially restarts the bot. There is no current solution for that issue tho.

**Comment by CLGitDev** [comment]
@pashorizer Thanks for the pointer. I have no problem scheduling a cron job for this but I'm more curious on why it seemed to be working for me in v0.4.3.

I don't have the log with me anymore, but I vaguely remember I saw the line "Authenticate with static token" came up periodically, not only when I first kickoff the bot. Maybe there were some sort of retry mechanism before?

**Comment by pashorizer** [comment]
There is actually a refresh token functionality. But it doesn't work reliable.

**Comment by timchen100** [comment]
```
08 Aug 12:04:55 (default): Logging in to game server...
08 Aug 12:04:57 (default): Logged in successfully
Getting profile data from pogo server.
Exception in thread "default" java.lang.UnsupportedClassVersionError: com/google/common/util/concurrent/AtomicDouble : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

```

**Comment by pashorizer** [comment]
@timchen100 This does not belong to this issue. Besides that it seems like you have not the correct java version.

**Comment by timchen100** [comment]
Oh. Sorry, I thought it would be an issue with with Google Login.

**Comment by Rofii** [comment]
@pashorizer Do you know of a way to script automatic opening and restarting with Windows?

**Comment by Mixone-FinallyHere** [comment]
@Rofii id suggest a mix of kill start and pause in a batch file
