### ISSUE TITLE
HELP!! "Adress already in use"

### ISSUE THREAD

**Issue by lBeher** [jabbink/PokemonGoBot#839]
Hi there. I cant use the bot since 12 hours ago. I have MAC and thats what it says:

2016-08-08 13:06:01.739 ERROR 6202 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.RuntimeException: java.net.BindException: **Address already in use**
	at io.undertow.Undertow.start(Undertow.java:186) ~[undertow-core-1.3.23.Final.jar!/:1.3.23.Final]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]

**Comment by jabbink** [comment]
Are you running multiple bots?

**Comment by lBeher** [comment]
Nope. Yesterday just close the bot and when I was going to open it again, BUM! error. I've tried to download again, create a new config.properties but always same error. Dont know what to do..

**Comment by Peyphour** [comment]
Check if you have any Java process running

**Comment by lBeher** [comment]
No.. I have check it on terminal and I dont have any java process runing. I dont know what to do but Ive try all. Also I have restarted my MAC but same problem lol

**Comment by philippjess** [comment]
Did you shut down the bot correctly so that the port got unbound? Take a look at all open ports with iptables or use another port.

**Comment by philippjess** [comment]
try killall java

**Comment by lBeher** [comment]
Ok perfects, thanks to all! Just needed to kill the java procces open!

**Comment by etkstim** [comment]
I have another problem.
When start application if port 8080 are busy, i have same error but i haven't possibility to config other port to start boot. is it right?

**Comment by Peyphour** [comment]
https://github.com/jabbink/PokemonGoBot/issues/806#issuecomment-238089960

**Comment by jabbink** [comment]
`java -jar PokemonGoBot-0.5.0.jar --spring.main.web-environment=false`
