### ISSUE TITLE
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 

### ISSUE THREAD

**Issue by KyleBoyer** [jabbink/PokemonGoBot#850]
Stack trace:

08 Aug 10:16:07 (default: BotLoop): Using ITEM_GREAT_BALL; Using curve; achieved catch probability: 0.5625143, desired: 0.8 
08 Aug 10:16:08 (default: BotLoop): Using ITEM_GREAT_BALL; Using Razz Berry; Using curve; achieved catch probability: 0.5625143, desired: 0.8 
08 Aug 10:16:08 (default: BotLoop): Error running loop BotLoop! 
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:698)
        at ink.abb.pogo.scraper.util.pokemon.CatchablePokemonKt.catch(CatchablePokemon.kt:27)
        at ink.abb.pogo.scraper.util.pokemon.CatchablePokemonKt.catch(CatchablePokemon.kt:115)
        at ink.abb.pogo.scraper.util.pokemon.CatchablePokemonKt.catch(CatchablePokemon.kt:42)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:64)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:124)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:169)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 11 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
        at rx.Observable.unsafeSubscribe(Observable.java:9861)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        ... 13 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Mixone-FinallyHere** [comment]
Looking at the probabilities, since they are so low, and has used already great ball, razz berry and curve, maybe it tried to use an ultra ball without checking if there was one in inventory? (hence the empty buffer maybe? )

**Comment by tristo7** [comment]
I get this every time it tries to run "profile_update_timer"

**Comment by Sieberkev** [comment]
`InvalidProtocolBufferException: Contents of buffer are null` will hopefully be fixed once and for all with the new API implementation very soon.
