### ISSUE TITLE
403 when connecting

### ISSUE THREAD

**Issue by didierva** [jabbink/PokemonGoBot#852]
**Description:**
Getting a 403

Getting profile data from pogo server.
D/RequestHandler: Authenticated with static token
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
	at com.pokegoapi.api.inventory.Inventories.<init>(Inventories.java:74)
	at com.pokegoapi.api.PokemonGo.getInventories(PokemonGo.java:138)
	at com.pokegoapi.api.player.PlayerProfile.getStats(PlayerProfile.java:304)
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 12 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 14 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:197)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
	at java.lang.Thread.run(Thread.java:745)

**Comment by BartWillems** [comment]
I've got the same issue.
 @CosmoRing , what you linked is another error, This one fails with a 403 exception.

`Getting profile data from pogo server.
D/RequestHandler: Authenticated with static token
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
        at com.pokegoapi.api.inventory.Inventories.<init>(Inventories.java:74)
        at com.pokegoapi.api.PokemonGo.getInventories(PokemonGo.java:138)
        at com.pokegoapi.api.player.PlayerProfile.getStats(PlayerProfile.java:304)
        at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 12 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        ... 14 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:197)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
        at java.lang.Thread.run(Thread.java:745)`

**Comment by SerCrAsH** [comment]
Same in my vps ... but it works in my local pc

**Comment by Venome** [comment]
when i use VPN i got 403 too
i think it's related with token code

**Comment by langerhans** [comment]
403 is most likely an IP ban. That is why it doesn't work on VPS for you but maybe at home. Switch your VPS provvider or run the bot at home. Not really a bot issue.
