### ISSUE TITLE
Worked once, now failing. Any advice appreciated!

### ISSUE THREAD

**Issue by kjp87** [jabbink/PokemonGoBot#859]
Hi there, I've successfully ran the Bot once and now it fails to run again, -any help is appreciated.
The files are set EXACTLY as shown in the guide, -both the config.properties and the bot .jar file are sat in the same folder named "Main". I have tried the obvious steps of rebooting/deleting & re-downloading. The config file is definitely not saved as .txt, but the bot seems to be unable to find the file. Starting to pull my hair out now! Thank you for whoever can shed light on this!

Here is a far as the bot gets:

Last login: Mon Aug  8 19:22:23 on ttys000
Kaels-MBP:~ kaelplace$ CD /Users/kaelplace/Desktop/main 
Kaels-MBP:~ kaelplace$ java -jar /Users/kaelplace/Desktop/main/PokemonGoBot-0.5.0.jar 

2016-08-08 19:28:56.000  INFO 1158 --- [           main] ink.abb.pogo.scraper.MainKt              : Starting MainKt on Kaels-MBP.home with PID 1158 (/Users/kaelplace/Desktop/main/PokemonGoBot-0.5.0.jar started by kaelplace in /Users/kaelplace)
2016-08-08 19:28:56.009  INFO 1158 --- [           main] ink.abb.pogo.scraper.MainKt              : No active profile set, falling back to default profiles: default
2016-08-08 19:28:56.108  INFO 1158 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@446cdf90: startup date [Mon Aug 08 19:28:56 BST 2016]; root of context hierarchy
2016-08-08 19:28:57.689  INFO 1158 --- [           main] org.xnio                                 : XNIO version 3.3.6.Final
2016-08-08 19:28:57.722  INFO 1158 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.6.Final
2016-08-08 19:28:57.917  WARN 1158 --- [           main] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2016-08-08 19:28:57.917  WARN 1158 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2016-08-08 19:28:57.938  INFO 1158 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2016-08-08 19:28:57.939  INFO 1158 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1836 ms
2016-08-08 19:28:58.269  INFO 1158 --- [           main] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2016-08-08 19:28:58.276  INFO 1158 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2016-08-08 19:28:58.277  INFO 1158 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2016-08-08 19:28:58.278  INFO 1158 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2016-08-08 19:28:58.278  INFO 1158 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
2016-08-08 19:28:58.842  INFO 1158 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@446cdf90: startup date [Mon Aug 08 19:28:56 BST 2016]; root of context hierarchy
2016-08-08 19:28:58.927  INFO 1158 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/start]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.startBot(java.lang.String)
2016-08-08 19:28:58.929  INFO 1158 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bots]}" onto public final java.util.List<ink.abb.pogo.scraper.Settings> ink.abb.pogo.scraper.controllers.BotController.bots()
2016-08-08 19:28:58.929  INFO 1158 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/stop]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.stopBot(java.lang.String)
2016-08-08 19:28:58.929  INFO 1158 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/load]}" onto public final void ink.abb.pogo.scraper.controllers.BotController.loadBot(java.lang.String)
2016-08-08 19:28:58.929  INFO 1158 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/unload]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.unloadBot(java.lang.String)
2016-08-08 19:28:58.929  INFO 1158 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/reload]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.reloadBot(java.lang.String)
2016-08-08 19:28:58.934  INFO 1158 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2016-08-08 19:28:58.934  INFO 1158 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2016-08-08 19:28:58.985  INFO 1158 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 19:28:58.987  INFO 1158 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 19:28:59.056  INFO 1158 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 19:28:59.172  INFO 1158 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-08-08 19:28:59.246  INFO 1158 --- [           main] b.c.e.u.UndertowEmbeddedServletContainer : Undertow started on port(s) 8080 (http)
Exception in thread "default" java.io.FileNotFoundException: config.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:77)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
2016-08-08 19:28:59.253  INFO 1158 --- [           main] ink.abb.pogo.scraper.MainKt              : Started MainKt in 3.745 seconds (JVM running for 4.296)

...and then sits there with no chance to the above :(

**Comment by toffaste1337** [comment]
It doesnt find your config.properties file. Make sure it doesnt have the `.template` extension as well.

**Comment by Sieberkev** [comment]
> Kaels-MBP:~ kaelplace$ CD /Users/kaelplace/Desktop/main 
Kaels-MBP:~ kaelplace$ java -jar /Users/kaelplace/Desktop/main/PokemonGoBot-0.5.0.jar

If your current directory is already correct, just do `java -jar PokemonGoBot-0.5.0.jar` with no directory information in it.

**Comment by kjp87** [comment]
<img width="822" alt="screen shot 2016-08-08 at 19 41 56" src="https://cloud.githubusercontent.com/assets/20911706/17491616/46ba2f62-5da0-11e6-8ded-db34c42641dd.png">
toffaste1337 Its exactly as shown in the guide mate, thank you for trying though!
Sieberkev Ill try that now, cheers bud!

**Comment by kjp87** [comment]
Sieberkev - Same ending, didn't work. Thanks anyway bud!
Any other suggestions?

**Comment by Danman00** [comment]
If you created the file with textedit i would recommend to use nano from terminal so you can make sure u have the right file extension.

just use
`sudo nano config.properties`
in the same folder where u have the bot 

have u tried  ?
>If your current directory is already correct, just do java -jar PokemonGoBot-0.5.0.jar with no directory information in it.

**Comment by gabrielklein** [comment]
Be sure that you are in the same folder, and run it manually (using the terminal)! (java -jar xxx)
If you double-click on it to start it, you may have an issue.

Check the owner of the file too! Did you run it as root before?

**Comment by kjp87** [comment]
<img width="598" alt="screen shot 2016-08-08 at 21 50 07" src="https://cloud.githubusercontent.com/assets/20911706/17495716/22cc1c3e-5db2-11e6-92df-cb8ff9d4ab98.png">
Danman00, Thanks for your advice mate, I've loaded it up using the sudo nano command as advised, but I'm not sure how to save as a new file from the window, can you advise please?

**Comment by kjp87** [comment]
<img width="598" alt="screen shot 2016-08-08 at 21 50 07" src="https://cloud.githubusercontent.com/assets/20911706/17495852/9bed13ac-5db2-11e6-865a-cce08d78b288.png">
Danman00 I've opened the file using the sudo nano command, but I'm unsure as to how save the file to ensure theres no hidden .txt extension, can you please advise? thanks bud!

**Comment by kjp87** [comment]
gabrielklein when you say ran as root, how do you mean please mate?

**Comment by Danman00** [comment]
Press Ctrl+o to save the file in this step u set the file Name and Ctrl+x to close nano

**Comment by gabrielklein** [comment]
Root = admin access (I don't know the exact name on mac).
If the config file was created by an admin access (su ...), you may have this issue.

**Comment by kjp87** [comment]
Danman00 No luck unfortunately mate. I'll try deleting it all and restarting again. I wonder if there is some way of clearing my cash that could help

**Comment by Danman00** [comment]
That could help too 
i'm also using a MAC here's my setup
i got a folder on my dekstop called pogo
i created the config.properties with nano
'sudo nano config.properties'
then i start the bot with
'sudo java -jar PokemonGoBot-0.5.0.jar' i also use sudo here so i dont get permission issues if the bot needs to write the token in the config file

**Comment by kjp87** [comment]
A fresh install, carefully checked all files and even copied your setup using the sudo nano on the config.properties file, and the sudo java -jar PokemonGoBor-0.5.0.jar. Exact same result as before :(
It worked beautifully on the first run, and now nothing. Thank you very much for your help guys, maybe it's just not meant to be! :(

**Comment by kiaph** [comment]
I hate to be the guy to ask this, but as it hasn't been asked yet..

Have you tried restarting your computer?

I have solved very similar issues lately with the bot by restarting my and my GF's laptops.

**Comment by gabrielklein** [comment]
Try to redo the same thing without the "sudo" ;)

**Comment by kjp87** [comment]
kiaph Yes mate, to the point my computer must twitch every time I go near the apple logo haha

gabrielklein same result buddy, I even used CCleaner to clear all cache files I can. Something odd has happened somewhere I feel, I think in using the program once, a setting has changed somewhere and now it won't go back :(

**Comment by kjp87** [comment]
The only other possibility I can think of is perhaps my java has gone belly up? I'll try removing it if i can then re-installing that.

**Comment by kjp87** [comment]
Removed all traces of java, cleared cache, restart.
Installed a fresh copy of netbeans8.1 and java 8 (update 101), and still the same ending as before. For some bizarre reason my computer is unable to locate the config.properties file in the same folder as the bot. the config.properties file comes up as a java properties file (get info; Kind: java properties).

Big thanks to all those that attempted helping!

**Comment by langerhans** [comment]
Can you post `ls -al` from that directory? Maybe it'S just a permissions issue.
