### ISSUE TITLE
Exception in thread "main" java.lang.NumberFormatException: empty String (Not lat/long)

### ISSUE THREAD

**Issue by GameRulerX** [jabbink/PokemonGoBot#86]
Hi! I noticed somebody else had posted about this; their issue was just that they didn't have the lat/long, which I do. I'm also brand new to github , so sorry if I posted this in the wrong manner. I've got everything saved just as I did in the previous version, edited the config.properties ( Info about it provided below. ( I ommited my lat/long as well as my username and Password) {I wasn't sure about the token/based64 password, or what it's for/does, is that where my issue is coming into play?}
**TL;DR:** New to github, not sure where to post, issue as at bottom

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMD log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\pc>cd desktop

C:\Users\pc\Desktop>java -jar pogo.scraper-all-0.3.0.jar
Exception in thread "main" java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at ink.abb.pogo.scraper.Settings$startingLatitude$1.invoke(Settings.kt:37)
        at ink.abb.pogo.scraper.Settings$startingLatitude$1.invoke(Settings.kt:16)
        at ink.abb.pogo.scraper.Settings.getPropertyOrDie(Settings.kt:69)
        at ink.abb.pogo.scraper.Settings.<init>(Settings.kt:37)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:68)

C:\Users\pc\Desktop>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Config.Properties
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# PTC/Google login credentials
username=*********@gmail.com
#Choose plaintext or base64'd password
password=****
base64_password=
# Token to login directly
token=
latitude=********
longitude=********
preferred_ball=ITEM_POKE_BALL
# should the bot EVER drop items (true/false)
drop_items=true
# Meters per second
speed=2.778
# should the bot auto transfer duplicate pokemon
autotransfer=false
# Minimum CP to keep a pokemon
transfer_cp_threshold=1500
# list of pokemon you don't want to transfer regardless of CP
# the names must be divided by a ","
# if you want all pokemons to be transferred just leave it blank
ignored_pokemon=EEVEE,MEWTWO
,BULBASAUR,IVYSAUR,VENUSAUR,CHARMELEON,CHARIZARD,OMANYTE,OMASTAR,KABUTO
,KABUTOPS,SNORLAX,SQUIRTLE,WARTORTLE,BLASTOISE,DRATINI
# list of pokemon you always want to trancsfer regardless of CP
# obligatory_transfer=DODUO,RATTATA,CATERPIE,PIDGEY
#List of pokemon names (I took it out for -obvious- reasons?)
```

**Comment by jabbink** [comment]
The error message indicates that your `latitude=***` does not contain a valued value.

Make sure there is no space behind the `=` and the decimal point is a `.`, not a `,`.

**Comment by GameRulerX** [comment]
It also seems that there is a difference between the template and what you've got posted, as I've noted. checking to see if that was the issue
