### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by EpicAwesomeWolf** [jabbink/PokemonGoBot#864]
Start bot, then...

Last login: Mon Aug  8 15:59:08 on ttys000
Jacks-MacBook-Pro-125:~ Jack$ /Users/Jack/Desktop/Tresh\ v3/tresh\ m8\ copy.command ; exit;

2016-08-08 16:01:32.545  INFO 5607 --- [           main] ink.abb.pogo.scraper.MainKt              : Starting MainKt on Jacks-MacBook-Pro-125.local with PID 5607 (/Users/Jack/Desktop/Tresh v3/PokemonGoBot-0.5.0.jar started by Jack in /Users/Jack/Desktop/Tresh v3)
2016-08-08 16:01:32.553  INFO 5607 --- [           main] ink.abb.pogo.scraper.MainKt              : No active profile set, falling back to default profiles: default
2016-08-08 16:01:32.686  INFO 5607 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@30946e09: startup date [Mon Aug 08 16:01:32 EDT 2016]; root of context hierarchy
2016-08-08 16:01:34.645  INFO 5607 --- [           main] org.xnio                                 : XNIO version 3.3.6.Final
2016-08-08 16:01:34.693  INFO 5607 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.6.Final
2016-08-08 16:01:34.901  WARN 5607 --- [           main] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2016-08-08 16:01:34.901  WARN 5607 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2016-08-08 16:01:34.922  INFO 5607 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2016-08-08 16:01:34.924  INFO 5607 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2242 ms
2016-08-08 16:01:35.273  INFO 5607 --- [           main] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2016-08-08 16:01:35.280  INFO 5607 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2016-08-08 16:01:35.281  INFO 5607 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2016-08-08 16:01:35.282  INFO 5607 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2016-08-08 16:01:35.282  INFO 5607 --- [           main] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
2016-08-08 16:01:35.887  INFO 5607 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@30946e09: startup date [Mon Aug 08 16:01:32 EDT 2016]; root of context hierarchy
2016-08-08 16:01:36.003  INFO 5607 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bots]}" onto public final java.util.List<ink.abb.pogo.scraper.Settings> ink.abb.pogo.scraper.controllers.BotController.bots()
2016-08-08 16:01:36.005  INFO 5607 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/load]}" onto public final void ink.abb.pogo.scraper.controllers.BotController.loadBot(java.lang.String)
2016-08-08 16:01:36.006  INFO 5607 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/unload]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.unloadBot(java.lang.String)
2016-08-08 16:01:36.006  INFO 5607 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/reload]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.reloadBot(java.lang.String)
2016-08-08 16:01:36.007  INFO 5607 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/stop]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.stopBot(java.lang.String)
2016-08-08 16:01:36.007  INFO 5607 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/api/bot/{name}/start]}" onto public final boolean ink.abb.pogo.scraper.controllers.BotController.startBot(java.lang.String)
2016-08-08 16:01:36.013  INFO 5607 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2016-08-08 16:01:36.015  INFO 5607 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2016-08-08 16:01:36.101  INFO 5607 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 16:01:36.101  INFO 5607 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 16:01:36.163  INFO 5607 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 16:01:36.300  INFO 5607 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-08-08 16:01:36.378  INFO 5607 --- [           main] b.c.e.u.UndertowEmbeddedServletContainer : Undertow started on port(s) 8080 (http)
2016-08-08 16:01:36.385  INFO 5607 --- [           main] ink.abb.pogo.scraper.MainKt              : Started MainKt in 4.735 seconds (JVM running for 5.453)
08 Aug 16:01:36 (default): Set Profile Update Timer setting ("profile_update_timer") not specified, defaulting to "60". 
08 Aug 16:01:36 (default): Set Timer to return the first Pokestop (minutes) setting ("timer_walk_to_start_pokestop") not specified, defaulting to "-1". 
08 Aug 16:01:36 (default): Should the bot follow the streets (true) or just go directly to pokestops/waypoints setting ("follow_streets") not specified, defaulting to "false". 
08 Aug 16:01:36 (default): Max number of items to keep from type ITEM_LUCKY_EGG setting ("item_lucky_egg") not specified, defaulting to "-1". 
08 Aug 16:01:36 (default): Max number of items to keep from type ITEM_INCENSE_ORDINARY setting ("item_incense") not specified, defaulting to "-1". 
08 Aug 16:01:36 (default): Max number of items to keep from type ITEM_TROY_DISK (lure module) setting ("item_lure_module") not specified, defaulting to "-1". 
08 Aug 16:01:36 (default): maximum keep pokemon amount setting ("max_pokemon_amount") not specified, defaulting to "-1". 
08 Aug 16:01:36 (default): Display If Pokemon Was Caught From Lure setting ("display_if_pokemon_from_lure") not specified, defaulting to "true". 
08 Aug 16:01:36 (default): Allow leaving the starting area setting ("allow_leave_start_area") not specified, defaulting to "false". 
08 Aug 16:01:36 (default): Max distance from starting point the bot should ever go setting ("spawn_radius") not specified, defaulting to "-1". 
08 Aug 16:01:36 (default): Number of times the pokestop should be spun to attempt softban bypass setting ("ban_spin_count") not specified, defaulting to "0". 
08 Aug 16:01:36 (default): Export on Profile Update setting ("export") not specified, defaulting to "". 
08 Aug 16:01:36 (default): Port where the socketserver should listen setting ("gui_port_socket") not specified, defaulting to "8001". 
08 Aug 16:01:36 (default): Initial map size (S2 tiles) to fetch setting ("initial_map_size") not specified, defaulting to "9". 
08 Aug 16:01:36 (default): Logging in to game server...
08 Aug 16:01:37 (default): Logged in successfully
Getting profile data from pogo server.
D/RequestHandler: Authenticated with static token
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
	at com.pokegoapi.api.player.PlayerProfile.getStats(PlayerProfile.java:304)
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 10 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 12 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Danman00** [comment]
Are u using the latest [conf Template](https://raw.githubusercontent.com/jabbink/PokemonGoBot/master/config.properties.template) ?

**Comment by EpicAwesomeWolf** [comment]
@Danman00, just used latest template, and I get this error: 
08 Aug 17:07:14 (default): Getting initial pokestops...
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:422)
	at ink.abb.pogo.scraper.Bot.start(Bot.kt:102)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:144)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 7 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 9 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Danman00** [comment]
Looks like  #858

**Comment by Spyderdreams** [comment]
yes I believe it is the same
fm360 states  

> I found a way to fix this type "java -jar PokemonGoBot-0.5.0.jar --server.port=8090" to start it up

**Comment by jabbink** [comment]
Try 0.5.1

**Comment by langerhans** [comment]
Also duplicate.
