### ISSUE TITLE
Logs in but then doesn't work

### ISSUE THREAD

**Issue by arekay18** [jabbink/PokemonGoBot#865]
**Description:**
I can successfully log-in, but then a wall of text appears and nothing more happens.

**Steps to reproduce:**

1. Start Bot
2. Logs-in
3. Stops working

**Expected behavior:**
The bot should run.

**Actual behavior:**
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:77)
	at com.pokegoapi.api.player.PlayerProfile.getPlayerData(PlayerProfile.java:227)
	at ink.abb.pogo.scraper.Bot.start(Bot.kt:60)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:144)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)

**Version:**
0.5.0

**Operating System:**
OSX

**Java version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

**Comment by Danman00** [comment]
Same issue here #858 plese search next time
