### ISSUE TITLE
bot working for 8 hours then this suddenly came in

### ISSUE THREAD

**Issue by blindxscript** [jabbink/PokemonGoBot#868]
**Description:**
Bot just suddenly stop working

ERROR 33143 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186) ~[undertow-core-1.3.23.Final.jar!/:1.3.23.Final]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:71) [PokemonGoBot-0.5.0.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54) [PokemonGoBot-0.5.0.jar!/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104) [PokemonGoBot-0.5.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61) [PokemonGoBot-0.5.0.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [PokemonGoBot-0.5.0.jar:na]
**Caused by: java.net.BindException: Address already in use**
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_101]
	at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_101]
	at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_101]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_101]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_101]
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190) ~[xnio-nio-3.3.6.Final.jar!/:3.3.6.Final]
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243) ~[xnio-api-3.3.6.Final.jar!/:3.3.6.Final]
	at io.undertow.Undertow.start(Undertow.java:142) ~[undertow-core-1.3.23.Final.jar!/:1.3.23.Final]
	... 19 common frames omitted

**Comment by blindxscript** [comment]
fixed by java "-jar PokemonGoBot-0.5.0.jar --server.port=8090" by fm360

**Comment by jabbink** [comment]
Bot was obviously not running for 8 hours straight as this is the log of the startup.

Also a cleaner option is to do `--spring.main.web-environment=false` instead of that server,port thing if you don't care about multibotting and the mgmt interface.
