### ISSUE TITLE
Bot logs in but cannot log into GUI

### ISSUE THREAD

**Issue by nokingah** [jabbink/PokemonGoBot#882]
**Description:**
The bot seems to start up fine, then some exception comes and I cannot access the GUI

And I cannot connect to the GUI via the website either

**Steps to reproduce:**

1. Used the command `java -jar PokemonGoBot-0.5.0.jar`
Waits...

**Expected behavior:**
Thought the bot would start (though the last version i used was 4.3 so I'm haven't seen the new GUI working etc.)

**Actual behavior:**
It stops and I cannot login to the GUI

**Stacktrace (If it's a crash):**
`08 Aug 22:33:49 (default): Logging in to game server...
08 Aug 22:33:50 (default): Logged in successfully
Getting profile data from pogo server.
D/RequestHandler: Authenticated with static token
Exception in thread "default" java.lang.NullPointerException
        at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
`

**Version:**
0.5.0

**Operating System:**
Ubuntu 16.04

**Java version:**
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

[Full output of `java -version`]

**Comment by jabbink** [comment]
Try v0.5.1

**Comment by jabbink** [comment]
Also jdk9 is highly experimental and known for misbehaving. Only reason anyone can download it right now is for devs to debug and I've heard that this bot does not always work correctly with it.

Please use a stable (if possible Oracle) Are/Jdk 8.

**Comment by langerhans** [comment]
Solution was offered, also duplicate (#794)
