### ISSUE TITLE
Stops working, Remove Token works again

### ISSUE THREAD

**Issue by Smir** [jabbink/PokemonGoBot#89]
I understand everything is unstable at the current moment, But just noticed that it stops working, I removed the token, and it worked fine...

error before removing the token was this.

`.D/RequestHandler: Authenticated with static token
E/PokemonGo: Failed to get profile data and update inventory
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProto
colBufferException: Contents of buffer are null
        at com.pokegoapi.api.PokemonGo.getPlayerAndUpdateInventory(PokemonGo.jav
a:117)
        at com.pokegoapi.api.PokemonGo.getPlayerProfile(PokemonGo.java:175)
        at com.pokegoapi.api.PokemonGo.getPlayerProfile(PokemonGo.java:157)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:100)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
r are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.PokemonGo.getPlayerAndUpdateInventory(PokemonGo.jav
a:114)
        ... 3 more

.`

I guess the token is the huge long letter/number combo starting like this?

eyJhbGciOiJSUzI1NiIsImtpZCI6ImQ5Zjg0M2ZmNTVkMD

same issue with PTC and Google...

**Comment by pr0ves** [comment]
It's because it expired, you have to regenerate from time to time.

**Comment by Smir** [comment]
I see so there isn't a way to automatically approve, how comes I've only ever had to do it once for PokeColor? 

I know this uses Java, but Authentication should be the same across multiple platforms?

**Comment by pr0ves** [comment]
The APIs handle the authentication in different ways. PokeColor is in C# and probably the PokeGO API written in C# handles it better

**Comment by pr0ves** [comment]
Actually, now that i think about it, it's because the one who create the token request chooses an duration for every generated token. So probably the guys of the PokeGOAPI in java chose to expirate the token very soon from it's generation.
Other than this, I don't know what could it be

**Comment by jabbink** [comment]
Upstream issue with logging in.

**Comment by Smir** [comment]
What do you mean Jabbink?

**Comment by Smir** [comment]
it happens constantly, Tried on 3 Different PC's, 1 of which is a windows server in a totally different location

**Comment by jabbink** [comment]
It's the API, not this bot, that is doing wrong stuff for Google login. Apparently nobody cares enough to fix the Google part as almost everyone botting uses a (disposable) ptc account.
