### ISSUE TITLE
Sudden LoginFailedException: Invalid Auth status code

### ISSUE THREAD

**Issue by zoegalaxy** [jabbink/PokemonGoBot#892]
**Description:**

Bot running fine then after sometime will have this error:

Caused by: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:217)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
	at java.lang.Thread.run(Thread.java:745)

Restart the Bot and becomes okay again.  Problem for me if I leave my mac running overnight then wake up in the morning just to find out it has this error.

I'm using PTC, and not Google.

**Expected behavior:**
Bot running continuously

**Actual behavior:**
Bot running fine then all of sudden will have the Exception error.  Restart the bot and is okay again.

**Comment by remie2000** [comment]
#817
