### ISSUE TITLE
Bot is logging in but not doing anything after.

### ISSUE THREAD

**Issue by ThaPurno** [jabbink/PokemonGoBot#893]
Bot isn't working atm yesterday it worked.

09 Aug 10:41:53 (default): Logging in to game server...
2016-08-09 10:41:53.233  INFO 3604 --- [  XNIO-2 task-1] io.undertow.servlet
                  : Initializing Spring FrameworkServlet 'dispatcherServlet'
2016-08-09 10:41:53.234  INFO 3604 --- [  XNIO-2 task-1] o.s.web.servlet.Dispatc
herServlet        : FrameworkServlet 'dispatcherServlet': initialization started

2016-08-09 10:41:53.287  INFO 3604 --- [  XNIO-2 task-1] o.s.web.servlet.Dispatc
herServlet        : FrameworkServlet 'dispatcherServlet': initialization complet
ed in 52 ms
D/RequestHandler: Authenticated with static token
09 Aug 10:41:54 (default): Logged in successfully
Getting profile data from pogo server.
Exception in thread "default" java.lang.NullPointerException
        at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(P
okemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(P
okemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
2016-08-09 10:42:09.478  WARN 3604 --- [  XNIO-2 task-4] o.s.web.servlet.PageNot
Found             : Request method 'POST' not supported
2016-08-09 10:42:11.538  WARN 3604 --- [  XNIO-2 task-5] o.s.web.servlet.PageNot
Found             : Request method 'POST' not supported
2016-08-09 10:43:02.548  WARN 3604 --- [ XNIO-2 task-20] o.s.web.servlet.PageNot
Found             : Request method 'POST' not supported
2016-08-09 10:43:04.611  WARN 3604 --- [ XNIO-2 task-21] o.s.web.servlet.PageNot
Found             : Request method 'POST' not supported
> Building 83% > :run

**Comment by jabbink** [comment]
Should be fixed on `develop` now.

Problem is that your account never accepted the ToS.
