### ISSUE TITLE
Address already in use on OS X when running second bot

### ISSUE THREAD

**Issue by StephanBijzitter** [jabbink/PokemonGoBot#895]
With the previous release, just before the big day, I had to change the gui settings to be able to bot on multiple accounts.

```ini
# Port where the webserver (gui) should listen, 0 = do not listen
gui_port=0
# Port where the socketserver should listen, 0 = do not listen
gui_port_socket=0
```

These settings were (are) used for all accounts.
It seems that the 0.5 update does not respect these values anymore, and still tries to open up a socket. With the first bot, that is not a problem. However, as soon as the second bot tries to create the socket, shit hits the fan.

stacktrace:
```
java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186) ~[undertow-core-1.3.23.Final.jar!/:1.3.23.Final]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:71) [PokemonGoBot-0.5.0.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54) [PokemonGoBot-0.5.0.jar!/:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104) [PokemonGoBot-0.5.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61) [PokemonGoBot-0.5.0.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [PokemonGoBot-0.5.0.jar:na]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_73]
	at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_73]
	at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_73]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_73]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_73]
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190) ~[xnio-nio-3.3.6.Final.jar!/:3.3.6.Final]
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243) ~[xnio-api-3.3.6.Final.jar!/:3.3.6.Final]
	at io.undertow.Undertow.start(Undertow.java:142) ~[undertow-core-1.3.23.Final.jar!/:1.3.23.Final]
	... 19 common frames omitted
```

**Comment by pashorizer** [comment]
Append this to your command line `spring.main.web-environment=false`

**Comment by StephanBijzitter** [comment]
Shut down account A and then started A again with these arguments. Still works as expected. However B still cannot be started, with or without these arguments.

**Comment by pashorizer** [comment]
@StephanBijzitter Use it with double `--`

**Comment by jabbink** [comment]
Don't run a second java instance, this bot has multibot capabilities. Check the README.

**Comment by StephanBijzitter** [comment]
Apologies :-)
