### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by namkangice** [jabbink/PokemonGoBot#896]
Can't start bot
_________________________________________________________________________________________
_________________________________________________________________________________________
d:\poke>java -jar PokemonGoBot-0.5.0.jar --server.port=8090

2016-08-09 16:40:06.533  INFO 4708 --- [           main] ink.abb.pogo.scraper.MainKt              : Starting MainKt on DESKTOP-VT0RN55 with PID 4708 (D:\poke\PokemonGoBot-0.5.0.jar started by ICELP in d:\poke)
2016-08-09 16:40:06.553  INFO 4708 --- [           main] ink.abb.pogo.scraper.MainKt              : No active profile set, falling back to default profiles: default
2016-08-09 16:40:06.630  INFO 4708 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@506c589e: startup date [Tue Aug 09 16:40:06 ICT 2016]; root of context hierarchy
2016-08-09 16:40:08.382  INFO 4708 --- [           main] org.xnio                                 : XNIO version 3.3.6.Final
2016-08-09 16:40:08.407  INFO 4708 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.6.Final
2016-08-09 16:40:09.497  WARN 4708 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.IllegalArgumentException: XNIO001001: No XNIO provider found
2016-08-09 16:40:09.534 ERROR 4708 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.IllegalArgumentException: XNIO001001: No XNIO provider found
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:306) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:71) [PokemonGoBot-0.5.0.jar!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54) [PokemonGoBot-0.5.0.jar!/:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:104) [PokemonGoBot-0.5.0.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:61) [PokemonGoBot-0.5.0.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [PokemonGoBot-0.5.0.jar:na]
Caused by: java.lang.IllegalArgumentException: XNIO001001: No XNIO provider found
        at org.xnio.Xnio.doGetInstance(Xnio.java:255) ~[xnio-api-3.3.6.Final.jar!/:3.3.6.Final]
        at org.xnio.Xnio.getInstance(Xnio.java:198) ~[xnio-api-3.3.6.Final.jar!/:3.3.6.Final]
        at io.undertow.websockets.jsr.UndertowContainerProvider.getDefaultContainer(UndertowContainerProvider.java:92) ~[undertow-websockets-jsr-1.3.23.Final.jar!/:1.3.23.Final]
        at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:63) ~[undertow-websockets-jsr-1.3.23.Final.jar!/:1.3.23.Final]
        at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:252) ~[undertow-servlet-1.3.23.Final.jar!/:1.3.23.Final]
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:152) ~[undertow-servlet-1.3.23.Final.jar!/:1.3.23.Final]
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createDeploymentManager(UndertowEmbeddedServletContainerFactory.java:365) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:220) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:160) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130) ~[spring-boot-1.3.6.RELEASE.jar!/:1.3.6.RELEASE]
        ... 16 common frames omitted

2016-08-09 16:40:09.666  INFO 4708 --- [           main] .b.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: [jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/PokeGOAPI-Java-ef1f52f1f0621f94b97125975c961a8ad8129e92.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/kotlin-stdlib-1.0.3.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/netty-socketio-1.7.7.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-boot-starter-1.3.6.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-boot-starter-web-1.3.6.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-boot-starter-undertow-1.3.6.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/jackson-databind-2.8.0.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/jackson-core-2.8.0.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/jackson-annotations-2.8.0.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/jackson-module-kotlin-2.8.0.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/gpsoauth-0.3.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/okio-1.9.0.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/moshi-1.2.0.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/stream-1.1.1.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/okhttp-3.4.1.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/protobuf-java-3.0.0-beta-3.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/rxjava-1.1.8.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/lz4-1.3.0.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/kotlin-runtime-1.0.3.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/netty-buffer-4.0.25.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/netty-common-4.0.25.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/netty-transport-4.0.25.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/netty-handler-4.0.25.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/netty-codec-http-4.0.25.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/netty-codec-4.0.25.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/netty-transport-native-epoll-4.0.25.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/slf4j-api-1.7.21.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-boot-1.3.6.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-boot-autoconfigure-1.3.6.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-boot-starter-logging-1.3.6.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-core-4.2.7.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/snakeyaml-1.16.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-boot-starter-validation-1.3.6.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-web-4.2.7.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-webmvc-4.2.7.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/undertow-core-1.3.23.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/undertow-servlet-1.3.23.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/undertow-websockets-jsr-1.3.23.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/javax.servlet-api-3.1.0.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/javax.el-3.0.0.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/kotlin-reflect-1.0.3.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/base64-2.3.9.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-context-4.2.7.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/logback-classic-1.1.7.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/jcl-over-slf4j-1.7.21.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/jul-to-slf4j-1.7.21.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/log4j-over-slf4j-1.7.21.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/tomcat-embed-el-8.0.36.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/hibernate-validator-5.2.4.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-aop-4.2.7.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-beans-4.2.7.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/spring-expression-4.2.7.RELEASE.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/jboss-logging-3.3.0.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/xnio-api-3.3.6.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/xnio-nio-3.3.6.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/jboss-annotations-api_1.2_spec-1.0.0.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/jboss-websocket-api_1.1_spec-1.1.0.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/logback-core-1.1.7.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/validation-api-1.1.0.Final.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/classmate-1.1.0.jar!/, jar:file:/D:/poke/PokemonGoBot-0.5.0.jar!/lib/aopalliance-1.0.jar!/]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
        ... 3 more
Caused by: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.IllegalArgumentException: XNIO001001: No XNIO provider found
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:71)
        ... 8 more
Caused by: java.lang.IllegalArgumentException: XNIO001001: No XNIO provider found
        at org.xnio.Xnio.doGetInstance(Xnio.java:255)
        at org.xnio.Xnio.getInstance(Xnio.java:198)
        at io.undertow.websockets.jsr.UndertowContainerProvider.getDefaultContainer(UndertowContainerProvider.java:92)
        at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:63)
        at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:252)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:152)
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createDeploymentManager(UndertowEmbeddedServletContainerFactory.java:365)
        at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:220)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:160)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
        ... 16 more

_________________________________________________________________________________________
_________________________________________________________________________________________

**Operating System:**
windows10

**Java version:**
java version "1.8.0_66"

**Comment by FrancYescO** [comment]
try to update your jre is pretty old

**Comment by jabbink** [comment]
java 1.8.0_u102 should work

**Comment by langerhans** [comment]
This might actually be caused by having more than one JRE installed. What is the output of `echo %JAVA_HOME%`?
