### ISSUE TITLE
Bot fails with 'Contents of buffer are null' all the time - App and Emulator works from same IP

### ISSUE THREAD

**Issue by vamirineni87** [jabbink/PokemonGoBot#900]
**Description:**
Bot started failing in the last hour. Fails for all accounts during startup. 
Poke servers are up and running. 
App works fine in the droidemulator and phone as well from the same IP. (wifi)

After the error, does the bot retry to make any calls? No error handler?

**Error**
```
2016-08-09 07:11:06.461  INFO 16240 --- [           main] b.c.e.u.UndertowEmbeddedServletContainer : Undertow started on port(s) 8080 (http)
2016-08-09 07:11:06.469  INFO 16240 --- [           main] ink.abb.pogo.scraper.MainKt              : Started MainKt in 3.028 seconds (JVM running for 3.504)
09 Aug 07:11:06 (default): Logging in to game server...
09 Aug 07:11:07 (default): Logged in successfully
Getting profile data from pogo server.
D/RequestHandler: Authenticated with static token
09 Aug 07:11:08 (default):
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred.
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:77)
        at com.pokegoapi.api.player.PlayerProfile.getPlayerData(PlayerProfile.java:227)
        at ink.abb.pogo.scraper.Bot.start(Bot.kt:60)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:144)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 9 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        ... 11 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by Peyphour** [comment]
There is at least 5 other issues for this ...

**Comment by vamirineni87** [comment]
I have read the all the comments for past 30 mins. "Its a shitty server response". But my question is about error handling. if the bot encounters this error, does it not continue?

**Comment by Peyphour** [comment]
The exception isn't caught so no

**Comment by jabbink** [comment]
Also try 0.5.1

**Comment by vamirineni87** [comment]
Tried that. Still seems to be happening occasionally. I just have to restart the bot again. Issue though i have a script with timer and it only restarts every 90 mins. so 90 mins lost if this error occurs. Wish I had time to learn kotlin
