### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by lalahazred** [jabbink/PokemonGoBot#905]
Description:
I'm receiving a login error.

"Logging in to game server...
Exception in thread "default" java.lang.IllegalStateException: Server refused your login credentials. Are they correct?"

not sure why this is happening. I copied the exact login/psw directly from the previous working bot.

**Comment by emperol2** [comment]
same issue here.

**Comment by pokecheater** [comment]
Same Issue

First it was working all fine. Since I restarted the bot I've got the following error:

Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
	at com.pokegoapi.api.player.PlayerProfile.getStats(PlayerProfile.java:304)
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 10 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 12 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pokecheater** [comment]
I have a similar issue with my second account. Login in the morning was fine (i logged in multiple times). Now I ve got the following error (like the one with the unknown6 hash codes when the api was broken):

09 Aug 15:47:52 (default): Got 0 pokestops
09 Aug 15:47:52 (default): Retrying in 10 seconds... 
 

Login with the normal client is still fine.

**Comment by jabbink** [comment]
@pokecheater 

Let it retry, sometimes this is a temporary issue, the entire reason why it says "retrying" instead of "good luck, byebye"

@lalahazred your username/password is wrong. If you use Google login, make sure you put in your full emailaddress as username!

@emperol2 ^
