### ISSUE TITLE
Unable to log in using latest bot with gradle

### ISSUE THREAD

**Issue by smileytechguy** [jabbink/PokemonGoBot#929]
Unable to log in using latest bot with gradle
``` java
                                  ,'\
    _.----.        ____         ,'  _\   ___    ___     ____        ;-.               ,
_,-'       `.     |    |  /`.   \,-'    |   \  /   |   |    \  |`.   \ '.           .'/
\      __    \    '-.  | /   `.  ___    |    \/    |   '-.   \ |  |   \  \ .---. .-' /
 \.    \ \   |  __  |  |/    ,','_  `.  |          | __  |    \|  |    '. '     `\_.'
   \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |      |(),()  |     ,
    \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |      (  __   /   .' \
     \    \ |   \_/  |   `-.  \    `'  /|  |    ||   \_/  | |\    |     .''.___.'--,/\_,|
      \    \ \      /       `-.`.___,-' |  |\  /| \      /  | |   |    {  /     \   }   |
       \    \ `.__,'|  |`-._    `|      |__| \/ |  `.__,'|  | |   |     '.\     /_.'    /
        \_.-'       |__|    `-._ |              '-.|     '-.| |   |      |'-.-',  `; _.'
                                `'                            '-._|      |  |  |   |`
                                                                         `""`""`"""`
10 Aug 00:15:40 [stg] - Logging in to game server...
10 Aug 00:15:40 [mate] - Logging in to game server...
10 Aug 00:15:40 [mom] - Logging in to game server...
Please go to https://accounts.google.com/o/oauth2/auth?client_id=848232511240-73ri3t7plvk96pj4f85uj8otdat2alem.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=openid%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Enter authorisation code:
Please go to https://accounts.google.com/o/oauth2/auth?client_id=848232511240-73ri3t7plvk96pj4f85uj8otdat2alem.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=openid%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Enter authorisation code:
Please go to https://accounts.google.com/o/oauth2/auth?client_id=848232511240-73ri3t7plvk96pj4f85uj8otdat2alem.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=openid%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Enter authorisation code:
D/GoogleUserCredentialProvider: 0
D/GoogleUserCredentialProvider: Got token: null
Refresh token:null
10 Aug 00:15:42 [mate] - Setting Google refresh token in your config
D/GoogleUserCredentialProvider: 0
D/GoogleUserCredentialProvider: Got token: nullException in thread "mate" 
java.lang.IllegalStateException: provider.refreshToken must not be null
        at ink.abb.pogo.scraper.MainKt.getAuth(Main.kt:52)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:129)
        at ink.abb.pogo.scraper.MainKt.startBot$default(Main.kt:118)
        at ink.abb.pogo.scraper.services.BotService.submitBot(BotService.kt:40)
Refresh token:null      at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:62)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

10 Aug 00:15:42 [mom] - Setting Google refresh token in your config
Exception in thread "mom" java.lang.IllegalStateException: provider.refreshToken must not be null
        at ink.abb.pogo.scraper.MainKt.getAuth(Main.kt:52)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:129)
        at ink.abb.pogo.scraper.MainKt.startBot$default(Main.kt:118)
        at ink.abb.pogo.scraper.services.BotService.submitBot(BotService.kt:40)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:62)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
D/GoogleUserCredentialProvider: 0
D/GoogleUserCredentialProvider: Got token: null
Refresh token:null
10 Aug 00:15:43 [stg] - Setting Google refresh token in your config
Exception in thread "stg" java.lang.IllegalStateException: provider.refreshToken must not be null
        at ink.abb.pogo.scraper.MainKt.getAuth(Main.kt:52)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:129)
        at ink.abb.pogo.scraper.MainKt.startBot$default(Main.kt:118)
        at ink.abb.pogo.scraper.services.BotService.submitBot(BotService.kt:40)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:62)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$forEach$lambda$1.invoke(PokemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Comment by smileytechguy** [comment]
Resolved: needed to change login type to google-auto
