### ISSUE TITLE
I got error on POGOProtos.Enums

### ISSUE THREAD

**Issue by pietsteph** [jabbink/PokemonGoBot#932]
Exception in thread "default" java.lang.IllegalArgumentException: No enum constant POGOProtos.Enums.PokemonIdOuterClass.PokemonId.MRMIME
	at java.lang.Enum.valueOf(Enum.java:238)
	at POGOProtos.Enums.PokemonIdOuterClass$PokemonId.valueOf(PokemonIdOuterClass.java:14)
	at ink.abb.pogo.scraper.SettingsParser.createSettingsFromProperties(Settings.kt:99)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:111)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

*Version: 0.5.1

*Operating System: macOS 10.12

*java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by Peyphour** [comment]
Did you put MRMIME in your config ?

**Comment by pietsteph** [comment]
yes

**Comment by Peyphour** [comment]
Can you close the issue ?
