### ISSUE TITLE
LoginFailedException again

### ISSUE THREAD

**Issue by staurakis** [jabbink/PokemonGoBot#933]
After more than 8 hours running perfectly, i once again received this error:

Caused by: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:217)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
        at java.lang.Thread.run(Unknown Source)
←[37m10 ┴Ϋή 08:50:04 [default: BotLoop] - Getting map of (37.9310334331721, 23.686526395912175)
←[0;39m←[37m10 ┴Ϋή 08:50:04 [default: BotLoop] - Looting nearby pokestop e58a79f44e624c58b2cdd31efa93c486.16
←[0;39mD/RequestHandler: Authenticated with static token
←[31m10 ┴Ϋή 08:50:05 [default: BotLoop] - Error running loop BotLoop!
←[0;39mcom.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred.
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.api.map.fort.Pokestop.loot(Pokestop.java:172)
        at ink.abb.pogo.scraper.tasks.LootOneNearbyPokestop.run(LootOneNearbyPokestop.kt:39)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:239)
        at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:51)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:239)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:149)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:187)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved
, token not refreshed?
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 10 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
        at rx.Observable.unsafeSubscribe(Observable.java:9861)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        ... 12 more
Caused by: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:217)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
        at java.lang.Thread.run(Unknown Source)

I am running the latest version of the program on a windows 7 machine and my java version is: build 1.8.0_101-b13.

**Comment by akocmark** [comment]
im also getting the same error

**Comment by Peyphour** [comment]
Stop the bot, kill all java process and restart

**Comment by staurakis** [comment]
When it restarts it runs again smoothly for x amount of time (that can be something between 1,5 hours to 8 hours) and then at some point it crashes again.
So it is only a matter of fixing it in order to have an unattended client cause right now the program cannot run unattended.

**Comment by Peyphour** [comment]
What auth do you use ? Google, google-auto, ptc ?

**Comment by staurakis** [comment]
currently ptc but i have tested it and experienced it with google as well.

**Comment by Peyphour** [comment]
The 'x amount of time' is the token expiration time, I don't know if the bot request another automatically

**Comment by staurakis** [comment]
mmmmm i'm not so sure, cause as i said, everything appears quite randomly. 
The amount of time is so random that makes it impossible to reproduce this error. 
Except, if something (for example a load on the server side) makes it impossible for the program to authenticate and somewhere there the problem occurs. 
But as far as i can tell, the re authentication process is working correctly most of the times.....

**Comment by Peyphour** [comment]
We should add some debug output, maybe catch the LoginFailedException and see at this point

**Comment by staurakis** [comment]
indeed.... 
I tried to check the logs, but the only thing that you can see, is the error not being able the get the map information (due to the non authenticated event)....

**Comment by akocmark** [comment]
not sure, but it seems that this only happens when you're using google login.
the google authentication token doesn't last that long, means you'll get this error because the google authentication token has expired, if so, I think we need a way to automatically refresh it every after a set interval.

**Comment by staurakis** [comment]
i use ptc.... and it always happens.

**Comment by akocmark** [comment]
@staurakis 
if that's the case, well I think Niantic is invalidating the token on server side at x amount of time and the new client app is refreshing this token every now and then. This only happens right after their new update.

**Comment by akocmark** [comment]
so it's confirmed

![screenshot 2016-08-10 11 59 33](https://cloud.githubusercontent.com/assets/4981864/17546236/3c91deec-5ef2-11e6-9a9b-25f069bb66a7.png)

**Comment by Peyphour** [comment]
Well a token is made to expire so ...
I will see if we can auto refresh the token when it expire

**Comment by staurakis** [comment]
That could indeed be the case and it is a good thought. On the other side...do they do this to their app as well? In other words, if somebody uses their app for x amount of time more than 2 hours, it suddenly stops working and has to exit and run it again? And if not what 'identifies' it not to behave like that?

**Comment by Peyphour** [comment]
No, in their app if the token expire the app request a new one

**Comment by staurakis** [comment]
So, the questions seems to be, can we do something to this program as well? I presume we can....

**Comment by Peyphour** [comment]
Yes we can for sure, when the token expire we just have to re-auth again

**Comment by staurakis** [comment]
I thought we were doing it already....

**Comment by akocmark** [comment]
please check the new 8.4 release. and see if it works :)

**Comment by Peyphour** [comment]
Which 8.4 release ? We are at 0.5.1 at the moment

**Comment by akocmark** [comment]
sorry wrong thread lol (was about to post it in necrobot)

**Comment by Peyphour** [comment]
Can you delete ?

**Comment by Mixone-FinallyHere** [comment]
this was repaired already no?
had it running all night yester/today and no issues

**Comment by staurakis** [comment]
I had it all night without issues (more than 8 hours) and in the morning it crashed again. It seems that it is not fixed no.

**Comment by Mixone-FinallyHere** [comment]
anything you might have set differently in config files?
or maybe you changed a piece of code and the git pull dint override it?
try re-cloning the latest build maybe

**Comment by staurakis** [comment]
no no nothing changed. It happens in a quite random and unexpected way. It is impossible to reproduce.... I am trying many things to try to track it down but it seems impossible.
I am suspecting Niantic's server. Something triggered from their side and cannot be handled from our side. The reset of the auth token is quite a possibility. What would be nice to know from @jabbink is how the program treats such an event, cause i think i have seen reauthentication and is working correctly most of the times.
That would explain why it can happen in 1,5 hours or after 8...

**Comment by Mixone-FinallyHere** [comment]
Thing is I am getting the exception but it is being handled by the code and just resending a static auth token (not sure if new or old) and without me having to do anything, about 10 seconds after it pops up the bot just keeps on going

**Comment by staurakis** [comment]
yes that's what i meant by 'most of the times it handles it without issues'. But sometimes it crashes and i don't know why.....
Either the server sends something else from what the program expects to 'catch' in order to reauthenticate, either the response of the program is not received correctly by the server and it doesn't accept it and the application crashes.

**Comment by Mixone-FinallyHere** [comment]
sorry :/

**Comment by staurakis** [comment]
Again after something like 2 hours:

**←[0;39mD/RequestHandler: Authenticated with static token
←[31m10 ┴Ϋή 16:17:14 [default: BotLoop] - Error running loop BotLoop!**
←[0;39mcom.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred.
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:148)
        at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:28)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:239)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:142)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:187)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth
status code recieved, token not refreshed?
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token
not refreshed?
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
        at rx.Observable.unsafeSubscribe(Observable.java:9861)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.Observable.unsafeSubscribe(Observable.java:9861)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        ... 11 more

**Comment by langerhans** [comment]
Duplicate issue, there are tons for the same problem already...
