### ISSUE TITLE
Can't run bot

### ISSUE THREAD

**Issue by damiienB** [jabbink/PokemonGoBot#941]
Hi , I have this all the time when I want to launch the bot
How fix this ?

10 août 15:06:53 [default] - Logging in to game server...
D/RequestHandler: Authenticated with static token
10 août 15:06:56 [default] - Logged in successfully
Getting profile data from pogo server.
Exception in thread "default" java.lang.UnsupportedClassVersionError: com/google/common/util/concurrent/AtomicDouble : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:260)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:112)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by mtchm** [comment]
update java?

**Comment by damiienB** [comment]
@mtchm 
I've already updated java (build 1.8.0_101-b13)

**Comment by Danman00** [comment]
have you got the exact error with 0.5.2 ?
i got the same error with an earlier version of the bot so i removed java completly and made a fresh install and now it works like a charm

**Comment by damiienB** [comment]
@Danman00 yes exactly the same error. I try to make a fresh install of Java
