### ISSUE TITLE
Google Error

### ISSUE THREAD

**Issue by brightstar75** [jabbink/PokemonGoBot#948]
i try login using google but keep having this message. Any advise?

"""`
←[37m10 Aug 21:54:40 [default] - Logging in to game server...
←[0;39mException in thread "default" java.lang.IllegalStateException: Server ref
used your login credentials. Are they correct?
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:131)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:112)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(P
okemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(P
okemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by toffaste1337** [comment]
Are your credentials correct?
Do you use `"credentials" : {
    "type" : "google",`?

**Comment by brightstar75** [comment]
where can i change the credentials type?

**Comment by toffaste1337** [comment]
If you're using the .properties file, make sure to use your whole email. If you're using the .properties file and have google 2-step verification enabled, make an app password.
If you're using the .json file, change `"type":"x"` to `"type":"google"` and get a link to generate a token on the first run.

**Comment by brightstar75** [comment]
thanks

**Comment by smileytechguy** [comment]
try to change google to google-auto

**Comment by brightstar75** [comment]
smileytechguy any difference? how to change?

**Comment by jabbink** [comment]
@brightstar75 did you put your full emailaddress in the `config.properties`?
