### ISSUE TITLE
Anybody gotten this error ? Please help

### ISSUE THREAD

**Issue by swtrpeter** [jabbink/PokemonGoBot#974]
**Description:**
Getting this error when trying to start bot behind VPN hotspot shield

10 Aug 20:20:41 [default] - Logging in to game server...
       D/RequestHandler: Authenticated with static token
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException:
Unknown exception occurred.
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.j
ava:155)
        at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:82)
        at com.pokegoapi.api.settings.Settings.<init>(Settings.java:69)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:95)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:146)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:112)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(P
okemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(P
okemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403

        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
ava:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.Rem
oteServerException: Got a unexpected http code : 403
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
e.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
e.call(OnSubscribeToObservableFuture.java:43)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
ava:445)
        ... 11 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http
 code : 403
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestH
andler.java:197)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
        at java.lang.Thread.run(Thread.java:745)
> Building 83% > :run
**Version:**
0.5.1
*Operating System:**
windows 7

**Java version:**
JDK 8

**Comment by toffaste1337** [comment]
Either Pokemon go has blacklisted that vpn or the ip is used by too many.
