### ISSUE TITLE
bot wont launch

### ISSUE THREAD

**Issue by sitruc1234** [jabbink/PokemonGoBot#979]
**Description:**
bot wont launch correcty

**Steps to reproduce:**

start it
**Expected behavior:**
login 

**Actual behavior:**
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 3 more
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:86)
	... 8 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:142)
	... 19 more
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Version:**
0.5.2
**Operating System:**
[Your operating system]

**Java version:**
8+

**Comment by BKer** [comment]
Hi,

It seems like something is already using port 8080. That's why you get an Address already in use message. You can set a different port by appending --server.port=8090 or something alike. It's actually described pretty well in the FAQ. I hope this resolves your issue :)

**Comment by sitruc1234** [comment]
i changed it and same thing

**Comment by sitruc1234** [comment]
also is it the port for the ui? i turned it off and still same issue

**Comment by sitruc1234** [comment]
Restarting computer did fix it, could it also have been the pokemon app on my phone that caused it?

**Comment by BKer** [comment]
No, I wasn't talking about the port for the UI. Although that could have been an issue as well if you run multiple bots. The FAQ has a section about: I get "Address already in use". The FAQ is more detailed than my description. If nothing of all that solves the issue I unfortunately have no clue :(

**Comment by BKer** [comment]
Hmm yeah I think you can't login on two different devices, but I'm not sure about that.
