### ISSUE TITLE
Unknown exception on startup

### ISSUE THREAD

**Issue by Killenova** [jabbink/PokemonGoBot#981]
←[32m11 Aug 18:04:54 [default] - Trying to read C:\Users\jkillen\Documents\pokeb
ot 0.5.2\config.properties
←[0;39m←[33m11 Aug 18:04:54 [default] - Set Profile Update Timer setting ("profi
le_update_timer") not specified, defaulting to "60".
←[0;39m←[33m11 Aug 18:04:54 [default] - Set Timer to return the first Pokestop (
minutes) setting ("timer_walk_to_start_pokestop") not specified, defaulting to "
-1".
←[0;39m←[33m11 Aug 18:04:54 [default] - Should the items that are kept be groupe
d by type (keep best from same type) setting ("group_items_by_type") not specifi
ed, defaulting to "false".
←[0;39m←[33m11 Aug 18:04:54 [default] - Max number of items to keep from type IT
EM_LUCKY_EGG setting ("item_lucky_egg") not specified, defaulting to "-1".
←[0;39m←[33m11 Aug 18:04:54 [default] - Max number of items to keep from type IT
EM_INCENSE_ORDINARY setting ("item_incense") not specified, defaulting to "-1".
←[0;39m←[33m11 Aug 18:04:54 [default] - Max number of items to keep from type IT
EM_TROY_DISK (lure module) setting ("item_lure_module") not specified, defaultin
g to "-1".
←[0;39m←[33m11 Aug 18:04:54 [default] - Camp around x lured pokestops setting ("
camp_lure_pokestop") not specified, defaulting to "-1".
←[0;39m←[33m11 Aug 18:04:54 [default] - Max distance from starting point the bot
 should ever go setting ("spawn_radius") not specified, defaulting to "-1".
←[0;39m←[33m11 Aug 18:04:54 [default] - Port where the socketserver should liste
n setting ("gui_port_socket") not specified, defaulting to "8001".
←[0;39m←[37m11 Aug 18:04:54 [default] - Logging in to game server...
←[0;39mException in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoExce
ption: Unknown exception occurred.
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.j
ava:155)
        at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:82)
        at com.pokegoapi.api.settings.Settings.<init>(Settings.java:69)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:95)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:180)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:145)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(P
okemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(P
okemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
com.pokegoapi.exceptions.RemoteServerException: java.net.ConnectException: Faile
d to connect to pgorelease.nianticlabs.com/130.211.14.80:443
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
ava:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.Rem
oteServerException: java.net.ConnectException: Failed to connect to pgorelease.n
ianticlabs.com/130.211.14.80:443
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
e.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
e.call(OnSubscribeToObservableFuture.java:43)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
ava:445)
        ... 11 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: java.net.ConnectExcep
tion: Failed to connect to pgorelease.nianticlabs.com/130.211.14.80:443
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestH
andler.java:240)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Failed to connect to pgorelease.nianticlab
s.com/130.211.14.80:443
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnecti
on.java:189)
        at okhttp3.internal.connection.RealConnection.buildConnection(RealConnec
tion.java:173)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.jav
a:114)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAll
ocation.java:193)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(St
reamAllocation.java:129)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocati
on.java:98)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInter
ceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.ja
va:109)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.j
ava:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndF
ollowUpInterceptor.java:124)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorCha
in.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
        at okhttp3.RealCall.execute(RealCall.java:60)
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestH
andler.java:195)
        ... 2 more

**Comment by Sieberkev** [comment]
> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
com.pokegoapi.exceptions.RemoteServerException: java.net.ConnectException: Faile
d to connect to pgorelease.nianticlabs.com/130.211.14.80:443

Looks like a server problem :)

(also your configuration is not up to date anymore, check the template to update it)

**Comment by langerhans** [comment]
Also a duplicate issue.
