### ISSUE TITLE
Bot stuck on pokestop XD

### ISSUE THREAD

**Issue by sitruc1234** [jabbink/PokemonGoBot#982]
11 Aug 02:12:17 [default: PokestopLoop] - Error running loop PokestopLoop!
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.api.map.fort.Pokestop.getDetails(Pokestop.java:249)
	at ink.abb.pogo.scraper.gui.SocketServer.sendPokestop(SocketServer.kt:125)
	at ink.abb.pogo.scraper.tasks.Walk.run(Walk.kt:52)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:70)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$5.invoke(Bot.kt:155)
	at ink.abb.pogo.scraper.Bot$start$5.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 11 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 13 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)
i have no clue what happend

**Comment by GonnaLoseItAll** [comment]
Have you closed it and reopened it?

**Comment by sitruc1234** [comment]
yea

**Comment by sitruc1234** [comment]
also every once and a while i get
11 Aug 02:46:07 [default: BotLoop] - Error running loop BotLoop!
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.pokemon.Pokemon.transferPokemon(Pokemon.java:89)
	at ink.abb.pogo.scraper.tasks.ReleasePokemon.run(ReleasePokemon.kt:48)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:149)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)

**Comment by langerhans** [comment]
>XD

Also duplicate issue. Search before posting.
