### ISSUE TITLE
Error running loop BotLoop

### ISSUE THREAD

**Issue by sitruc1234** [jabbink/PokemonGoBot#984]
11 Aug 02:54:31 [default: BotLoop] - Error running loop BotLoop!
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:82)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.dropItems(DropUselessItems.kt:90)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:147)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 10 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 12 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sitruc1234** [comment]
happen's every few mins when looting pokestop

**Comment by oleksij** [comment]
crashes with this issue once in ~1-2 hours
