### ISSUE TITLE
Exception in thread error

### ISSUE THREAD

**Issue by charliedumdum** [jabbink/PokemonGoBot#991]
when i start my bot it runs through parts of the config and then says this:

`Exception in thread "default" java.lang.IllegalStateException: javax.crypto.IllegalBlockSizeException: Data must not be longer than 86 bytes
	at svarzee.gps.gpsoauth.CipherUtil.pkcs1AoepEncode(CipherUtil.java:39)
	at svarzee.gps.gpsoauth.CipherUtil.createSignature(CipherUtil.java:26)
	at svarzee.gps.gpsoauth.Gpsoauth.performMasterLogin(Gpsoauth.java:57)
	at svarzee.gps.gpsoauth.Gpsoauth.performMasterLoginForToken(Gpsoauth.java:103)
	at svarzee.gps.gpsoauth.Gpsoauth.performMasterLoginForToken(Gpsoauth.java:90)
	at com.pokegoapi.auth.GoogleAutoCredentialProvider.login(GoogleAutoCredentialProvider.java:70)
	at com.pokegoapi.auth.GoogleAutoCredentialProvider.<init>(GoogleAutoCredentialProvider.java:63)
	at ink.abb.pogo.scraper.MainKt.getAuth(Main.kt:65)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:163)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:145)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: javax.crypto.IllegalBlockSizeException: Data must not be longer than 86 bytes
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:344)
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at svarzee.gps.gpsoauth.CipherUtil.pkcs1AoepEncode(CipherUtil.java:37)
	... 12 more
`
im very new to all this so if someone knows whats up that would be appriciated :)

thanks

**Comment by Danman00** [comment]
do you use base64 encoded password in your config ?

**Comment by langerhans** [comment]
What version? Java version? blah blah, there is an issze template for a reason, why did you delete it? Provide the info, then we might be able to help.

**Comment by charliedumdum** [comment]
@Danman00 no i dont

**Comment by langerhans** [comment]
Closing for not providing required info. Make sure you use the latest version and check your credentials and java version too.
