### ISSUE TITLE
got a exception please help

### ISSUE THREAD

**Issue by morinatsuz** [jabbink/PokemonGoBot#993]
I try to run this on my server then this appear

thanks in advance

Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unk               nown exception occurred.
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java               :155)
        at com.pokegoapi.api.settings.Settings.updateSettings(Settings.java:82)
        at com.pokegoapi.api.settings.Settings.<init>(Settings.java:69)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:95)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:180)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:145)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(Poke               monGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(Poke               monGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com               .pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java               :465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.Remote               ServerException: Got a unexpected http code : 403
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.c               all(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.c               all(OnSubscribeToObservableFuture.java:43)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java               :445)
        ... 11 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http co               de : 403
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHand               ler.java:197)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
        at java.lang.Thread.run(Thread.java:745)

**Comment by charliedumdum** [comment]
i have this too, maybe the bot just doesnt work anymore and needs an update. i think thats most likely the case.

**Comment by devinsba** [comment]
Niantic blocked cloud provider servers from connecting to their API. If you are trying to run on one that is probably the problem

**Comment by langerhans** [comment]
Comment above is right. Get a new server ;)

**Comment by Xat59** [comment]
Maybe we could use a proxy to avoid this behavior ?

**Comment by Sieberkev** [comment]
It is possible, and proxy support is build in since 0.6.0
