### ISSUE TITLE
Bot wont work [2]

### ISSUE THREAD

**Issue by GuilhermeFCardoso** [jabbink/PokemonGoBot#994]
11 Ago 11:59:26 [default] - Logging in to game server...
11 Ago 11:59:38 [default] - Logged in successfully
Getting profile data from pogo server.
Exception in thread "default" java.lang.UnsupportedClassVersionError: com/google/common/util/concurrent/AtomicDouble : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:43)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:294)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:145)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by Peyphour** [comment]
You do not have java 8
